<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/withCalendar/calendar-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789, 'iso8601');
$wrongTypeTests = [[null, 'null'], [true, 'boolean'], [1, 'number'], [1, 'bigint'], [19_970_327, 'large number'], [-19_970_327, 'negative number'], [1_234_567_890, 'very large integer'], [\Calendrics\Tests\Test262\JsSymbol::singleton(), 'symbol'], [(object) [], 'object'], [new \Calendrics\Spec\Duration(), 'duration instance']];
foreach ($wrongTypeTests as $__entry__) {
[$arg, $description] = array_pad($__entry__, 2, null);
if ($arg === null) { continue; }
Assert::throws(\TypeError::class, function () use (&$instance, &$arg) { return $instance->withCalendar($arg); }, "{$description} is not a valid calendar");
}
