<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/withCalendar/calendar-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789, 'iso8601');
$arg = 'iso8601';
$result = $instance->withCalendar($arg);
Assert::sameValue($result->calendarId, 'iso8601', "Calendar created from string \"{$arg}\"");
