<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainTime/prototype/toLocaleString/locales-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$time = new \Temporal\Spec\PlainTime(12, 34, 56, 987, 654, 321);
$defaultFormatter = new \Temporal\Tests\Test262\IntlDateTimeFormat([], []);
$expected = $defaultFormatter->format($time);
$actualExplicit = $time->toLocaleString();
Assert::sameValue($actualExplicit, $expected, 'default locale is determined by Intl.DateTimeFormat');
$actualImplicit = $time->toLocaleString();
Assert::sameValue($actualImplicit, $expected, 'default locale is determined by Intl.DateTimeFormat');
