<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainTime/prototype/toLocaleString/lone-options-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$epochMs = 1_735_213_600_321;
$legacyDateLocal = new \Calendrics\Tests\Test262\JsDate($epochMs);
$legacyDate = new \Calendrics\Tests\Test262\JsDate($epochMs + ($legacyDateLocal->getTimezoneOffset() * 60 * 1000));
$plainTime = new \Calendrics\Spec\PlainTime(11, 46, 40, 321);
foreach ([['hour' => 'numeric'], ['minute' => 'numeric'], ['second' => 'numeric'], ['fractionalSecondDigits' => 3], ['dayPeriod' => 'short']] as $options) {
$plainTimeResult = $plainTime->toLocaleString('en', $options);
$legacyDateResult = $legacyDate->toLocaleString('en', $options);
Assert::sameValue($plainTimeResult, $legacyDateResult, "PlainTime.toLocaleString should format lone option " . (json_encode($options)) . "");
}
