<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainTime/prototype/toLocaleString/options-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$time = new \Temporal\Spec\PlainTime(12, 34, 56, 987, 654, 321);
$defaultFormatter = new \Temporal\Tests\Test262\IntlDateTimeFormat('en', []);
$expected = $defaultFormatter->format($time);
$actualExplicit = $time->toLocaleString('en');
Assert::sameValue($actualExplicit, $expected, 'default options are determined by Intl.DateTimeFormat');
$actualImplicit = $time->toLocaleString('en');
Assert::sameValue($actualImplicit, $expected, 'default options are determined by Intl.DateTimeFormat');
