<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-not-overlapping-options.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$sampleEpochMs = 1_726_773_817_847;
$sampleEpochNs = 1_726_773_817_847_000_000;
$legacyDate = new \Calendrics\Tests\Test262\JsDate($sampleEpochMs);
$instant = new \Calendrics\Spec\Instant($sampleEpochNs);
$plainDateTime = new \Calendrics\Spec\PlainDateTime(2024, 9, 19, 12, 23, 37, 847);
$plainDate = new \Calendrics\Spec\PlainDate(2024, 9, 19);
$plainYearMonth = new \Calendrics\Spec\PlainYearMonth(2024, 9);
$plainMonthDay = new \Calendrics\Spec\PlainMonthDay(9, 19);
$plainTime = new \Calendrics\Spec\PlainTime(12, 23, 37, 847);
$dateStyleFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['dateStyle' => 'short', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$dateStyleResult = json_encode($dateStyleFormatter->formatRangeToParts($legacyDate, $legacyDate));
Assert::sameValue(json_encode($dateStyleFormatter->formatRangeToParts($instant, $instant)), $dateStyleResult, 'Instant with dateStyle');
Assert::sameValue(json_encode($dateStyleFormatter->formatRangeToParts($plainDateTime, $plainDateTime)), $dateStyleResult, 'PlainDateTime with dateStyle');
Assert::sameValue(json_encode($dateStyleFormatter->formatRangeToParts($plainDate, $plainDate)), $dateStyleResult, 'PlainDate with dateStyle');
Assert::notSameValue(json_encode($dateStyleFormatter->formatRangeToParts($plainYearMonth, $plainYearMonth)), $dateStyleResult, 'PlainYearMonth with dateStyle should not throw but day is omitted');
Assert::notSameValue(json_encode($dateStyleFormatter->formatRangeToParts($plainMonthDay, $plainMonthDay)), $dateStyleResult, 'PlainMonthDay with dateStyle should not throw but year is omitted');
Assert::throws(\TypeError::class, function () use (&$dateStyleFormatter, &$plainTime) { return $dateStyleFormatter->formatRangeToParts($plainTime, $plainTime); }, 'no overlap between dateStyle and PlainTime');
$yearFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['year' => 'numeric', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$yearResult = json_encode($yearFormatter->formatRangeToParts($legacyDate, $legacyDate));
Assert::sameValue(json_encode($yearFormatter->formatRangeToParts($instant, $instant)), $yearResult, 'Instant with year');
Assert::sameValue(json_encode($yearFormatter->formatRangeToParts($plainDateTime, $plainDateTime)), $yearResult, 'PlainDateTime with year');
Assert::sameValue(json_encode($yearFormatter->formatRangeToParts($plainDate, $plainDate)), $yearResult, 'PlainDate with year');
Assert::sameValue(json_encode($yearFormatter->formatRangeToParts($plainYearMonth, $plainYearMonth)), $yearResult, 'PlainYearMonth with year');
Assert::throws(\TypeError::class, function () use (&$yearFormatter, &$plainMonthDay) { return $yearFormatter->formatRangeToParts($plainMonthDay, $plainMonthDay); }, 'no overlap between year and PlainMonthDay');
Assert::throws(\TypeError::class, function () use (&$yearFormatter, &$plainTime) { return $yearFormatter->formatRangeToParts($plainTime, $plainTime); }, 'no overlap between year and PlainTime');
$dayFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['day' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$dayResult = json_encode($dayFormatter->formatRangeToParts($legacyDate, $legacyDate));
Assert::sameValue(json_encode($dayFormatter->formatRangeToParts($instant, $instant)), $dayResult, 'Instant with day');
Assert::sameValue(json_encode($dayFormatter->formatRangeToParts($plainDateTime, $plainDateTime)), $dayResult, 'PlainDateTime with day');
Assert::sameValue(json_encode($dayFormatter->formatRangeToParts($plainDate, $plainDate)), $dayResult, 'PlainDate with day');
Assert::throws(\TypeError::class, function () use (&$dayFormatter, &$plainYearMonth) { return $dayFormatter->formatRangeToParts($plainYearMonth, $plainYearMonth); }, 'no overlap between day and PlainYearMonth');
Assert::sameValue(json_encode($dayFormatter->formatRangeToParts($plainMonthDay, $plainMonthDay)), $dayResult, 'PlainMonthDay with day');
Assert::throws(\TypeError::class, function () use (&$dayFormatter, &$plainTime) { return $dayFormatter->formatRangeToParts($plainTime, $plainTime); }, 'no overlap between day and PlainTime');
$timeStyleFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['timeStyle' => 'long', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$timeStyleResult = json_encode($timeStyleFormatter->formatRangeToParts($legacyDate, $legacyDate));
Assert::sameValue(json_encode($timeStyleFormatter->formatRangeToParts($instant, $instant)), $timeStyleResult, 'Instant with timeStyle');
$timeStylePlainDateTimeResult = json_encode($timeStyleFormatter->formatRangeToParts($plainDateTime, $plainDateTime));
Assert::notSameValue($timeStylePlainDateTimeResult, $timeStyleResult, 'PlainDateTime with timeStyle should not throw but time zone is omitted');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainDate) { return $timeStyleFormatter->formatRangeToParts($plainDate, $plainDate); }, 'no overlap between PlainDate and timeStyle');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainYearMonth) { return $timeStyleFormatter->formatRangeToParts($plainYearMonth, $plainYearMonth); }, 'no overlap between PlainYearMonth and timeStyle');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainMonthDay) { return $timeStyleFormatter->formatRangeToParts($plainMonthDay, $plainMonthDay); }, 'no overlap between PlainMonthDay and timeStyle');
Assert::sameValue(json_encode($timeStyleFormatter->formatRangeToParts($plainTime, $plainTime)), $timeStylePlainDateTimeResult, 'PlainTime with timeStyle should be the same as PlainDateTime');
$hourFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['hour' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$hourResult = json_encode($hourFormatter->formatRangeToParts($legacyDate, $legacyDate));
Assert::sameValue(json_encode($hourFormatter->formatRangeToParts($instant, $instant)), $hourResult, 'Instant with hour');
Assert::sameValue(json_encode($hourFormatter->formatRangeToParts($plainDateTime, $plainDateTime)), $hourResult, 'PlainDateTime with hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainDate) { return $hourFormatter->formatRangeToParts($plainDate, $plainDate); }, 'no overlap between PlainDate and hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainYearMonth) { return $hourFormatter->formatRangeToParts($plainYearMonth, $plainYearMonth); }, 'no overlap between PlainYearMonth and hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainMonthDay) { return $hourFormatter->formatRangeToParts($plainMonthDay, $plainMonthDay); }, 'no overlap between PlainMonthDay and hour');
Assert::sameValue(json_encode($hourFormatter->formatRangeToParts($plainTime, $plainTime)), $hourResult, 'PlainTime with hour');
$monthFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['month' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$monthResult = json_encode($monthFormatter->formatRangeToParts($legacyDate, $legacyDate));
$monthHourFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['month' => '2-digit', 'hour' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$monthHourResult = json_encode($monthHourFormatter->formatRangeToParts($legacyDate, $legacyDate));
Assert::sameValue(json_encode($monthHourFormatter->formatRangeToParts($instant, $instant)), $monthHourResult, 'Instant with month+hour');
Assert::sameValue(json_encode($monthHourFormatter->formatRangeToParts($plainDateTime, $plainDateTime)), $monthHourResult, 'PlainDateTime with month+hour');
Assert::sameValue(json_encode($monthHourFormatter->formatRangeToParts($plainDate, $plainDate)), $monthResult, 'PlainDate with month+hour behaves the same as month');
Assert::sameValue(json_encode($monthHourFormatter->formatRangeToParts($plainYearMonth, $plainYearMonth)), $monthResult, 'PlainYearMonth with month+hour behaves the same as month');
Assert::sameValue(json_encode($monthHourFormatter->formatRangeToParts($plainMonthDay, $plainMonthDay)), $monthResult, 'PlainMonthDay with month+hour behaves the same as month');
Assert::sameValue(json_encode($monthHourFormatter->formatRangeToParts($plainTime, $plainTime)), $hourResult, 'PlainTime with month+hour behaves the same as hour');
