<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-throws-typeerror-with-dissimilar-types.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat();
$t1 = '1976-11-18T14:23:30+00:00[UTC]';
$t2 = '2020-02-20T15:44:56-05:00[America/New_York]';
Assert::throws(\TypeError::class, function () use (&$dtf, &$t1, &$t2) { return $dtf->formatRangeToParts(\Calendrics\Spec\Instant::from($t1), \Calendrics\Spec\PlainDateTime::from($t2)); }, '');
