<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-no-time-clip.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$findPart = function ($parts, $expectedType, $expectedSource) use (&$__dp0) {
return \Calendrics\Tests\Test262\Js::arrayFind($parts, function ($__dp0) use (&$expectedType, &$expectedSource) { $type = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'type'); $source = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'source'); return $type === $expectedType && $source === $expectedSource; })->value;
};
$calendars = ['iso8601', 'gregory'];
foreach ($calendars as $calendar) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', JsUndefined::strip(['calendar' => $calendar]));
$minDate = new \Calendrics\Spec\PlainDate(-271_821, 4, 19, $calendar);
$maxDate = new \Calendrics\Spec\PlainDate(275_760, 9, 13, $calendar);
$dateParts = $dtf->formatRangeToParts($minDate, $maxDate);
$yearPart = +$findPart($dateParts, 'year', 'startRange');
Assert::assertTrue($yearPart === -271_821 || $yearPart === 271_822, 'dateParts includes min year');
Assert::sameValue(+$findPart($dateParts, 'month', 'startRange'), 4, 'dateParts includes min month');
Assert::sameValue(+$findPart($dateParts, 'day', 'startRange'), 19, 'dateParts includes min day');
Assert::sameValue(+$findPart($dateParts, 'year', 'endRange'), 275_760, 'dateParts includes max year');
Assert::sameValue(+$findPart($dateParts, 'month', 'endRange'), 9, 'dateParts includes max month');
Assert::sameValue(+$findPart($dateParts, 'day', 'endRange'), 13, 'dateParts includes max day');
$minDateTime = new \Calendrics\Spec\PlainDateTime(-271_821, 4, 19, 0, 0, 0, 0, 0, 1, $calendar);
$maxDateTime = new \Calendrics\Spec\PlainDateTime(275_760, 9, 13, 23, 59, 59, 999, 999, 999, $calendar);
$dateTimeParts = $dtf->formatRangeToParts($minDateTime, $maxDateTime);
$yearPart = +$findPart($dateTimeParts, 'year', 'startRange');
Assert::assertTrue($yearPart === -271_821 || $yearPart === 271_822, 'dateTimeParts includes min year');
Assert::sameValue(+$findPart($dateTimeParts, 'month', 'startRange'), 4, 'dateTimeParts includes min month');
Assert::sameValue(+$findPart($dateTimeParts, 'day', 'startRange'), 19, 'dateTimeParts includes min day');
Assert::sameValue(+$findPart($dateTimeParts, 'year', 'endRange'), 275_760, 'dateTimeParts includes max year');
Assert::sameValue(+$findPart($dateTimeParts, 'month', 'endRange'), 9, 'dateTimeParts includes max month');
Assert::sameValue(+$findPart($dateTimeParts, 'day', 'endRange'), 13, 'dateTimeParts includes max day');
$minYearMonth = new \Calendrics\Spec\PlainYearMonth(-271_821, 4, $calendar);
$maxYearMonth = new \Calendrics\Spec\PlainYearMonth(275_760, 9, $calendar);
$yearMonthParts = $dtf->formatRangeToParts($minYearMonth, $maxYearMonth);
$yearPart = +$findPart($yearMonthParts, 'year', 'startRange');
Assert::assertTrue($yearPart === -271_821 || $yearPart === 271_822, 'yearMonthParts includes min year');
Assert::sameValue(+$findPart($yearMonthParts, 'month', 'startRange'), 4, 'yearMonthParts includes min month');
Assert::sameValue(+$findPart($yearMonthParts, 'year', 'endRange'), 275_760, 'yearMonthParts includes max year');
Assert::sameValue(+$findPart($yearMonthParts, 'month', 'endRange'), 9, 'yearMonthParts includes max month');
}
