<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-format-with-era.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$checkEra = function ($parts) {
foreach ($parts as $part) {
if ($part->type === 'era' && \Calendrics\Tests\Test262\Js::startsWith($part->value, 'A')) {
return true;
}
}
return false;
};
$formatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(['en'], (object) ['era' => 'narrow']);
Assert::assertTrue($checkEra($formatter->formatRangeToParts(new \Calendrics\Spec\PlainDate(2025, 11, 4, 'gregory'), new \Calendrics\Spec\PlainDate(2025, 11, 5, 'gregory'))), 'formatting a PlainDate should work');
Assert::assertTrue($checkEra($formatter->formatRangeToParts(new \Calendrics\Spec\PlainYearMonth(2025, 11, 'gregory'), new \Calendrics\Spec\PlainYearMonth(2025, 12, 'gregory'))), 'formatting a PlainYearMonth should work');
Assert::assertTrue(!$checkEra($formatter->formatRangeToParts(new \Calendrics\Spec\PlainMonthDay(11, 4, 'gregory'), new \Calendrics\Spec\PlainMonthDay(11, 14, 'gregory'))), 'formatting a PlainMonthDay should work');
Assert::assertTrue(!$checkEra($formatter->formatRangeToParts(new \Calendrics\Spec\PlainTime(14, 46), new \Calendrics\Spec\PlainTime(17, 46))), 'formatting a PlainTime should work');
Assert::assertTrue($checkEra($formatter->formatRangeToParts(new \Calendrics\Spec\PlainDateTime(2025, 11, 4, 14, 16, 0, 0, 0, 0, 'gregory'), new \Calendrics\Spec\PlainDateTime(2025, 11, 15, 14, 47, 0, 0, 0, 0, 'gregory'))), 'formatting a PlainDateTime should work');
Assert::assertTrue($checkEra($formatter->formatRangeToParts(new \Calendrics\Spec\Instant(0), new \Calendrics\Spec\Instant(1_000_000_000))), 'formatting an Instant should work');
