<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-plainmonthday-formatting-timezonename.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$locale = 'en-US-u-ca-gregory';
$timeZoneNameStyles = ['long', 'short', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric'];
$md1 = new \Calendrics\Spec\PlainMonthDay(1, 5, 'gregory', 1972);
$md2 = new \Calendrics\Spec\PlainMonthDay(1, 6, 'gregory', 1972);
foreach ($timeZoneNameStyles as $timeZoneNameStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, (object) JsUndefined::strip(['timeZoneName' => $timeZoneNameStyle]));
$result = $dtf->formatRangeToParts($md1, $md2);
Assert::assertTrue(is_array($result), "can format a PlainMonthDay with timeZoneName = {$timeZoneNameStyle}");
foreach ($result as $__obj__) {
$type = $__obj__['type'] ?? null;
Assert::notSameValue($type, 'timeZoneName', "formatting a PlainMonthDay with timeZoneName = {$timeZoneNameStyle} should not print a time zone");
}
}
