<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-plaintime-formatting-timezonename.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$locale = 'en-US';
$timeZoneNameStyles = ['long', 'short', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric'];
$time1 = new \Calendrics\Spec\PlainTime(12, 34);
$time2 = new \Calendrics\Spec\PlainTime(18, 45);
foreach ($timeZoneNameStyles as $timeZoneNameStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['timeZoneName' => $timeZoneNameStyle]));
$result = $dtf->formatRangeToParts($time1, $time2);
Assert::incomplete('untranslatable: Array.isArray');
}
