<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-plaintime-formatting-timezonename.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$locale = 'en-US';
$timeZoneNameStyles = ['long', 'short', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric'];
$time1 = new \Calendrics\Spec\PlainTime(12, 34);
$time2 = new \Calendrics\Spec\PlainTime(18, 45);
foreach ($timeZoneNameStyles as $timeZoneNameStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, (object) JsUndefined::strip(['timeZoneName' => $timeZoneNameStyle]));
$result = $dtf->formatRangeToParts($time1, $time2);
Assert::assertTrue(is_array($result), "can format a PlainTime with timeZoneName = {$timeZoneNameStyle}");
foreach ($result as $__obj__) {
$type = $__obj__['type'] ?? null;
Assert::notSameValue($type, 'timeZoneName', "formatting a PlainTime with timeZoneName = {$timeZoneNameStyle} should not print a time zone");
}
}
