<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-plaindate-formatting-timezonename.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$locale = 'en-US';
$timeZoneNameStyles = ['long', 'short', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric'];
$date1 = new \Calendrics\Spec\PlainDate(2026, 1, 5);
$date2 = new \Calendrics\Spec\PlainDate(2026, 1, 6);
foreach ($timeZoneNameStyles as $timeZoneNameStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['timeZoneName' => $timeZoneNameStyle]));
$result = $dtf->formatRangeToParts($date1, $date2);
Assert::incomplete('untranslatable: Array.isArray');
}
