<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-plainyearmonth-formatting-timezonename.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$locale = 'en-US';
$timeZoneNameStyles = ['long', 'short', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric'];
$ym1 = new \Calendrics\Spec\PlainYearMonth(2026, 1, 'gregory', 1);
$ym2 = new \Calendrics\Spec\PlainYearMonth(2026, 2, 'gregory', 1);
foreach ($timeZoneNameStyles as $timeZoneNameStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, (object) JsUndefined::strip(['timeZoneName' => $timeZoneNameStyle]));
$result = $dtf->formatRangeToParts($ym1, $ym2);
Assert::incomplete('untranslatable: Array.isArray');
}
