<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-plaindatetime-formatting-timezonename.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$locale = 'en-US';
$timeZoneNameStyles = ['long', 'short', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric'];
$pdt1 = new \Calendrics\Spec\PlainDateTime(2026, 1, 5, 11, 22);
$pdt2 = new \Calendrics\Spec\PlainDateTime(2026, 1, 5, 11, 23);
foreach ($timeZoneNameStyles as $timeZoneNameStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['timeZoneName' => $timeZoneNameStyle]));
$result = $dtf->formatRangeToParts($pdt1, $pdt2);
Assert::assertTrue(is_array($result), "can format a PlainDateTime with timeZoneName = {$timeZoneNameStyle}");
foreach ($result as $__obj__) {
$type = $__obj__['type'] ?? null;
Assert::notSameValue($type, 'timeZoneName', "formatting a PlainDateTime with timeZoneName = {$timeZoneNameStyle} should not print a time zone");
}
}
