<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRangeToParts/to-datetime-formattable-with-different-arg-kinds.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$callCount = 0;
// JS-only (inline JS ToPrimitive observer (valueOf/toString shorthand has no PHP equivalent)): invalidDateValue = { valueOf() { callCount += 1; // TimeClip(NaN) throws a RangeError in HandleDateTimeOthers, so if we see // a RangeError below, it means the…
$objects = [new \Calendrics\Spec\PlainDate(1970, 1, 1), new \Calendrics\Spec\PlainDateTime(1970, 1, 1), new \Calendrics\Spec\PlainTime(), new \Calendrics\Spec\PlainYearMonth(1970, 1), new \Calendrics\Spec\PlainMonthDay(1, 1), new \Calendrics\Spec\ZonedDateTime(0, 'UTC'), new \Calendrics\Spec\Instant(0)];
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat();
for ($i = 0; $i < (is_string($objects) ? strlen($objects) : count($objects)); ++$i) {
$object = $objects[$i];
// JS-only (references JS-only ToPrimitive tracker variable): assert.sameValue(callCount, i * 2);
// JS-only (references JS-only ToPrimitive tracker variable): assert.throws(TypeError, function() { dtf.formatRangeToParts(invalidDateValue, object); });
// JS-only (references JS-only ToPrimitive tracker variable): assert.sameValue(callCount, i * 2 + 1);
// JS-only (references JS-only ToPrimitive tracker variable): assert.throws(TypeError, function() { dtf.formatRangeToParts(object, invalidDateValue); });
// JS-only (references JS-only ToPrimitive tracker variable): assert.sameValue(callCount, i * 2 + 2);
}
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
