<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/since/calendar-temporal-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkToTemporalCalendarFastPath(function ($temporalObject) use (&$yearmonth) { $yearmonth = new \Calendrics\Spec\PlainYearMonth(2000, 5); $yearmonth->since((object) JsUndefined::strip(['year' => 2005, 'month' => 6, 'calendar' => $temporalObject])); });
