<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/since/largestunit-plurals-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$earlier = new \Calendrics\Spec\PlainYearMonth(2000, 5);
$later = new \Calendrics\Spec\PlainYearMonth(2001, 6);
$validUnits = ['year', 'month'];
TemporalHelpers::checkPluralUnitsAccepted(function ($largestUnit) use (&$later, &$earlier) { return $later->since($earlier, JsUndefined::strip(['largestUnit' => $largestUnit])); }, $validUnits);
