<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/format/fractionalSecondDigits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$d1 = new \Calendrics\Tests\Test262\JsDate(2019, 7, 10, 1, 2, 3, 234);
$d2 = new \Calendrics\Tests\Test262\JsDate(2019, 7, 10, 1, 2, 3, 567);
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', ['minute' => 'numeric', 'second' => 'numeric']);
Assert::sameValue($dtf->format($d1), '02:03', 'no fractionalSecondDigits');
Assert::sameValue($dtf->format($d2), '02:03', 'no fractionalSecondDigits');
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', ['minute' => 'numeric', 'second' => 'numeric', 'fractionalSecondDigits' => 1]);
Assert::sameValue($dtf->format($d1), '02:03.2', '1 fractionalSecondDigits round down');
Assert::sameValue($dtf->format($d2), '02:03.5', '1 fractionalSecondDigits round down');
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', ['minute' => 'numeric', 'second' => 'numeric', 'fractionalSecondDigits' => 2]);
Assert::sameValue($dtf->format($d1), '02:03.23', '2 fractionalSecondDigits round down');
Assert::sameValue($dtf->format($d2), '02:03.56', '2 fractionalSecondDigits round down');
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', ['minute' => 'numeric', 'second' => 'numeric', 'fractionalSecondDigits' => 3]);
Assert::sameValue($dtf->format($d1), '02:03.234', '3 fractionalSecondDigits round down');
Assert::sameValue($dtf->format($d2), '02:03.567', '3 fractionalSecondDigits round down');
