<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/format/temporal-objects-no-time-clip-weekday.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', ['weekday' => 'long', 'year' => 'numeric', 'month' => 'long', 'day' => 'numeric', 'calendar' => 'iso8601']);
$minDate = new \Calendrics\Spec\PlainDate(-271_821, 4, 19);
$minResult = $dtf->format($minDate);
$weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
Assert::incomplete('untranslatable: Array.prototype.some()');
