<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/format/temporal-plaindate-formatting-datetime-style.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$ensureDateField = function ($result, $field, $dateStyle) use (&$expected) {
[$searchValue, $present] = array_pad($expected[$dateStyle][$field], 2, null);
$verb = ($present ? 'should' : 'should not');
Assert::sameValue(\Calendrics\Tests\Test262\Js::includes($result, $searchValue), $present, "dateStyle={$dateStyle}: {$field} {$verb} appear");
};
$locale = 'en-US';
$timeZone = 'Pacific/Apia';
$dateStyles = ['full', 'long', 'medium', 'short'];
$timeStyles = ['full', 'long', 'medium', 'short'];
$date = new \Calendrics\Spec\PlainDate(2021, 8, 4);
$expected = (object) JsUndefined::strip(['full' => (object) JsUndefined::strip(['year' => ['2021', true], 'month' => ['8', false], 'day' => ['4', true]]), 'long' => (object) JsUndefined::strip(['year' => ['2021', true], 'month' => ['8', false], 'day' => ['4', true]]), 'medium' => (object) JsUndefined::strip(['year' => ['2021', true], 'month' => ['8', false], 'day' => ['4', true]]), 'short' => (object) JsUndefined::strip(['year' => ['21', true], 'month' => ['8', true], 'day' => ['4', true]])]);
foreach ($timeStyles as $timeStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, (object) JsUndefined::strip(['timeStyle' => $timeStyle, 'timeZone' => $timeZone]));
Assert::throws(\TypeError::class, function () use (&$dtf, &$date) { return $dtf->format($date); }, "timeStyle={$timeStyle}");
}
foreach ($dateStyles as $dateStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, (object) JsUndefined::strip(['dateStyle' => $dateStyle, 'timeZone' => $timeZone]));
$result = $dtf->format($date);
$ensureDateField($result, 'year', $dateStyle);
$ensureDateField($result, 'month', $dateStyle);
$ensureDateField($result, 'day', $dateStyle);
foreach ($timeStyles as $timeStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, (object) JsUndefined::strip(['dateStyle' => $dateStyle, 'timeStyle' => $timeStyle, 'timeZone' => $timeZone]));
Assert::sameValue($dtf->format($date), $result, "dateStyle = {$dateStyle}, timeStyle = {$timeStyle}");
}
}
