<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/format/temporal-objects-not-overlapping-options.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$sampleEpochMs = 1_726_773_817_847;
$sampleEpochNs = 1_726_773_817_847_000_000;
$legacyDate = new \Calendrics\Tests\Test262\JsDate($sampleEpochMs);
$instant = new \Calendrics\Spec\Instant($sampleEpochNs);
$plainDateTime = new \Calendrics\Spec\PlainDateTime(2024, 9, 19, 12, 23, 37, 847);
$plainDate = new \Calendrics\Spec\PlainDate(2024, 9, 19);
$plainYearMonth = new \Calendrics\Spec\PlainYearMonth(2024, 9);
$plainMonthDay = new \Calendrics\Spec\PlainMonthDay(9, 19);
$plainTime = new \Calendrics\Spec\PlainTime(12, 23, 37, 847);
$dateStyleFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['dateStyle' => 'short', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$dateStyleResult = $dateStyleFormatter->format($legacyDate);
Assert::sameValue($dateStyleFormatter->format($instant), $dateStyleResult, 'Instant with dateStyle');
Assert::sameValue($dateStyleFormatter->format($plainDateTime), $dateStyleResult, 'PlainDateTime with dateStyle');
Assert::sameValue($dateStyleFormatter->format($plainDate), $dateStyleResult, 'PlainDate with dateStyle');
Assert::notSameValue($dateStyleFormatter->format($plainYearMonth), $dateStyleResult, 'PlainYearMonth with dateStyle should not throw but day is omitted');
Assert::notSameValue($dateStyleFormatter->format($plainMonthDay), $dateStyleResult, 'PlainMonthDay with dateStyle should not throw but year is omitted');
Assert::throws(\TypeError::class, function () use (&$dateStyleFormatter, &$plainTime) { return $dateStyleFormatter->format($plainTime); }, 'no overlap between dateStyle and PlainTime');
$yearFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['year' => 'numeric', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$yearResult = $yearFormatter->format($legacyDate);
Assert::sameValue($yearFormatter->format($instant), $yearResult, 'Instant with year');
Assert::sameValue($yearFormatter->format($plainDateTime), $yearResult, 'PlainDateTime with year');
Assert::sameValue($yearFormatter->format($plainDate), $yearResult, 'PlainDate with year');
Assert::sameValue($yearFormatter->format($plainYearMonth), $yearResult, 'PlainYearMonth with year');
Assert::throws(\TypeError::class, function () use (&$yearFormatter, &$plainMonthDay) { return $yearFormatter->format($plainMonthDay); }, 'no overlap between year and PlainMonthDay');
Assert::throws(\TypeError::class, function () use (&$yearFormatter, &$plainTime) { return $yearFormatter->format($plainTime); }, 'no overlap between year and PlainTime');
$dayFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['day' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$dayResult = $dayFormatter->format($legacyDate);
Assert::sameValue($dayFormatter->format($instant), $dayResult, 'Instant with day');
Assert::sameValue($dayFormatter->format($plainDateTime), $dayResult, 'PlainDateTime with day');
Assert::sameValue($dayFormatter->format($plainDate), $dayResult, 'PlainDate with day');
Assert::throws(\TypeError::class, function () use (&$dayFormatter, &$plainYearMonth) { return $dayFormatter->format($plainYearMonth); }, 'no overlap between day and PlainYearMonth');
Assert::sameValue($dayFormatter->format($plainMonthDay), $dayResult, 'PlainMonthDay with day');
Assert::throws(\TypeError::class, function () use (&$dayFormatter, &$plainTime) { return $dayFormatter->format($plainTime); }, 'no overlap between day and PlainTime');
$timeStyleFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['timeStyle' => 'long', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$timeStyleResult = $timeStyleFormatter->format($legacyDate);
Assert::sameValue($timeStyleFormatter->format($instant), $timeStyleResult, 'Instant with timeStyle');
$timeStylePlainDateTimeResult = $timeStyleFormatter->format($plainDateTime);
Assert::notSameValue($timeStylePlainDateTimeResult, $timeStyleResult, 'PlainDateTime with timeStyle should not throw but time zone is omitted');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainDate) { return $timeStyleFormatter->format($plainDate); }, 'no overlap between PlainDate and timeStyle');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainYearMonth) { return $timeStyleFormatter->format($plainYearMonth); }, 'no overlap between PlainYearMonth and timeStyle');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainMonthDay) { return $timeStyleFormatter->format($plainMonthDay); }, 'no overlap between PlainMonthDay and timeStyle');
Assert::sameValue($timeStyleFormatter->format($plainTime), $timeStylePlainDateTimeResult, 'PlainTime with timeStyle should be the same as PlainDateTime');
$hourFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['hour' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$hourResult = $hourFormatter->format($legacyDate);
Assert::sameValue($hourFormatter->format($instant), $hourResult, 'Instant with hour');
Assert::sameValue($hourFormatter->format($plainDateTime), $hourResult, 'PlainDateTime with hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainDate) { return $hourFormatter->format($plainDate); }, 'no overlap between PlainDate and hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainYearMonth) { return $hourFormatter->format($plainYearMonth); }, 'no overlap between PlainYearMonth and hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainMonthDay) { return $hourFormatter->format($plainMonthDay); }, 'no overlap between PlainMonthDay and hour');
Assert::sameValue($hourFormatter->format($plainTime), $hourResult, 'PlainTime with hour');
$monthFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['month' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$monthResult = $monthFormatter->format($legacyDate);
$monthHourFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, (object) ['month' => '2-digit', 'hour' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$monthHourResult = $monthHourFormatter->format($legacyDate);
Assert::sameValue($monthHourFormatter->format($instant), $monthHourResult, 'Instant with month+hour');
Assert::sameValue($monthHourFormatter->format($plainDateTime), $monthHourResult, 'PlainDateTime with month+hour');
Assert::sameValue($monthHourFormatter->format($plainDate), $monthResult, 'PlainDate with month+hour behaves the same as month');
Assert::sameValue($monthHourFormatter->format($plainYearMonth), $monthResult, 'PlainYearMonth with month+hour behaves the same as month');
Assert::sameValue($monthHourFormatter->format($plainMonthDay), $monthResult, 'PlainMonthDay with month+hour behaves the same as month');
Assert::sameValue($monthHourFormatter->format($plainTime), $hourResult, 'PlainTime with month+hour behaves the same as hour');
