<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/format/temporal-plaintime-formatting-datetime-style.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$ensureTimeField = function ($result, $field, $value, $timeStyle) use (&$expected) {
$present = $expected[$timeStyle][$field];
$verb = ($present ? 'should' : 'should not');
Assert::sameValue(\Calendrics\Tests\Test262\Js::includes($result, $value), $present, "timeStyle={$timeStyle}: {$field} {$verb} appear");
};
$locale = 'en-US';
$timeZone = 'Pacific/Apia';
$dateStyles = ['full', 'long', 'medium', 'short'];
$timeStyles = ['full', 'long', 'medium', 'short'];
$time = new \Calendrics\Spec\PlainTime(0, 34, 56, 777, 888, 999);
$expected = JsUndefined::strip(['full' => ['hour' => true, 'minute' => true, 'second' => true, 'millisecond' => false, 'microsecond' => false, 'nanosecond' => false], 'long' => ['hour' => true, 'minute' => true, 'second' => true, 'millisecond' => false, 'microsecond' => false, 'nanosecond' => false], 'medium' => ['hour' => true, 'minute' => true, 'second' => true, 'millisecond' => false, 'microsecond' => false, 'nanosecond' => false], 'short' => ['hour' => true, 'minute' => true, 'second' => false, 'millisecond' => false, 'microsecond' => false, 'nanosecond' => false]]);
foreach ($dateStyles as $dateStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['dateStyle' => $dateStyle, 'timeZone' => $timeZone]));
Assert::throws(\TypeError::class, function () use (&$dtf, &$time) { return $dtf->format($time); }, "dateStyle={$dateStyle}");
}
foreach ($timeStyles as $timeStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['timeStyle' => $timeStyle, 'timeZone' => $timeZone]));
$result = $dtf->format($time);
$ensureTimeField($result, 'hour', '12', $timeStyle);
$ensureTimeField($result, 'minute', '34', $timeStyle);
$ensureTimeField($result, 'second', '56', $timeStyle);
$ensureTimeField($result, 'millisecond', '777', $timeStyle);
$ensureTimeField($result, 'microsecond', '888', $timeStyle);
$ensureTimeField($result, 'nanosecond', '999', $timeStyle);
foreach ($dateStyles as $dateStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['dateStyle' => $dateStyle, 'timeStyle' => $timeStyle, 'timeZone' => $timeZone]));
Assert::sameValue($dtf->format($time), $result, "dateStyle = {$dateStyle}, timeStyle = {$timeStyle}");
}
}
