<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/format/temporal-objects-no-time-clip-non-latin-numerals.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('ar-EG', (object) ['year' => 'numeric', 'month' => 'numeric', 'day' => 'numeric', 'calendar' => 'iso8601']);
$maxDate = new \Calendrics\Spec\PlainDate(275_760, 9, 13);
$result = $dtf->format($maxDate);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '١٣'), 'max date should include day 13 in Arabic-Indic digits, got: ' . $result);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '٩'), 'max date should include month 9 in Arabic-Indic digit, got: ' . $result);
$minDate = new \Calendrics\Spec\PlainDate(-271_821, 4, 19);
$minResult = $dtf->format($minDate);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($minResult, '١٩'), 'min date should include day 19 in Arabic-Indic digits, got: ' . $minResult);
