<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/format/temporal-plaintime-formatting-timezonename.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$locale = 'en-US';
$timeZoneNameStyles = ['long', 'short', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric'];
$time = new \Calendrics\Spec\PlainTime(12, 34);
foreach ($timeZoneNameStyles as $timeZoneNameStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['timeZoneName' => $timeZoneNameStyle]));
$timeZoneDisplayName = \Calendrics\Tests\Test262\Js::arrayFind($dtf->formatToParts(\Calendrics\Tests\Test262\Js::dateUTC(1970, 0, 1, 12, 34)), function ($__dp0) { $type = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'type'); return $type === 'timeZoneName'; })->value;
$result = $dtf->format($time);
Assert::sameValue(is_string($result), true, "can format a PlainTime with timeZoneName = {$timeZoneNameStyle}");
Assert::incomplete('untranslatable: Array.prototype.indexOf()');
}
