<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/format/temporal-plainyearmonth-formatting-datetime-style.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$ensureDateField = function ($result, $field, $dateStyle) use (&$expected) {
[$searchValue, $present] = array_pad($expected[$dateStyle][$field], 2, null);
$verb = ($present ? 'should' : 'should not');
Assert::sameValue(\Calendrics\Tests\Test262\Js::includes($result, $searchValue), $present, "dateStyle={$dateStyle}: {$field} {$verb} appear");
};
$locale = 'en-US';
$timeZone = 'Pacific/Apia';
$dateStyles = ['full', 'long', 'medium', 'short'];
$timeStyles = ['full', 'long', 'medium', 'short'];
$yearmonth = new \Calendrics\Spec\PlainYearMonth(2222, 1, 'gregory', 30);
$expected = JsUndefined::strip(['full' => JsUndefined::strip(['year' => ['2222', true], 'month' => ['1', false], 'day' => ['30', false]]), 'long' => JsUndefined::strip(['year' => ['2222', true], 'month' => ['1', false], 'day' => ['30', false]]), 'medium' => JsUndefined::strip(['year' => ['2222', true], 'month' => ['1', false], 'day' => ['30', false]]), 'short' => JsUndefined::strip(['year' => ['22', true], 'month' => ['1', true], 'day' => ['30', false]])]);
foreach ($timeStyles as $timeStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['timeStyle' => $timeStyle, 'timeZone' => $timeZone]));
Assert::throws(\TypeError::class, function () use (&$dtf, &$yearmonth) { return $dtf->format($yearmonth); }, "timeStyle={$timeStyle}");
}
foreach ($dateStyles as $dateStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['dateStyle' => $dateStyle, 'timeZone' => $timeZone]));
$result = $dtf->format($yearmonth);
$ensureDateField($result, 'year', $dateStyle);
$ensureDateField($result, 'month', $dateStyle);
$ensureDateField($result, 'day', $dateStyle);
foreach ($timeStyles as $timeStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['dateStyle' => $dateStyle, 'timeStyle' => $timeStyle, 'timeZone' => $timeZone]));
Assert::sameValue($dtf->format($yearmonth), $result, "dateStyle = {$dateStyle}, timeStyle = {$timeStyle}");
}
}
