<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/format/temporal-objects-resolved-time-zone.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$usDayPeriodSpace = (\Calendrics\Tests\Test262\Js::truthy($__logical0 = \Calendrics\Tests\Test262\Js::arrayFind(new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US', ['timeStyle' => 'short'])->formatToParts(0), fn($part, $i, $parts) => $part->type === 'literal' && $parts[$i + 1]->type === 'dayPeriod')?->value) ? $__logical0 : '');
$formatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US', ['timeZone' => 'Pacific/Apia']);
$date = new \Calendrics\Spec\PlainDate(2021, 8, 4);
$dateResult = $formatter->format($date);
Assert::sameValue($dateResult, '8/4/2021', 'plain date');
$datetime1 = new \Calendrics\Spec\PlainDateTime(2021, 8, 4, 0, 30, 45, 123, 456, 789);
$datetimeResult1 = $formatter->format($datetime1);
Assert::sameValue($datetimeResult1, "8/4/2021, 12:30:45{$usDayPeriodSpace}AM", 'plain datetime close to beginning of day');
$datetime2 = new \Calendrics\Spec\PlainDateTime(2021, 8, 4, 23, 30, 45, 123, 456, 789);
$datetimeResult2 = $formatter->format($datetime2);
Assert::sameValue($datetimeResult2, "8/4/2021, 11:30:45{$usDayPeriodSpace}PM", 'plain datetime close to end of day');
$monthDay = new \Calendrics\Spec\PlainMonthDay(8, 4, 'gregory');
$monthDayResult = $formatter->format($monthDay);
Assert::sameValue($monthDayResult, '8/4', 'plain month-day');
$time1 = new \Calendrics\Spec\PlainTime(0, 30, 45, 123, 456, 789);
$timeResult1 = $formatter->format($time1);
Assert::sameValue($timeResult1, "12:30:45{$usDayPeriodSpace}AM", 'plain time close to beginning of day');
$time2 = new \Calendrics\Spec\PlainTime(23, 30, 45, 123, 456, 789);
$timeResult2 = $formatter->format($time2);
Assert::sameValue($timeResult2, "11:30:45{$usDayPeriodSpace}PM", 'plain time close to end of day');
$month = new \Calendrics\Spec\PlainYearMonth(2021, 8, 'gregory');
$monthResult = $formatter->format($month);
Assert::sameValue($monthResult, '8/2021', 'plain year-month');
