<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/add/argument-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$plainTime = new \Calendrics\Spec\PlainTime(15, 23, 30, 123, 456, 789);
$duration = \Calendrics\Spec\Duration::from('PT16H');
TemporalHelpers::assertPlainTime($plainTime->add($duration), 7, 23, 30, 123, 456, 789);
