<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDateTime/prototype/toLocaleString/datestyle-and-timestyle.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$item = new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 0, 0, 0, 0, 0, 0);
$result = $item->toLocaleString('en', (object) ['dateStyle' => 'full', 'timeStyle' => 'full']);
Assert::sameValue(\Calendrics\Tests\Test262\Js::includes($result, ':00'), true, 'using both dateStyle and timeStyle should not throw');
