<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDateTime/prototype/toLocaleString/dateStyle.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$dateGregorian = new \Calendrics\Spec\PlainDateTime(2024, 3, 26, 10, 30, 0, 0, 0, 0, 'gregory');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateGregorian->toLocaleString('en-u-ca-gregory', (object) ['dateStyle' => 'long']), 'March'), 'dateStyle: long writes month of March out in full');
Assert::assertTrue(!\Calendrics\Tests\Test262\Js::includes($dateGregorian->toLocaleString('en-u-ca-gregory', (object) ['dateStyle' => 'short']), 'March'), 'dateStyle: short does not write month of March out in full');
$dateIslamic = new \Calendrics\Spec\PlainDateTime(2024, 3, 26, 10, 30, 0, 0, 0, 0, 'islamic-tbla');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateIslamic->toLocaleString('en-u-ca-islamic-tbla', (object) ['dateStyle' => 'long']), 'Ramadan'), 'dateStyle: long writes month of Ramadan out in full');
Assert::assertTrue(!\Calendrics\Tests\Test262\Js::includes($dateIslamic->toLocaleString('en-u-ca-islamic-tbla', (object) ['dateStyle' => 'short']), 'Ramadan'), 'dateStyle: short does not write month of Ramadan out in full');
