<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDateTime/prototype/toLocaleString/default-includes-time-not-time-zone-name.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$plainDateTime = new \Calendrics\Spec\PlainDateTime(2024, 12, 26, 11, 46, 40, 321);
$result = $plainDateTime->toLocaleString('en', ['timeZone' => 'UTC']);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '2024'), "PlainDateTime formatted with no options {$result} should include year");
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '12') || \Calendrics\Tests\Test262\Js::includes($result, 'Dec'), "PlainDateTime formatted with no options {$result} should include month");
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '26'), "PlainDateTime formatted with no options {$result} should include day");
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '11'), "PlainDateTime formatted with no options {$result} should include hour");
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '46'), "PlainDateTime formatted with no options {$result} should include minute");
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '40'), "PlainDateTime formatted with no options {$result} should include second");
Assert::assertTrue(!\Calendrics\Tests\Test262\Js::includes($result, '321'), "PlainDateTime formatted with no options {$result} should not include fractional second digits");
Assert::assertTrue(!\Calendrics\Tests\Test262\Js::includes($result, 'UTC') && !\Calendrics\Tests\Test262\Js::includes($result, 'Coordinated Universal Time'), "PlainDateTime formatted with no options {$result} should not include time zone name");
