<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/hoursInDay/get-start-of-day-throws.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$zdt = \Calendrics\Spec\ZonedDateTime::fromEpochParts(-8640000000000, 0, '-01');
Assert::throws(\RangeException::class, function () use (&$zdt) { return $zdt->hoursInDay; }, '');
$zdt = \Calendrics\Spec\ZonedDateTime::fromEpochParts(-8640000000000, 0, '+01');
Assert::throws(\RangeException::class, function () use (&$zdt) { return $zdt->hoursInDay; }, '');
$zdt = \Calendrics\Spec\ZonedDateTime::fromEpochParts(8640000000000, 0, '-01');
Assert::throws(\RangeException::class, function () use (&$zdt) { return $zdt->hoursInDay; }, '');
