<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/argument.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::throws(\TypeError::class, fn() => new \Calendrics\Spec\Instant(), 'undefined');
Assert::throws(\TypeError::class, fn() => new \Calendrics\Spec\Instant(), 'undefined');
Assert::throws(\TypeError::class, fn() => new \Calendrics\Spec\Instant(null), 'null');
Assert::throws(\TypeError::class, fn() => new \Calendrics\Spec\Instant(42.0), 'number');
Assert::throws(\TypeError::class, fn() => new \Calendrics\Spec\Instant(\Calendrics\Tests\Test262\JsSymbol::singleton()), 'symbol');
