<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/with/options-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$badOptions = [null, true, 'some string', \Calendrics\Tests\Test262\JsSymbol::singleton(), 1, 2];
$instance = new \Calendrics\Spec\PlainTime();
foreach ($badOptions as $value) {
Assert::throws(\TypeError::class, function () use (&$instance, &$value) { return $instance->with(['minute' => 45], $value); }, "TypeError on wrong options type " . (gettype($value)) . "");
Assert::throws(\RangeException::class, function () use (&$instance, &$value) { return $instance->with(JsUndefined::strip(['minute' => INF]), $value); }, 'Partial time processed before throwing TypeError');
}
