<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/with/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = new \Temporal\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['overflow' => 'reject'], 'options');
$instance = new \Temporal\Spec\PlainTime(12);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->with((object) ['hour' => 25], $options); }, 'overflow reject exception thrown');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
