<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/from/argument-propertybag-optional-properties.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$minimumProperties = ['hour' => 0];
$allProperties = ['hour' => 0, 'minute' => 0, 'second' => 0, 'millisecond' => 0, 'microsecond' => 0, 'nanosecond' => 0];
$resultWithout = \Calendrics\Spec\PlainTime::from($minimumProperties);
$resultWith = \Calendrics\Spec\PlainTime::from($allProperties);
Assert::assertTrue($resultWithout->equals($resultWith), 'results should be the same with and without optional properties');
