<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/from/argument-string-time-designator-required-for-disambiguation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
foreach (TemporalHelpers::isoPlainTimeStringsAmbiguous() as $string) {
$arg = $string;
Assert::throws(\RangeException::class, function () use (&$arg) { return \Calendrics\Spec\PlainTime::from($arg); }, "'{$arg}' is ambiguous and requires T prefix");
$arg = "T{$string}";
\Calendrics\Spec\PlainTime::from($arg);
$arg = " {$string}";
Assert::throws(\RangeException::class, function () use (&$arg) { return \Calendrics\Spec\PlainTime::from($arg); }, "space is not accepted as a substitute for T prefix: '{$arg}'");
}
foreach (TemporalHelpers::isoPlainTimeStringsUnambiguous() as $arg) {
\Calendrics\Spec\PlainTime::from($arg);
}
