<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/from/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$base = ['hour' => 15, 'minute' => 30, 'second' => 45, 'millisecond' => 987, 'microsecond' => 654, 'nanosecond' => 321];
foreach ([INF, -INF] as $inf) {
foreach (['hour', 'minute', 'second', 'millisecond', 'microsecond', 'nanosecond'] as $prop) {
foreach (['constrain', 'reject'] as $overflow) {
Assert::throws(\RangeException::class, function () use (&$base, &$prop, &$inf, &$overflow) { return \Calendrics\Spec\PlainTime::from(JsUndefined::strip(array_merge($base, [$prop => $inf])), JsUndefined::strip(['overflow' => $overflow])); }, "{$prop} property cannot be {$inf} (overflow {$overflow}");
$calls = new \Calendrics\Tests\Test262\ObserverTrace();
$obj = TemporalHelpers::toPrimitiveObserver($calls, $inf, $prop);
Assert::throws(\RangeException::class, function () use (&$base, &$prop, &$obj, &$overflow) { return \Calendrics\Spec\PlainTime::from(JsUndefined::strip(array_merge($base, [$prop => $obj])), JsUndefined::strip(['overflow' => $overflow])); }, '');
Assert::compareObserverTrace($calls, ["get {$prop}.valueOf", "call {$prop}.valueOf"], 'it fails after fetching the primitive value');
}
}
}
