<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/from/observable-get-overflow-argument-string-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
Assert::incomplete('untranslatable object property');
