<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/from/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expectedOptionsReading = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$expectedOpsForPrimitiveOptions = ['get fields.hour', 'get fields.hour.valueOf', 'call fields.hour.valueOf', 'get fields.microsecond', 'get fields.microsecond.valueOf', 'call fields.microsecond.valueOf', 'get fields.millisecond', 'get fields.millisecond.valueOf', 'call fields.millisecond.valueOf', 'get fields.minute', 'get fields.minute.valueOf', 'call fields.minute.valueOf', 'get fields.nanosecond', 'get fields.nanosecond.valueOf', 'call fields.nanosecond.valueOf', 'get fields.second', 'get fields.second.valueOf', 'call fields.second.valueOf'];
$expected = array_merge($expectedOpsForPrimitiveOptions, $expectedOptionsReading);
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$fields = TemporalHelpers::propertyBagObserver($actual, ['hour' => 1.7, 'minute' => 1.7, 'second' => 1.7, 'millisecond' => 1.7, 'microsecond' => 1.7, 'nanosecond' => 1.7, 'calendar' => 'iso8601'], 'fields');
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'constrain'], 'options');
$result = \Calendrics\Spec\PlainTime::from($fields, $options);
Assert::compareObserverTrace($actual, $expected, 'order of operations');
$actual->clear();
\Calendrics\Spec\PlainTime::from(new \Calendrics\Spec\PlainTime(12, 34), $options);
Assert::compareObserverTrace($actual, $expectedOptionsReading, 'order of operations when cloning a PlainTime instance');
$actual->clear();
\Calendrics\Spec\PlainTime::from(new \Calendrics\Spec\PlainDateTime(2000, 5, 2), $options);
Assert::compareObserverTrace($actual, $expectedOptionsReading, 'order of operations when converting a PlainDateTime instance');
$actual->clear();
\Calendrics\Spec\PlainTime::from(new \Calendrics\Spec\ZonedDateTime(0, 'UTC'), $options);
Assert::compareObserverTrace($actual, $expectedOptionsReading, 'order of operations when converting a ZonedDateTime instance');
$actual->clear();
\Calendrics\Spec\PlainTime::from('12:34', $options);
Assert::compareObserverTrace($actual, $expectedOptionsReading, 'order of operations when parsing a string');
$actual->clear();
// JS-only (JS rejects non-object options via ToObject; PHP accepts null as "absent"): assert.throws(TypeError, () => Temporal.PlainTime.from(fields, null));
// JS-only (trace covers a call skipped above, so the tracker is empty here): assert.compareArray(actual, expectedOpsForPrimitiveOptions, "item fields are read before TypeError is thrown for primitive options");
$actual->clear();
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
