<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/from/overflow-reject.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
Assert::throws(\RangeException::class, fn() => \Calendrics\Spec\PlainTime::from(['hour' => 26], ['overflow' => 'reject']), '');
TemporalHelpers::assertPlainTime(\Calendrics\Spec\PlainTime::from(['hour' => 22], ['overflow' => 'reject']), 22, 0, 0, 0, 0, 0);
