<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/equals/argument-plaindate.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkToTemporalPlainDateTimeFastPath(function ($date, $calendar) use (&$datetime) { $datetime = new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 0, 0, 0, 0, 0, 0, $calendar); Assert::assertTrue($datetime->equals($date), ''); });
