<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/equals/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$dt1 = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789);
$dt2 = new \Calendrics\Spec\PlainDateTime(2019, 10, 29, 10, 46, 38, 271, 986, 102);
$dt3 = new \Calendrics\Spec\PlainDateTime(2019, 10, 29, 10, 46, 38, 271, 986, 102);
$dt4 = new \Calendrics\Spec\PlainDateTime(2019, 10, 29, 15, 23, 30, 123, 456, 789);
$dt5 = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 10, 46, 38, 271, 986, 102);
Assert::sameValue($dt1->equals($dt1), true, 'equal');
Assert::sameValue($dt1->equals($dt2), false, 'unequal');
Assert::sameValue($dt2->equals($dt3), true, 'equal with different objects');
Assert::sameValue($dt2->equals($dt4), false, 'same date, different time');
Assert::sameValue($dt2->equals($dt5), false, 'same time, different date');
