<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/subtract/leap-year-coptic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$calendar = 'coptic';
$options = ['overflow' => 'reject'];
$leapDay = \Calendrics\Spec\PlainYearMonth::from(JsUndefined::strip(['year' => 1739, 'monthCode' => 'M13', 'calendar' => $calendar]), $options);
$years1 = new \Calendrics\Spec\Duration(-1);
$years1n = new \Calendrics\Spec\Duration(1);
$years4 = new \Calendrics\Spec\Duration(-4);
$years4n = new \Calendrics\Spec\Duration(4);
TemporalHelpers::assertPlainYearMonth($leapDay->subtract($years1, $options), 1740, 13, 'M13', 'Adding 1 year to epagomenal month', 'am', 1740, null);
TemporalHelpers::assertPlainYearMonth($leapDay->subtract($years1n, $options), 1738, 13, 'M13', 'Subtracting 1 year from epagomenal month', 'am', 1738, null);
TemporalHelpers::assertPlainYearMonth($leapDay->subtract($years4, $options), 1743, 13, 'M13', 'Adding 4 years to epagomenal month', 'am', 1743, null);
TemporalHelpers::assertPlainYearMonth($leapDay->subtract($years4n, $options), 1735, 13, 'M13', 'Subtracting 4 years from epagomenal month', 'am', 1735, null);
