<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/compare/compare-calendar.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$ym1 = new \Calendrics\Spec\PlainYearMonth(2000, 1, 'iso8601', 1);
$ym2 = new \Calendrics\Spec\PlainYearMonth(2000, 1, 'gregory', 1);
Assert::sameValue(\Calendrics\Spec\PlainYearMonth::compare($ym1, $ym2), 0, '');
