<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/compare/exhaustive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$cal1 = 'iso8601';
$cal2 = 'gregory';
Assert::sameValue(\Calendrics\Spec\PlainYearMonth::compare(new \Calendrics\Spec\PlainYearMonth(2000, 5, $cal1), new \Calendrics\Spec\PlainYearMonth(1987, 5, $cal2)), 1, 'year >');
Assert::sameValue(\Calendrics\Spec\PlainYearMonth::compare(new \Calendrics\Spec\PlainYearMonth(1981, 12, $cal1), new \Calendrics\Spec\PlainYearMonth(2048, 12, $cal2)), -1, 'year <');
Assert::sameValue(\Calendrics\Spec\PlainYearMonth::compare(new \Calendrics\Spec\PlainYearMonth(2000, 5, $cal1), new \Calendrics\Spec\PlainYearMonth(2000, 3, $cal2)), 1, 'month >');
Assert::sameValue(\Calendrics\Spec\PlainYearMonth::compare(new \Calendrics\Spec\PlainYearMonth(1981, 4, $cal1), new \Calendrics\Spec\PlainYearMonth(1981, 12, $cal2)), -1, 'month <');
Assert::sameValue(\Calendrics\Spec\PlainYearMonth::compare(new \Calendrics\Spec\PlainYearMonth(2000, 5, $cal1, 30), new \Calendrics\Spec\PlainYearMonth(2000, 5, $cal2, 14)), 1, 'reference day >');
Assert::sameValue(\Calendrics\Spec\PlainYearMonth::compare(new \Calendrics\Spec\PlainYearMonth(1981, 4, $cal1, 1), new \Calendrics\Spec\PlainYearMonth(1981, 4, $cal2, 12)), -1, 'reference day <');
Assert::sameValue(\Calendrics\Spec\PlainYearMonth::compare(new \Calendrics\Spec\PlainYearMonth(2000, 5, $cal1), new \Calendrics\Spec\PlainYearMonth(2000, 5, $cal2)), 0, '=');
