<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/subtract/overflow-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$datetime = new \Calendrics\Spec\PlainDateTime(2000, 5, 31, 12);
$duration = new \Calendrics\Spec\Duration(3, 1);
$explicit = $datetime->subtract($duration, (object) []);
TemporalHelpers::assertPlainDateTime($explicit, 1997, 4, 'M04', 30, 12, 0, 0, 0, 0, 0, 'default overflow is constrain');
$implicit = $datetime->subtract($duration, (object) []);
TemporalHelpers::assertPlainDateTime($implicit, 1997, 4, 'M04', 30, 12, 0, 0, 0, 0, 0, 'default overflow is constrain');
$lambda = $datetime->subtract($duration, function () {  });
TemporalHelpers::assertPlainDateTime($lambda, 1997, 4, 'M04', 30, 12, 0, 0, 0, 0, 0, 'default overflow is constrain');
