<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/toLocaleString/dateStyle-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$defaultFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en');
$__destruct__ = $defaultFormatter->resolvedOptions();
$calendar = $__destruct__->calendar;
$yearmonth = new \Calendrics\Spec\PlainYearMonth(2000, 5, $calendar);
$expected = $defaultFormatter->format($yearmonth);
$actual = $yearmonth->toLocaleString('en', (object) []);
Assert::sameValue($actual, $expected, 'dateStyle undefined is the same as being absent');
