<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/toLocaleString/era.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$date = new \Calendrics\Spec\PlainYearMonth(2000, 5, 'gregory');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::startsWith($date->toLocaleString('en', (object) ['era' => 'narrow']), '5'), 'toLocaleString on a PlainYearMonth with era option should work');
