<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/toLocaleString/options-conflict.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$conflictingOptions = [['era', 'short'], ['year', 'numeric'], ['month', 'numeric']];
$calendar = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en')->resolvedOptions()->calendarId;
$ym = new \Calendrics\Spec\PlainYearMonth(2024, 4, $calendar);
$ym->toLocaleString('en', ['dateStyle' => 'short']);
Assert::throws(\TypeError::class, function () use (&$ym) { $ym->toLocaleString('en', ['timeStyle' => 'short']); }, 'timeStyle conflicts with PlainYearMonth');
foreach ($conflictingOptions as $__entry__) {
[$option, $value] = array_pad($__entry__, 2, null);
Assert::throws(\TypeError::class, function () use (&$ym, &$option, &$value) { $ym->toLocaleString('en', JsUndefined::strip([$option => $value, 'dateStyle' => 'short'])); }, "{$option} conflicts with dateStyle");
$ym->toLocaleString('en', JsUndefined::strip([$option => $value]));
$ym->toLocaleString('en', JsUndefined::strip([$option => $value]));
}
