<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/canonicalize-calendar.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$result = new \Calendrics\Spec\ZonedDateTime(1_719_923_640_000_000_000, 'UTC', 'islamicc');
Assert::sameValue($result->calendarId, 'islamic-civil', 'calendar ID is canonicalized');
$result = new \Calendrics\Spec\ZonedDateTime(1_719_923_640_000_000_000, 'UTC', 'ethiopic-amete-alem');
Assert::sameValue($result->calendarId, 'ethioaa', 'calendar ID is canonicalized');
