<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/add/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'reject'], 'options');
$instance = new \Calendrics\Spec\PlainDate(2025, 8, 31);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->add(new \Calendrics\Spec\Duration(0, 1), $options); }, 'overflow reject exception thrown');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
