<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/add/prop-desc.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::sameValue('function', 'function', '`typeof PlainDate.prototype.add` is `function`');
Assert::methodExists('\Calendrics\Spec\PlainDate', 'add');
