<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/since/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expectedOpsForPrimitiveOptions = ['get other.hour', 'get other.hour.valueOf', 'call other.hour.valueOf', 'get other.microsecond', 'get other.microsecond.valueOf', 'call other.microsecond.valueOf', 'get other.millisecond', 'get other.millisecond.valueOf', 'call other.millisecond.valueOf', 'get other.minute', 'get other.minute.valueOf', 'call other.minute.valueOf', 'get other.nanosecond', 'get other.nanosecond.valueOf', 'call other.nanosecond.valueOf', 'get other.second', 'get other.second.valueOf', 'call other.second.valueOf'];
$expected = array_merge($expectedOpsForPrimitiveOptions, ['get options.largestUnit', 'get options.largestUnit.toString', 'call options.largestUnit.toString', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString']);
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$instance = new \Calendrics\Spec\PlainTime(12, 34, 56, 987, 654, 321);
$other = TemporalHelpers::propertyBagObserver($actual, (object) ['hour' => 1.7, 'minute' => 1.7, 'second' => 1.7, 'millisecond' => 1.7, 'microsecond' => 1.7, 'nanosecond' => 1.7, 'calendar' => 'iso8601'], 'other', ['calendar']);
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['roundingIncrement' => 1, 'roundingMode' => 'trunc', 'largestUnit' => 'hours', 'smallestUnit' => 'nanoseconds', 'additional' => true], 'options');
$result = $instance->since($other, $options);
Assert::compareObserverTrace($actual, $expected, 'order of operations');
$actual->clear();
// JS-only (JS rejects non-object options via ToObject; PHP accepts null as "absent"): assert.throws(TypeError, () => instance.since(other, null));
// JS-only (trace covers a call skipped above, so the tracker is empty here): assert.compareArray(actual, expectedOpsForPrimitiveOptions, "other time fields are read before TypeError is thrown for primitive options");
$actual->clear();
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
