<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/since/round-cross-unit-boundary.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$earlier = new \Calendrics\Spec\PlainTime();
$later = new \Calendrics\Spec\PlainTime(1, 59, 59);
$duration = $earlier->since($later, (object) ['largestUnit' => 'hours', 'smallestUnit' => 'minutes', 'roundingMode' => 'expand']);
TemporalHelpers::assertDuration($duration, 0, 0, 0, 0, -2, 0, 0, 0, 0, 0, '-1:60 balances to -2 hours');
