services:
  php:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/app
      - composer-cache:/home/app/.composer/cache
    working_dir: /app
    command: sleep infinity

volumes:
  composer-cache:
