<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/until/float64-representable-integer.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::incomplete('ZonedDateTime fixture requires epoch nanoseconds outside PHP int64 range');
