<?php

declare(strict_types=1);

// Source: tests/Test262/data/Now/plainDateISO/return-value.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$d = \Calendrics\Spec\Now::plainDateISO();
Assert::assertTrue($d instanceof \Calendrics\Spec\PlainDate, '');
Assert::sameValue($d->calendarId, 'iso8601', 'calendar string should be iso8601');
