<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/since/calendar-temporal-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkToTemporalCalendarFastPath(function ($temporalObject) use (&$date) { $date = new \Calendrics\Spec\PlainDate(2000, 5, 2); $date->since(JsUndefined::strip(['year' => 2005, 'month' => 6, 'day' => 2, 'calendar' => $temporalObject])); });
