<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/since/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$createOptionsObserver = function ($__dp0 = []) use (&$actual) {
$smallestUnit = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'smallestUnit') ?? 'days';
$largestUnit = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'largestUnit') ?? 'auto';
$roundingMode = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'roundingMode') ?? 'halfExpand';
$roundingIncrement = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'roundingIncrement') ?? 1;
return TemporalHelpers::propertyBagObserver($actual, JsUndefined::strip(['roundingIncrement' => $roundingIncrement, 'roundingMode' => $roundingMode, 'largestUnit' => $largestUnit, 'smallestUnit' => $smallestUnit, 'additional' => 'property']), 'options');
};
$expectedOpsForPrimitiveOptions = ['get other.calendar', 'get other.day', 'get other.day.valueOf', 'call other.day.valueOf', 'get other.month', 'get other.month.valueOf', 'call other.month.valueOf', 'get other.monthCode', 'get other.monthCode.toString', 'call other.monthCode.toString', 'get other.year', 'get other.year.valueOf', 'call other.year.valueOf'];
$expected = array_merge($expectedOpsForPrimitiveOptions, ['get options.largestUnit', 'get options.largestUnit.toString', 'call options.largestUnit.toString', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString']);
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$instance = new \Calendrics\Spec\PlainDate(2000, 5, 2, 'iso8601');
$otherDatePropertyBag = TemporalHelpers::propertyBagObserver($actual, ['year' => 2001, 'month' => 6, 'monthCode' => 'M06', 'day' => 2, 'calendar' => 'iso8601'], 'other', ['calendar']);
$instance->since($otherDatePropertyBag, $createOptionsObserver(['largestUnit' => 'years']));
Assert::compareObserverTrace($actual, $expected, 'order of operations');
$actual->clear();
// JS-only (JS rejects non-object options via ToObject; PHP accepts null as "absent"): assert.throws(TypeError, () => instance.since(otherDatePropertyBag, null));
// JS-only (trace covers a call skipped above, so the tracker is empty here): assert.compareArray(actual, expectedOpsForPrimitiveOptions, "other date fields are read before TypeError is thrown for primitive options");
$actual->clear();
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
