<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/since/weeks-months.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$date = new \Calendrics\Spec\PlainDate(1969, 7, 24);
$laterDate = new \Calendrics\Spec\PlainDate(1969, 9, 4);
TemporalHelpers::assertDuration($laterDate->since($date, (object) ['largestUnit' => 'weeks']), 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 'weeks');
TemporalHelpers::assertDuration($laterDate->since($date, (object) ['largestUnit' => 'months']), 0, 1, 0, 11, 0, 0, 0, 0, 0, 0, 'months');
