<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/toPlainDateTime/limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$midnight = new \Calendrics\Spec\PlainTime(0, 0);
$firstNs = new \Calendrics\Spec\PlainTime(0, 0, 0, 0, 0, 1);
$lastNs = new \Calendrics\Spec\PlainTime(23, 59, 59, 999, 999, 999);
$min = new \Calendrics\Spec\PlainDate(-271_821, 4, 19);
$max = new \Calendrics\Spec\PlainDate(275_760, 9, 13);
Assert::throws(\RangeException::class, function () use (&$min, &$midnight) { return $min->toPlainDateTime($midnight); }, 'Cannot go below representable limit for PlainDateTime');
TemporalHelpers::assertPlainDateTime($max->toPlainDateTime($midnight), 275_760, 9, 'M09', 13, 0, 0, 0, 0, 0, 0, 'Midnight on maximal representable PlainDate');
TemporalHelpers::assertPlainDateTime($min->toPlainDateTime($firstNs), -271_821, 4, 'M04', 19, 0, 0, 0, 0, 0, 1, 'Computing the minimum (earliest) representable PlainDateTime');
TemporalHelpers::assertPlainDateTime($max->toPlainDateTime($lastNs), 275_760, 9, 'M09', 13, 23, 59, 59, 999, 999, 999, 'Computing the maximum (latest) representable PlainDateTime');
