<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/minute-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$hour = 12;
$explicit = new \Calendrics\Spec\PlainTime($hour);
TemporalHelpers::assertPlainTime($explicit, $hour, 0, 0, 0, 0, 0, 'explicit');
$implicit = new \Calendrics\Spec\PlainTime($hour);
TemporalHelpers::assertPlainTime($implicit, $hour, 0, 0, 0, 0, 0, 'implicit');
