<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/negative-infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
Assert::throws(\RangeException::class, fn() => new \Calendrics\Spec\PlainTime(-INF), '');
Assert::throws(\RangeException::class, fn() => new \Calendrics\Spec\PlainTime(0, -INF), '');
Assert::throws(\RangeException::class, fn() => new \Calendrics\Spec\PlainTime(0, 0, -INF), '');
Assert::throws(\RangeException::class, fn() => new \Calendrics\Spec\PlainTime(0, 0, 0, -INF), '');
Assert::throws(\RangeException::class, fn() => new \Calendrics\Spec\PlainTime(0, 0, 0, 0, -INF), '');
Assert::throws(\RangeException::class, fn() => new \Calendrics\Spec\PlainTime(0, 0, 0, 0, 0, -INF), '');
$O = function ($primitiveValue, $propertyName) use (&$calls) { return function ($calls) use (&$primitiveValue, &$propertyName) { return TemporalHelpers::toPrimitiveObserver($calls, $primitiveValue, $propertyName); }; };
$tests = [['infinite hour', [$O(-INF, 'hour'), $O(1, 'minute'), $O(1, 'second'), $O(1, 'millisecond'), $O(1, 'microsecond'), $O(1, 'nanosecond')], ['get hour.valueOf', 'call hour.valueOf']], ['infinite minute', [$O(1, 'hour'), $O(-INF, 'minute'), $O(1, 'second'), $O(1, 'millisecond'), $O(1, 'microsecond'), $O(1, 'nanosecond')], ['get hour.valueOf', 'call hour.valueOf', 'get minute.valueOf', 'call minute.valueOf']], ['infinite second', [$O(1, 'hour'), $O(1, 'minute'), $O(-INF, 'second'), $O(1, 'millisecond'), $O(1, 'microsecond'), $O(1, 'nanosecond')], ['get hour.valueOf', 'call hour.valueOf', 'get minute.valueOf', 'call minute.valueOf', 'get second.valueOf', 'call second.valueOf']], ['infinite millisecond', [$O(1, 'hour'), $O(1, 'minute'), $O(1, 'second'), $O(-INF, 'millisecond'), $O(1, 'microsecond'), $O(1, 'nanosecond')], ['get hour.valueOf', 'call hour.valueOf', 'get minute.valueOf', 'call minute.valueOf', 'get second.valueOf', 'call second.valueOf', 'get millisecond.valueOf', 'call millisecond.valueOf']], ['infinite microsecond', [$O(1, 'hour'), $O(1, 'minute'), $O(1, 'second'), $O(1, 'millisecond'), $O(-INF, 'microsecond'), $O(1, 'nanosecond')], ['get hour.valueOf', 'call hour.valueOf', 'get minute.valueOf', 'call minute.valueOf', 'get second.valueOf', 'call second.valueOf', 'get millisecond.valueOf', 'call millisecond.valueOf', 'get microsecond.valueOf', 'call microsecond.valueOf']], ['infinite nanosecond', [$O(1, 'hour'), $O(1, 'minute'), $O(1, 'second'), $O(1, 'millisecond'), $O(1, 'microsecond'), $O(-INF, 'nanosecond')], ['get hour.valueOf', 'call hour.valueOf', 'get minute.valueOf', 'call minute.valueOf', 'get second.valueOf', 'call second.valueOf', 'get millisecond.valueOf', 'call millisecond.valueOf', 'get microsecond.valueOf', 'call microsecond.valueOf', 'get nanosecond.valueOf', 'call nanosecond.valueOf']]];
foreach ($tests as $__entry__) {
[$description, $args, $expected] = array_pad($__entry__, 3, null);
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$args_ = array_map(fn($o) => $o($actual), $args);
Assert::throws(\RangeException::class, function () use (&$args_) { return new \Calendrics\Spec\PlainTime(...$args_); }, $description);
Assert::compareObserverTrace($actual, $expected, "{$description} order of operations");
}
