<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/toLocaleString/dateStyle-timeStyle-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$datetime = new \Temporal\Spec\ZonedDateTime(957_270_896_987_650_000, 'UTC');
$defaultFormatter = new \Temporal\Tests\Test262\IntlDateTimeFormat('en', ['year' => 'numeric', 'month' => 'numeric', 'day' => 'numeric', 'hour' => 'numeric', 'minute' => 'numeric', 'second' => 'numeric', 'timeZoneName' => 'short', 'timeZone' => 'UTC']);
$expected = $defaultFormatter->format($datetime->toInstant());
$actualDate = $datetime->toLocaleString('en', []);
Assert::sameValue($actualDate, $expected, 'dateStyle undefined is the same as being absent');
$actualTime = $datetime->toLocaleString('en', []);
Assert::sameValue($actualTime, $expected, 'timeStyle undefined is the same as being absent');
