<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/toLocaleString/era.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$zdt = new \Calendrics\Spec\ZonedDateTime(0, 'UTC');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::startsWith($zdt->toLocaleString('en', (object) ['era' => 'narrow']), '1'), 'toLocaleString on a ZonedDateTime with era option should work');
