<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/toLocaleString/lone-options-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$epochMs = 1_735_213_600_321;
$epochNs = 1_735_213_600_321_000_000;
$legacyDate = new \Temporal\Tests\Test262\JsDate($epochMs);
$zonedDateTime = new \Temporal\Spec\ZonedDateTime($epochNs, 'UTC');
foreach ([(object) ['year' => 'numeric'], (object) ['month' => 'long'], (object) ['day' => 'numeric'], (object) ['weekday' => 'long'], (object) ['hour' => 'numeric'], (object) ['minute' => 'numeric'], (object) ['second' => 'numeric'], (object) ['fractionalSecondDigits' => 3], (object) ['dayPeriod' => 'short'], (object) ['timeZoneName' => 'short']] as $options) {
$zonedDateTimeResult = $zonedDateTime->toLocaleString('en', $options);
$legacyDateResult = $legacyDate->toLocaleString('en', (object) JsUndefined::strip(array_merge((array) $options, ['timeZone' => 'UTC'])));
Assert::sameValue($zonedDateTimeResult, $legacyDateResult, "ZonedDateTime.toLocaleString should format lone option " . (json_encode($options)) . "");
}
