<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/toLocaleString/offset-time-zones.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$zdt = new \Calendrics\Spec\ZonedDateTime(0, '+00:00');
$result = $zdt->toLocaleString('en');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, 'GMT') && !\Calendrics\Tests\Test262\Js::includes($result, '+') && !\Calendrics\Tests\Test262\Js::includes($result, '-'), '');
$zdt = new \Calendrics\Spec\ZonedDateTime(0, '+01:00');
$result = $zdt->toLocaleString('en');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, 'GMT+1'), '');
$zdt = new \Calendrics\Spec\ZonedDateTime(0, '-01:00');
$result = $zdt->toLocaleString('en');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, 'GMT-1'), '');
