<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/since/argument-zoneddatetime-negative-epochnanoseconds.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$datetime = new \Calendrics\Spec\ZonedDateTime(-13_849_764_999_999_999, 'UTC');
$instance = new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 15, 30, 45, 987, 654, 321);
$result = $instance->since($datetime);
TemporalHelpers::assertDuration($result, 0, 0, 0, 11_239, 22, 40, 10, 987, 654, 320);
