<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/from/japanese-month-codes.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$calendar = 'japanese';
foreach (TemporalHelpers::isoMonths() as $__obj__) {
$month = $__obj__['month'] ?? null;
$monthCode = $__obj__['monthCode'] ?? null;
$daysInMonth = $__obj__['daysInMonth'] ?? null;
$pmd = \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 1]));
TemporalHelpers::assertPlainMonthDay($pmd, $monthCode, 1, "monthCode {$monthCode} should be preserved");
$pmdMonth = \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['calendar' => $calendar, 'year' => 1972, 'month' => $month, 'day' => 1]));
TemporalHelpers::assertPlainMonthDay($pmdMonth, $monthCode, 1, "Equivalent monthCode {$monthCode} and month {$month} are resolved to the same PlainMonthDay");
$pmdMax = \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => $daysInMonth]));
TemporalHelpers::assertPlainMonthDay($pmdMax, $monthCode, $daysInMonth, "{$monthCode} with day {$daysInMonth} should be valid");
$constrained = \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => $daysInMonth + 1]), (object) ['overflow' => 'constrain']);
TemporalHelpers::assertPlainMonthDay($constrained, $monthCode, $daysInMonth, "day " . ($daysInMonth + 1) . " should be constrained to {$daysInMonth} for {$monthCode}");
Assert::throws(\RangeException::class, function () use (&$calendar, &$monthCode, &$daysInMonth) { \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => $daysInMonth + 1]), (object) ['overflow' => 'reject']); }, "{$monthCode} with day " . ($daysInMonth + 1) . " should throw with reject overflow");
}
