<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/with/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$zdt = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789)->toZonedDateTime('UTC');
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['year' => 2019]), \Calendrics\Spec\ZonedDateTime::from('2019-11-18T15:23:30.123456789+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['month' => 5]), \Calendrics\Spec\ZonedDateTime::from('1976-05-18T15:23:30.123456789+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['monthCode' => 'M05']), \Calendrics\Spec\ZonedDateTime::from('1976-05-18T15:23:30.123456789+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['day' => 5]), \Calendrics\Spec\ZonedDateTime::from('1976-11-05T15:23:30.123456789+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['hour' => 5]), \Calendrics\Spec\ZonedDateTime::from('1976-11-18T05:23:30.123456789+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['minute' => 5]), \Calendrics\Spec\ZonedDateTime::from('1976-11-18T15:05:30.123456789+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['second' => 5]), \Calendrics\Spec\ZonedDateTime::from('1976-11-18T15:23:05.123456789+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['millisecond' => 5]), \Calendrics\Spec\ZonedDateTime::from('1976-11-18T15:23:30.005456789+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['microsecond' => 5]), \Calendrics\Spec\ZonedDateTime::from('1976-11-18T15:23:30.123005789+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['nanosecond' => 5]), \Calendrics\Spec\ZonedDateTime::from('1976-11-18T15:23:30.123456005+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->with((object) ['month' => 5, 'second' => 15]), \Calendrics\Spec\ZonedDateTime::from('1976-05-18T15:23:15.123456789+00:00[UTC]'));
