<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/with/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get options.disambiguation', 'get options.disambiguation.toString', 'call options.disambiguation.toString', 'get options.offset', 'get options.offset.toString', 'call options.offset.toString', 'get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = new \Temporal\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['overflow' => 'constrain', 'offset' => 'prefer', 'disambiguation' => 'compatible'], 'options');
$instance = new \Temporal\Spec\ZonedDateTime(0, 'UTC');
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->with((object) ['monthCode' => 'M08L'], $options); }, 'exception thrown when month code incorrect for calendar');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
