<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/with/overflow-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$datetime = new \Calendrics\Spec\ZonedDateTime(1_000_000_000_987_654_321, 'UTC');
$explicit = $datetime->with((object) ['second' => 67], (object) []);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($explicit), 1_000_000_019_987_654_321, 'default overflow is constrain');
$implicit = $datetime->with((object) ['second' => 67], (object) []);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($implicit), 1_000_000_019_987_654_321, 'default overflow is constrain');
$lambda = $datetime->with((object) ['second' => 67], function () {  });
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($lambda), 1_000_000_019_987_654_321, 'default overflow is constrain');
