<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/add/leap-month-dangi-numerical-months.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = \Calendrics\Spec\PlainDate::from(['calendar' => 'dangi', 'year' => 2012, 'month' => 4, 'day' => 1]);
Assert::throws(\RangeException::class, function () use (&$instance) { return $instance->add('P1Y1M', ['overflow' => 'reject']); }, 'Adding a year and a month to a numerical (leap) month.');
$oneYear = new \Calendrics\Spec\Duration(1);
Assert::throws(\RangeException::class, function () use (&$instance, &$oneYear) { return $instance->add($oneYear, ['overflow' => 'reject']); }, 'Adding a year to a numerical (leap) month.');
