<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Duration/prototype/round/relativeto-infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$instance = new \Calendrics\Spec\Duration(1, 2, 3, 4, 5, 6, 7, 987, 654, 321);
$base = ['era' => 'ad', 'month' => 5, 'day' => 2, 'hour' => 15, 'calendar' => 'gregory'];
foreach ([INF, -INF] as $inf) {
Assert::throws(\RangeException::class, function () use (&$instance, &$base, &$inf) { return $instance->round(JsUndefined::strip(['smallestUnit' => 'seconds', 'relativeTo' => JsUndefined::strip(array_merge($base, ['eraYear' => $inf]))])); }, "eraYear property cannot be {$inf} in relativeTo");
$calls = new \Calendrics\Tests\Test262\ObserverTrace();
$obj = TemporalHelpers::toPrimitiveObserver($calls, $inf, 'eraYear');
Assert::throws(\RangeException::class, function () use (&$instance, &$base, &$obj) { return $instance->round(JsUndefined::strip(['smallestUnit' => 'seconds', 'relativeTo' => JsUndefined::strip(array_merge($base, ['eraYear' => $obj]))])); }, '');
Assert::compareObserverTrace($calls, ['get eraYear.valueOf', 'call eraYear.valueOf'], 'it fails after fetching the primitive value');
}
