<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/subtract/argument-duration-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$jun13 = \Calendrics\Spec\PlainYearMonth::from('2013-06');
$diff = \Calendrics\Spec\Duration::from('P18Y7M');
TemporalHelpers::assertPlainYearMonth($jun13->subtract($diff), 1994, 11, 'M11');
