<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/subtract/limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$min = \Calendrics\Spec\PlainYearMonth::from('-271821-04');
foreach (['reject', 'constrain'] as $overflow) {
Assert::throws(\RangeException::class, function () use (&$min, &$overflow) { return $min->subtract(['months' => 1], JsUndefined::strip(['overflow' => $overflow])); }, $overflow);
}
