<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/subtract/overflow-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$yearmonth = new \Calendrics\Spec\PlainYearMonth(2000, 5);
$duration = new \Calendrics\Spec\Duration(1, 1);
Assert::throws(\RangeException::class, function () use (&$yearmonth, &$duration) { return $yearmonth->subtract($duration, ['overflow' => null]); }, 'null');
Assert::throws(\RangeException::class, function () use (&$yearmonth, &$duration) { return $yearmonth->subtract($duration, ['overflow' => true]); }, 'true');
Assert::throws(\RangeException::class, function () use (&$yearmonth, &$duration) { return $yearmonth->subtract($duration, ['overflow' => false]); }, 'false');
Assert::throws(\TypeError::class, function () use (&$yearmonth, &$duration) { return $yearmonth->subtract($duration, JsUndefined::strip(['overflow' => \Calendrics\Tests\Test262\JsSymbol::singleton()])); }, 'symbol');
Assert::throws(\RangeException::class, function () use (&$yearmonth, &$duration) { return $yearmonth->subtract($duration, ['overflow' => 2]); }, 'number');
Assert::throws(\RangeException::class, function () use (&$yearmonth, &$duration) { return $yearmonth->subtract($duration, ['overflow' => 2]); }, 'bigint');
Assert::throws(\RangeException::class, function () use (&$yearmonth, &$duration) { return $yearmonth->subtract($duration, JsUndefined::strip(['overflow' => []])); }, 'plain object');
$expected = ['get overflow.toString', 'call overflow.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$observer = TemporalHelpers::toPrimitiveObserver($actual, 'constrain', 'overflow');
$result = $yearmonth->subtract($duration, JsUndefined::strip(['overflow' => $observer]));
TemporalHelpers::assertPlainYearMonth($result, 1999, 4, 'M04', 'object with toString');
Assert::compareObserverTrace($actual, $expected, 'order of operations');
