<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/toZonedDateTime/throws-if-combined-date-time-outside-valid-iso-range.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$minDate = new \Calendrics\Spec\PlainDate(-271_821, 4, 19);
$midnight = new \Calendrics\Spec\PlainTime();
$item = (object) JsUndefined::strip(['timeZone' => '+00', 'plainTime' => $midnight]);
Assert::throws(\RangeException::class, function () use (&$minDate, &$item) { return $minDate->toZonedDateTime($item); }, '');
