<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DurationFormat/prototype/format/taint-temporal-duration-prototype.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$duration = new \Calendrics\Spec\Duration(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
Assert::incomplete('untranslatable: Intl.DurationFormat has no harness shim');
