<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DurationFormat/prototype/format/temporal-duration-string-arg.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$durations = [JsUndefined::strip(['string' => 'PT0S', 'durationLike' => ['years' => 0]]), JsUndefined::strip(['string' => 'P1Y2M3W4DT5H6M7.00800901S', 'durationLike' => ['years' => 1, 'months' => 2, 'weeks' => 3, 'days' => 4, 'hours' => 5, 'minutes' => 6, 'seconds' => 7, 'milliseconds' => 8, 'microseconds' => 9, 'nanoseconds' => 10]])];
Assert::incomplete('untranslatable: Intl.DurationFormat has no harness shim');
