<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/toPlainYearMonth/limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$min = \Calendrics\Spec\PlainDate::from('-271821-04-19');
TemporalHelpers::assertPlainYearMonth($min->toPlainYearMonth(), -271_821, 4, 'M04', 'min');
$max = \Calendrics\Spec\PlainDate::from('+275760-09-13');
TemporalHelpers::assertPlainYearMonth($max->toPlainYearMonth(), 275_760, 9, 'M09', 'max');
