<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/equals/canonicalize-iana-identifiers-before-comparing.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$calcutta = \Calendrics\Spec\ZonedDateTime::from('2020-01-01T00:00:00+05:30[Asia/Calcutta]');
$kolkata = \Calendrics\Spec\ZonedDateTime::from('2020-01-01T00:00:00+05:30[Asia/Kolkata]');
$colombo = \Calendrics\Spec\ZonedDateTime::from('2020-01-01T00:00:00+05:30[Asia/Colombo]');
Assert::sameValue($calcutta->equals($kolkata), true, '');
Assert::sameValue($calcutta->equals((string) ($kolkata)), true, '');
Assert::sameValue($kolkata->equals($calcutta), true, '');
Assert::sameValue($kolkata->equals((string) ($calcutta)), true, '');
Assert::sameValue($calcutta->equals($colombo), false, '');
