<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/compare/argument-propertybag-optional-properties.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$minimumProperties = (object) ['hour' => 0];
$allProperties = (object) ['hour' => 0, 'minute' => 0, 'second' => 0, 'millisecond' => 0, 'microsecond' => 0, 'nanosecond' => 0];
$resultWithout = \Calendrics\Spec\PlainTime::compare($minimumProperties, $minimumProperties);
$resultWith = \Calendrics\Spec\PlainTime::compare($allProperties, $allProperties);
Assert::sameValue($resultWithout, $resultWith, 'results should be the same with and without optional properties');
