<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/compare/argument-string-too-many-decimals.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$invalidStrings = ['1970-01-01T00:00:00.1234567891', '1970-01-01T00:00:00.1234567890', '1970-01-01T00+00:00:00.1234567891', '1970-01-01T00+00:00:00.1234567890', '00:00:00.1234567891', '00:00:00.1234567890', '00+00:00:00.1234567891', '00+00:00:00.1234567890'];
foreach ($invalidStrings as $arg) {
Assert::throws(\RangeException::class, function () use (&$arg) { \Calendrics\Spec\PlainTime::compare($arg, new \Calendrics\Spec\PlainTime(12, 34, 56, 987, 654, 321)); }, 'no more than 9 decimal places are allowed (first arg)');
Assert::throws(\RangeException::class, function () use (&$arg) { \Calendrics\Spec\PlainTime::compare(new \Calendrics\Spec\PlainTime(12, 34, 56, 987, 654, 321), $arg); }, 'no more than 9 decimal places are allowed (second arg)');
}
