<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/compare/argument-string-no-implicit-midnight.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$arg = '2019-10-01';
$midnight = new \Calendrics\Spec\PlainTime();
Assert::throws(\RangeException::class, function () use (&$arg, &$midnight) { return \Calendrics\Spec\PlainTime::compare($arg, $midnight); }, 'Date-only string throws, does not implicitly convert to midnight (first argument)');
Assert::throws(\RangeException::class, function () use (&$midnight, &$arg) { return \Calendrics\Spec\PlainTime::compare($midnight, $arg); }, 'Date-only string throws, does not implicitly convert to midnight (second argument)');
