<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/compare/argument-zoneddatetime-negative-epochnanoseconds.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$datetime = new \Calendrics\Spec\ZonedDateTime(-13_849_764_999_999_999, 'UTC');
$time = new \Calendrics\Spec\PlainTime(16, 50, 35, 0, 0, 1);
$result1 = \Calendrics\Spec\PlainTime::compare($time, $datetime);
Assert::sameValue($result1, 0, '');
$result2 = \Calendrics\Spec\PlainTime::compare($datetime, $time);
Assert::sameValue($result2, 0, '');
