<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/compare/plaintime-propertybag-no-time-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$props = (object) [];
Assert::throws(\TypeError::class, function () use (&$props) { return \Calendrics\Spec\PlainTime::compare($props, new \Calendrics\Spec\PlainTime(0, 30)); }, 'TypeError if no properties are present');
$props->minute = 30;
$result = \Calendrics\Spec\PlainTime::compare($props, new \Calendrics\Spec\PlainTime(0, 30));
Assert::sameValue($result, 0, 'missing time units default to 0');
