<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/equals/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$t1 = \Calendrics\Spec\PlainTime::from('08:44:15.321');
$t1bis = \Calendrics\Spec\PlainTime::from('08:44:15.321');
$t2 = \Calendrics\Spec\PlainTime::from('14:23:30.123');
Assert::sameValue($t1->equals($t1), true, 'same object');
Assert::sameValue($t1->equals($t1bis), true, 'different object');
Assert::sameValue($t1->equals($t2), false, 'different times');
