<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/days/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$blank = new \Calendrics\Spec\Duration();
Assert::sameValue($blank->days, 0, '');
