<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/constructor-options-fractionalSecondDigits-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$invalidOptions = ['LONG', ' long', 'short ', 'full', 'numeric', -1, 4, '4', '-1', -0.00_001, 3.000_001];
foreach ($invalidOptions as $fractionalSecondDigits) {
Assert::throws(\RangeException::class, function () use (&$fractionalSecondDigits) { new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', JsUndefined::strip(['fractionalSecondDigits' => $fractionalSecondDigits])); }, "new Intl.DateTimeFormat(\"en\", { fractionalSecondDigits: \"{$fractionalSecondDigits}\" }) throws RangeError");
}
