<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/subtract/minimum-maximum-instant.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$min = \Calendrics\Spec\Instant::fromEpochParts(-8640000000000, 0);
$max = \Calendrics\Spec\Instant::fromEpochParts(8640000000000, 0);
$zero = \Calendrics\Spec\Duration::from(['nanoseconds' => 0]);
$one = \Calendrics\Spec\Duration::from(['nanoseconds' => 1]);
$minusOne = \Calendrics\Spec\Duration::from(JsUndefined::strip(['nanoseconds' => -1]));
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->subtract($zero)), \Calendrics\Tests\Test262\JsEpoch::read($min), '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->subtract($zero)), \Calendrics\Tests\Test262\JsEpoch::read($max), '');
Assert::throws(\RangeException::class, function () use (&$min, &$one) { return $min->subtract($one); }, '');
Assert::throws(\RangeException::class, function () use (&$max, &$minusOne) { return $max->subtract($minusOne); }, '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->subtract($minusOne)), \Calendrics\Tests\Test262\JsEpoch::read($min) + 1, '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->subtract($one)), \Calendrics\Tests\Test262\JsEpoch::read($max) - 1, '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->subtract(JsUndefined::strip(['nanoseconds' => -8.64e+21 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($max), '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->subtract(JsUndefined::strip(['microseconds' => -8_640_000_000_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($max), '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->subtract(JsUndefined::strip(['milliseconds' => -8_640_000_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($max), '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->subtract(JsUndefined::strip(['seconds' => -8_640_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($max), '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->subtract(JsUndefined::strip(['nanoseconds' => 8.64e+21 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($min), '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->subtract(JsUndefined::strip(['microseconds' => 8_640_000_000_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($min), '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->subtract(JsUndefined::strip(['milliseconds' => 8_640_000_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($min), '');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->subtract(JsUndefined::strip(['seconds' => 8_640_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($min), '');
