<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DurationFormat/prototype/formatToParts/taint-temporal-duration-prototype.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$assertSameParts = function ($actual, $expected) {
Assert::sameValue((is_string($actual) ? strlen($actual) : count($actual)), (is_string($expected) ? strlen($expected) : count($expected)), '');
for ($i = 0; $i < (is_string($actual) ? strlen($actual) : count($actual)); ++$i) {
Assert::sameValue($actual[$i]->type, $expected[$i]->type, '');
Assert::sameValue($actual[$i]->value, $expected[$i]->value, '');
Assert::sameValue($actual[$i]->unit, $expected[$i]->unit, '');
}
};
$duration = new \Calendrics\Spec\Duration(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
Assert::incomplete('untranslatable: Intl.DurationFormat has no harness shim');
