<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DurationFormat/prototype/formatToParts/temporal-duration-string-arg.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$assertSameParts = function ($actual, $expected) {
Assert::sameValue((is_string($actual) ? strlen($actual) : count($actual)), (is_string($expected) ? strlen($expected) : count($expected)), '');
for ($i = 0; $i < (is_string($actual) ? strlen($actual) : count($actual)); ++$i) {
Assert::sameValue($actual[$i]->type, $expected[$i]->type, '');
Assert::sameValue($actual[$i]->value, $expected[$i]->value, '');
Assert::sameValue($actual[$i]->unit, $expected[$i]->unit, '');
}
};
$durations = [(object) JsUndefined::strip(['string' => 'PT0S', 'durationLike' => (object) ['years' => 0]]), (object) JsUndefined::strip(['string' => 'P1Y2M3W4DT5H6M7.00800901S', 'durationLike' => (object) ['years' => 1, 'months' => 2, 'weeks' => 3, 'days' => 4, 'hours' => 5, 'minutes' => 6, 'seconds' => 7, 'milliseconds' => 8, 'microseconds' => 9, 'nanoseconds' => 10]])];
Assert::incomplete('untranslatable: Intl.DurationFormat has no harness shim');
