<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/toInstant/recent-date.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$zdt = \Calendrics\Spec\ZonedDateTime::from('2019-10-29T10:46:38.271986102+01:00[+01:00]');
TemporalHelpers::assertInstantsEqual($zdt->toInstant(), \Calendrics\Spec\Instant::from('2019-10-29T09:46:38.271986102Z'));
