<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/toInstant/year-less-than-1.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$zdt = \Calendrics\Spec\ZonedDateTime::from('0000-10-29T10:46:38.271986102+00:00[UTC]');
TemporalHelpers::assertInstantsEqual($zdt->toInstant(), \Calendrics\Spec\Instant::from('0000-10-29T10:46:38.271986102Z'));
$zdt = \Calendrics\Spec\ZonedDateTime::from('+000000-10-29T10:46:38.271986102+00:00[UTC]');
TemporalHelpers::assertInstantsEqual($zdt->toInstant(), \Calendrics\Spec\Instant::from('0000-10-29T10:46:38.271986102Z'));
$zdt = \Calendrics\Spec\ZonedDateTime::from('-001000-10-29T10:46:38.271986102+00:00[UTC]');
TemporalHelpers::assertInstantsEqual($zdt->toInstant(), \Calendrics\Spec\Instant::from('-001000-10-29T10:46:38.271986102Z'));
