<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/argument-cast.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::sameValue(\Calendrics\Spec\Duration::compare('PT12H', new \Calendrics\Spec\Duration()), 1, 'first argument string');
Assert::sameValue(\Calendrics\Spec\Duration::compare(['hours' => 12], new \Calendrics\Spec\Duration()), 1, 'first argument object');
Assert::throws(\TypeError::class, fn() => \Calendrics\Spec\Duration::compare(['hour' => 12], new \Calendrics\Spec\Duration()), 'first argument missing property');
Assert::sameValue(\Calendrics\Spec\Duration::compare(new \Calendrics\Spec\Duration(), 'PT12H'), -1, 'second argument string');
Assert::sameValue(\Calendrics\Spec\Duration::compare(new \Calendrics\Spec\Duration(), ['hours' => 12]), -1, 'second argument object');
Assert::throws(\TypeError::class, fn() => \Calendrics\Spec\Duration::compare(new \Calendrics\Spec\Duration(), ['hour' => 12]), 'second argument missing property');
Assert::sameValue(\Calendrics\Spec\Duration::compare(['hours' => 12, 'minute' => 5], ['hours' => 12, 'day' => 5]), 0, 'ignores incorrect properties');
