<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$blank1 = new \Calendrics\Spec\Duration();
$blank2 = new \Calendrics\Spec\Duration();
$compare = [\Calendrics\Spec\Duration::class, 'compare'];
$plainRelativeTo = new \Calendrics\Spec\PlainDate(2025, 8, 22);
$zonedRelativeTo = new \Calendrics\Spec\ZonedDateTime(1, 'UTC');
Assert::sameValue($compare($blank1, $blank2), 0, 'zero durations compared without relativeTo');
Assert::sameValue($compare($blank1, $blank2, (object) JsUndefined::strip(['relativeTo' => $plainRelativeTo])), 0, 'zero durations compared with PlainDate relativeTo');
Assert::sameValue($compare($blank1, $blank2, (object) JsUndefined::strip(['relativeTo' => $zonedRelativeTo])), 0, 'zero durations compared with ZonedDateTime relativeTo');
