<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/relativeto-argument-string-calendar-invalid-iso-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance_1 = new \Calendrics\Spec\Duration(1);
$instance_2 = new \Calendrics\Spec\Duration(2);
$invalidStrings = [['', 'empty string'], ['1997-12-04[u-ca=notacal]', 'Unknown calendar'], ['1997-12-04[u-ca=11111111]', 'compact ISO date used as calendar name'], ['1997-12-04[u-ca=1111-11-11]', 'extended ISO date used as calendar name']];
foreach ($invalidStrings as $__entry__) {
[$arg, $description] = array_pad($__entry__, 2, null);
Assert::throws(\RangeException::class, function () use (&$instance_1, &$instance_2, &$arg) { return \Calendrics\Spec\Duration::compare($instance_1, $instance_2, (object) JsUndefined::strip(['relativeTo' => $arg])); }, "{$description} is not a valid calendar ID");
}
