<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/relativeto-hour.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$oneDay = new \Calendrics\Spec\Duration(0, 0, 0, 1);
$hours24 = new \Calendrics\Spec\Duration(0, 0, 0, 0, 24);
Assert::sameValue(\Calendrics\Spec\Duration::compare($oneDay, $hours24), 0, 'relativeTo not required for days');
Assert::sameValue(\Calendrics\Spec\Duration::compare($oneDay, $hours24, (object) JsUndefined::strip(['relativeTo' => \Calendrics\Spec\PlainDate::from('2017-01-01')])), 0, 'relativeTo does not affect days if PlainDate');
Assert::sameValue(\Calendrics\Spec\Duration::compare($oneDay, $hours24, (object) ['relativeTo' => '2019-11-03']), 0, 'casts relativeTo to PlainDate from string');
Assert::sameValue(\Calendrics\Spec\Duration::compare($oneDay, $hours24, (object) JsUndefined::strip(['relativeTo' => (object) ['year' => 2019, 'month' => 11, 'day' => 3]])), 0, 'casts relativeTo to PlainDate from object');
