<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/relativeto-month.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$oneMonth = new \Calendrics\Spec\Duration(0, 1);
$days30 = new \Calendrics\Spec\Duration(0, 0, 0, 30);
Assert::sameValue(\Calendrics\Spec\Duration::compare($oneMonth, $days30, JsUndefined::strip(['relativeTo' => \Calendrics\Spec\PlainDate::from('2018-04-01')])), 0, '');
Assert::sameValue(\Calendrics\Spec\Duration::compare($oneMonth, $days30, JsUndefined::strip(['relativeTo' => \Calendrics\Spec\PlainDate::from('2018-03-01')])), 1, '');
Assert::sameValue(\Calendrics\Spec\Duration::compare($oneMonth, $days30, JsUndefined::strip(['relativeTo' => \Calendrics\Spec\PlainDate::from('2018-02-01')])), -1, '');
