<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/relativeto-argument-propertybag-calendar-invalid-iso-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance_1 = new \Calendrics\Spec\Duration(1);
$instance_2 = new \Calendrics\Spec\Duration(2);
$invalidStrings = [['', 'empty string'], ['notacal', 'Unknown calendar']];
foreach ($invalidStrings as $__entry__) {
[$cal, $description] = array_pad($__entry__, 2, null);
$arg = JsUndefined::strip(['year' => 2019, 'monthCode' => 'M11', 'day' => 1, 'calendar' => $cal]);
Assert::throws(\RangeException::class, function () use (&$instance_1, &$instance_2, &$arg) { return \Calendrics\Spec\Duration::compare($instance_1, $instance_2, JsUndefined::strip(['relativeTo' => $arg])); }, "{$description} is not a valid calendar ID");
}
