<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/relativeto-propertybag-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$oneDay = new \Calendrics\Spec\Duration(0, 0, 0, 1);
$hours24 = new \Calendrics\Spec\Duration(0, 0, 0, 0, 24);
Assert::throws(\TypeError::class, function () use (&$oneDay, &$hours24) { return \Calendrics\Spec\Duration::compare($oneDay, $hours24, (object) JsUndefined::strip(['relativeTo' => (object) ['month' => 11, 'day' => 3]])); }, 'missing year');
Assert::throws(\TypeError::class, function () use (&$oneDay, &$hours24) { return \Calendrics\Spec\Duration::compare($oneDay, $hours24, (object) JsUndefined::strip(['relativeTo' => (object) ['year' => 2019, 'month' => 11]])); }, 'missing day');
Assert::throws(\TypeError::class, function () use (&$oneDay, &$hours24) { return \Calendrics\Spec\Duration::compare($oneDay, $hours24, (object) JsUndefined::strip(['relativeTo' => (object) ['year' => 2019, 'day' => 3]])); }, 'missing month');
