<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/relativeto-undefined-throw-on-calendar-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$oneYear = new \Calendrics\Spec\Duration(1);
$oneMonth = new \Calendrics\Spec\Duration(0, 1);
$oneWeek = new \Calendrics\Spec\Duration(0, 0, 1);
$oneDay = new \Calendrics\Spec\Duration(0, 0, 0, 1);
$twoDays = new \Calendrics\Spec\Duration(0, 0, 0, 2);
Assert::sameValue(\Calendrics\Spec\Duration::compare($oneDay, $twoDays), -1, 'days do not require relativeTo');
Assert::throws(\RangeException::class, function () use (&$oneWeek, &$oneDay) { return \Calendrics\Spec\Duration::compare($oneWeek, $oneDay); }, 'weeks in left operand require relativeTo');
Assert::throws(\RangeException::class, function () use (&$oneDay, &$oneWeek) { return \Calendrics\Spec\Duration::compare($oneDay, $oneWeek); }, 'weeks in right operand require relativeTo');
Assert::throws(\RangeException::class, function () use (&$oneMonth, &$oneDay) { return \Calendrics\Spec\Duration::compare($oneMonth, $oneDay); }, 'months in left operand require relativeTo');
Assert::throws(\RangeException::class, function () use (&$oneDay, &$oneMonth) { return \Calendrics\Spec\Duration::compare($oneDay, $oneMonth); }, 'months in right operand require relativeTo');
Assert::throws(\RangeException::class, function () use (&$oneYear, &$oneDay) { return \Calendrics\Spec\Duration::compare($oneYear, $oneDay); }, 'years in left operand require relativeTo');
Assert::throws(\RangeException::class, function () use (&$oneDay, &$oneYear) { return \Calendrics\Spec\Duration::compare($oneDay, $oneYear); }, 'years in right operand require relativeTo');
