<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDateTime/prototype/toZonedDateTime/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.disambiguation', 'get options.disambiguation.toString', 'call options.disambiguation.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$instance = new \Calendrics\Spec\PlainDateTime(2000, 4, 2, 2, 30);
$options = TemporalHelpers::propertyBagObserver($actual, ['disambiguation' => 'reject'], 'options');
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { return $instance->toZonedDateTime('America/Vancouver', $options); }, '');
Assert::compareObserverTrace($actual, $expected, 'order of operations with disambiguation: reject');
$actual->clear();
