<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/subtract/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$dt = new \Calendrics\Spec\ZonedDateTime(1, 'UTC');
$blank = new \Calendrics\Spec\Duration();
$result = $dt->subtract($blank);
Assert::sameValue($result->epochNanoseconds, 1, 'result is unchanged');
