<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/subtract/negative-epochnanoseconds.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$datetime = new \Calendrics\Spec\ZonedDateTime(-13_849_764_999_999_999, 'UTC');
$result = $datetime->subtract(new \Calendrics\Spec\Duration(0, 0, 0, 1));
Assert::sameValue($result->epochNanoseconds, -13_936_164_999_999_999, '');
