<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/subtract/overflow-subtracting-months-from-min-year.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$minYear = \Calendrics\Spec\ZonedDateTime::fromEpochParts(-8640000000000, 0, 'UTC');
$duration = new \Calendrics\Spec\Duration(0, 5432, 5432, 0, 0, 0, 0, 0, 0, 0);
Assert::throws(\RangeException::class, function () use (&$minYear, &$duration) { return $minYear->subtract($duration); }, '');
$maxYear = new \Calendrics\Spec\PlainDateTime(275_760, 1, 1)->toZonedDateTime('UTC');
Assert::throws(\RangeException::class, function () use (&$maxYear, &$duration) { return $maxYear->subtract($duration->negated()); }, '');
