<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/subtract/overflow.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$later = new \Calendrics\Spec\ZonedDateTime(1_572_356_798_271_986_102, '-03:00');
$earlier = $later->subtract((object) ['hours' => 12]);
TemporalHelpers::assertZonedDateTimesEqual($earlier, new \Calendrics\Spec\ZonedDateTime(1_572_313_598_271_986_102, '-03:00'));
$earlier = new \Calendrics\Spec\ZonedDateTime(1_590_981_158_271_986_102, '-04:00');
$later = new \Calendrics\Spec\ZonedDateTime(1_590_988_358_271_986_102, '-04:00');
TemporalHelpers::assertZonedDateTimesEqual($earlier->subtract((object) JsUndefined::strip(['hours' => -2])), $later);
