<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/subtract/overflow-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$datetime = new \Calendrics\Spec\ZonedDateTime(-1, 'UTC');
$duration = new \Calendrics\Spec\Duration(0, 1);
$explicit = $datetime->subtract($duration, (object) []);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($explicit), -2_678_400_000_000_001, 'default overflow is constrain');
$implicit = $datetime->subtract($duration, (object) []);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($implicit), -2_678_400_000_000_001, 'default overflow is constrain');
$lambda = $datetime->subtract($duration, function () {  });
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($lambda), -2_678_400_000_000_001, 'default overflow is constrain');
