<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/subtract/symmetrical-wrt-negative-durations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$mar31 = \Calendrics\Spec\ZonedDateTime::from('2020-03-31T15:00+00:00[UTC]');
TemporalHelpers::assertZonedDateTimesEqual($mar31->subtract((object) JsUndefined::strip(['minutes' => -30])), \Calendrics\Spec\ZonedDateTime::from('2020-03-31T15:30:00+00:00[UTC]'));
TemporalHelpers::assertZonedDateTimesEqual($mar31->subtract((object) JsUndefined::strip(['seconds' => -30])), \Calendrics\Spec\ZonedDateTime::from('2020-03-31T15:00:30+00:00[UTC]'));
