<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/weekOfYear/non-iso-week-of-year.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$nonIsoCalendars = ['buddhist', 'chinese', 'coptic', 'dangi', 'ethioaa', 'ethiopic', 'gregory', 'hebrew', 'indian', 'islamic-civil', 'islamic-tbla', 'islamic-umalqura', 'japanese', 'persian', 'roc'];
foreach ($nonIsoCalendars as $calendar) {
Assert::sameValue(new \Calendrics\Spec\PlainDate(2024, 1, 1, $calendar)->weekOfYear, null, "{$calendar} does not provide week numbers");
}
