<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/compare/argument-propertybag-calendar-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$wrongTypeTests = [[null, 'null'], [true, 'boolean'], [1, 'number'], [1, 'bigint'], [19_970_327, 'large number'], [-19_970_327, 'negative number'], [1_234_567_890, 'very large integer'], [\Calendrics\Tests\Test262\JsSymbol::singleton(), 'symbol'], [[], 'object'], [new \Calendrics\Spec\Duration(), 'duration instance']];
foreach ($wrongTypeTests as $__entry__) {
[$calendar, $description] = array_pad($__entry__, 2, null);
if ($calendar === null) { continue; }
$arg = JsUndefined::strip(['year' => 2019, 'monthCode' => 'M06', 'calendar' => $calendar]);
Assert::throws(\TypeError::class, function () use (&$arg) { return \Calendrics\Spec\PlainYearMonth::compare($arg, new \Calendrics\Spec\PlainYearMonth(2019, 6)); }, "{$description} is not a valid calendar (first argument)");
Assert::throws(\TypeError::class, function () use (&$arg) { return \Calendrics\Spec\PlainYearMonth::compare(new \Calendrics\Spec\PlainYearMonth(2019, 6), $arg); }, "{$description} is not a valid calendar (second argument)");
}
