<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/compare/argument-propertybag-calendar-leap-second.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$calendar = '2016-12-31T23:59:60';
$arg = (object) JsUndefined::strip(['year' => 2019, 'monthCode' => 'M06', 'calendar' => $calendar]);
$result1 = \Calendrics\Spec\PlainYearMonth::compare($arg, new \Calendrics\Spec\PlainYearMonth(2019, 6));
Assert::sameValue($result1, 0, 'leap second is a valid ISO string for calendar (first argument)');
$result2 = \Calendrics\Spec\PlainYearMonth::compare(new \Calendrics\Spec\PlainYearMonth(2019, 6), $arg);
Assert::sameValue($result2, 0, 'leap second is a valid ISO string for calendar (second argument)');
