<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/compare/argument-string-with-utc-designator.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$invalidStrings = ['2019-10-01T09:00:00Z', '2019-10-01T09:00:00Z[UTC]'];
$yearMonth = new \Calendrics\Spec\PlainYearMonth(2000, 5);
foreach ($invalidStrings as $arg) {
Assert::throws(\RangeException::class, function () use (&$arg, &$yearMonth) { return \Calendrics\Spec\PlainYearMonth::compare($arg, $yearMonth); }, 'String with UTC designator should not be valid as a PlainYearMonth (first argument)');
Assert::throws(\RangeException::class, function () use (&$yearMonth, &$arg) { return \Calendrics\Spec\PlainYearMonth::compare($yearMonth, $arg); }, 'String with UTC designator should not be valid as a PlainYearMonth (second argument)');
}
