<?php

declare(strict_types=1);

// Source: tests/Test262/data/Now/plainDateTimeISO/time-zone-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$resultExplicit = \Calendrics\Spec\Now::plainDateTimeISO();
Assert::assertTrue($resultExplicit instanceof \Calendrics\Spec\PlainDateTime, 'The result of evaluating (resultExplicit instanceof Temporal.PlainDateTime) is expected to be true');
$resultImplicit = \Calendrics\Spec\Now::plainDateTimeISO();
Assert::assertTrue($resultImplicit instanceof \Calendrics\Spec\PlainDateTime, 'The result of evaluating (resultImplicit instanceof Temporal.PlainDateTime) is expected to be true');
