<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/until/largestunit.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$fourFortyEight = new \Calendrics\Spec\PlainTime(4, 48, 55);
$elevenFiftyNine = new \Calendrics\Spec\PlainTime(11, 59, 58);
TemporalHelpers::assertDuration($fourFortyEight->until($elevenFiftyNine), 0, 0, 0, 0, 7, 11, 3, 0, 0, 0, 'does not include higher units than necessary (largest unit unspecified)');
TemporalHelpers::assertDuration($fourFortyEight->until($elevenFiftyNine, (object) ['largestUnit' => 'auto']), 0, 0, 0, 0, 7, 11, 3, 0, 0, 0, 'does not include higher units than necessary (largest unit is auto)');
TemporalHelpers::assertDuration($fourFortyEight->until($elevenFiftyNine, (object) ['largestUnit' => 'hours']), 0, 0, 0, 0, 7, 11, 3, 0, 0, 0, 'does not include higher units than necessary (largest unit is hours)');
TemporalHelpers::assertDuration($fourFortyEight->until($elevenFiftyNine, (object) ['largestUnit' => 'minutes']), 0, 0, 0, 0, 0, 431, 3, 0, 0, 0, 'does not include higher units than necessary (largest unit is minutes)');
TemporalHelpers::assertDuration($fourFortyEight->until($elevenFiftyNine, (object) ['largestUnit' => 'seconds']), 0, 0, 0, 0, 0, 0, 25_863, 0, 0, 0, 'does not include higher units than necessary (largest unit is seconds)');
