<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/until/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.largestUnit', 'get options.largestUnit.toString', 'call options.largestUnit.toString', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['smallestUnit' => 'hour', 'largestUnit' => 'week', 'roundingIncrement' => 1, 'roundingMode' => 'halfFloor'], 'options');
$instance = new \Calendrics\Spec\PlainTime(14);
$other = new \Calendrics\Spec\PlainTime(16);
Assert::throws(\RangeException::class, function () use (&$instance, &$other, &$options) { $instance->until($other, $options); }, 'exception thrown when largestUnit disallowed');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
