<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/until/roundingincrement-non-integer.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$earlier = new \Calendrics\Spec\PlainTime(12, 34, 56, 0, 0, 0);
$later = new \Calendrics\Spec\PlainTime(12, 34, 56, 0, 0, 5);
$result = $earlier->until($later, ['roundingIncrement' => 2.5, 'roundingMode' => 'trunc']);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 'roundingIncrement 2.5 truncates to 2');
