<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/argument-convert.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::assertPlainDate(new \Calendrics\Spec\PlainDate(2_020.6, 11.7, 24.1), 2020, 11, 'M11', 24, 'positive fractional');
TemporalHelpers::assertPlainDate(new \Calendrics\Spec\PlainDate(-2_020.6, 11.7, 24.1), -2020, 11, 'M11', 24, 'negative fractional');
TemporalHelpers::assertPlainDate(new \Calendrics\Spec\PlainDate(null, 11, 24), 0, 11, 'M11', 24, 'null');
TemporalHelpers::assertPlainDate(new \Calendrics\Spec\PlainDate(true, 11, 24), 1, 11, 'M11', 24, 'boolean');
TemporalHelpers::assertPlainDate(new \Calendrics\Spec\PlainDate('2020.6', '11.7', '24.1'), 2020, 11, 'M11', 24, 'fractional strings');
Assert::incomplete('BigInt literal in wrong-type for-of data table; Number-vs-BigInt distinction not representable in PHP');
