<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$plainDate = new \Calendrics\Spec\PlainDate(2020, 12, 24, 'iso8601');
TemporalHelpers::assertPlainDate($plainDate, 2020, 12, 'M12', 24, 'with string');
Assert::sameValue($plainDate->calendarId, 'iso8601', 'calendar string is iso8601');
