<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/add/argument-not-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\Instant(1_000_000_000_000_000_000);
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(); }, 'undefined');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(null); }, 'null');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(true); }, 'boolean');
Assert::throws(\RangeException::class, function () use (&$instance) { return $instance->add(''); }, 'empty string');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(\Calendrics\Tests\Test262\JsSymbol::singleton()); }, 'Symbol');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(7); }, 'number');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(7); }, 'bigint');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add([]); }, 'array');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(function () {  }); }, 'function');
