<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/add/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instant = new \Calendrics\Spec\Instant(1);
$blank = new \Calendrics\Spec\Duration();
$result = $instant->add($blank);
Assert::sameValue($result->epochNanoseconds, 1, 'result is unchanged');
