<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/add/minimum-maximum-instant.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$min = \Calendrics\Spec\Instant::fromEpochParts(-8640000000000, 0);
$max = \Calendrics\Spec\Instant::fromEpochParts(8640000000000, 0);
$zero = \Calendrics\Spec\Duration::from((object) ['nanoseconds' => 0]);
$one = \Calendrics\Spec\Duration::from((object) ['nanoseconds' => 1]);
$minusOne = \Calendrics\Spec\Duration::from((object) JsUndefined::strip(['nanoseconds' => -1]));
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->add($zero)), \Calendrics\Tests\Test262\JsEpoch::read($min), 'Adding zero to the minimum instant');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->add($zero)), \Calendrics\Tests\Test262\JsEpoch::read($max), 'Adding zero to the maximum instant');
Assert::throws(\RangeException::class, function () use (&$min, &$minusOne) { return $min->add($minusOne); }, 'Subtracting one from the minimum instant');
Assert::throws(\RangeException::class, function () use (&$max, &$one) { return $max->add($one); }, 'Adding one to the maximum instant');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->add($one)), \Calendrics\Tests\Test262\JsEpoch::read($min) + 1, 'Adding one to the minimum instant');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->add($minusOne)), \Calendrics\Tests\Test262\JsEpoch::read($max) - 1, 'Subtracting one from the maximum instant');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->add((object) JsUndefined::strip(['nanoseconds' => 8.64e+21 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($max), 'Minimum to maximum instant by adding nanoseconds');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->add((object) JsUndefined::strip(['microseconds' => 8_640_000_000_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($max), 'Minimum to maximum instant by adding microseconds');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->add((object) JsUndefined::strip(['milliseconds' => 8_640_000_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($max), 'Minimum to maximum instant by adding milliseconds');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($min->add((object) JsUndefined::strip(['seconds' => 8_640_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($max), 'Minimum to maximum instant by adding seconds');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->add((object) JsUndefined::strip(['nanoseconds' => -8.64e+21 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($min), 'Maximum to minimum instant by adding nanoseconds');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->add((object) JsUndefined::strip(['microseconds' => -8_640_000_000_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($min), 'Maximum to minimum instant by adding microseconds');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->add((object) JsUndefined::strip(['milliseconds' => -8_640_000_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($min), 'Maximum to minimum instant by adding milliseconds');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($max->add((object) JsUndefined::strip(['seconds' => -8_640_000_000_000 * 2]))), \Calendrics\Tests\Test262\JsEpoch::read($min), 'Maximum to minimum instant by adding seconds');
