<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/withPlainTime/argument-string-without-time-designator.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$dt = new \Calendrics\Spec\PlainDateTime(2015, 12, 7, 3, 24, 30, 0, 3, 500);
TemporalHelpers::assertPlainDateTime($dt->withPlainTime('12:34'), 2015, 12, 'M12', 7, 12, 34, 0, 0, 0, 0, 'time-like string works');
