<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/withPlainTime/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get fields.hour', 'get fields.hour.valueOf', 'call fields.hour.valueOf', 'get fields.microsecond', 'get fields.microsecond.valueOf', 'call fields.microsecond.valueOf', 'get fields.millisecond', 'get fields.millisecond.valueOf', 'call fields.millisecond.valueOf', 'get fields.minute', 'get fields.minute.valueOf', 'call fields.minute.valueOf', 'get fields.nanosecond', 'get fields.nanosecond.valueOf', 'call fields.nanosecond.valueOf', 'get fields.second', 'get fields.second.valueOf', 'call fields.second.valueOf'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$fields = TemporalHelpers::propertyBagObserver($actual, ['year' => 1.7, 'month' => 1.7, 'monthCode' => 'M01', 'day' => 1.7, 'hour' => 1, 'microsecond' => 2, 'millisecond' => 3, 'minute' => 4, 'nanosecond' => 5, 'second' => 6, 'calendar' => 'iso8601'], 'fields', ['calendar']);
$pdt = new \Calendrics\Spec\PlainDateTime(2025, 5, 2, 0, 0, 0, 0, 0, 0);
$pdt->withPlainTime($fields);
Assert::compareObserverTrace($actual, $expected, 'order of operations');
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
