<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/withCalendar/calendar-temporal-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$plainDate = new \Calendrics\Spec\PlainDate(2000, 5, 2);
$plainDateTime = new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 12, 34, 56, 987, 654, 321);
$plainMonthDay = new \Calendrics\Spec\PlainMonthDay(5, 2);
$plainYearMonth = new \Calendrics\Spec\PlainYearMonth(2000, 5);
$zonedDateTime = new \Calendrics\Spec\ZonedDateTime(1_000_000_000_000_000_000, 'UTC');
foreach ([$plainDate, $plainDateTime, $plainMonthDay, $plainYearMonth, $zonedDateTime] as $arg) {
$actual = [];
$expected = [];
// JS-only (JS-only observability getter on Temporal arg (PHP reads internal slot directly, getter never fires)): Object.defineProperty(arg, "calendar", { get() { actual.push("get calendar"); return calendar; }, });
$instance = new \Calendrics\Spec\ZonedDateTime(1_000_000_000_000_000_000, 'UTC', 'iso8601');
$result = $instance->withCalendar($arg);
Assert::sameValue($result->calendarId, 'iso8601', 'Temporal object coerced to calendar');
Assert::compareArray($actual, $expected, 'calendar getter not called');
}
