<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/equals/calendar-temporal-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkToTemporalCalendarFastPath(function ($temporalObject) use (&$datetime) { $datetime = new \Calendrics\Spec\ZonedDateTime(1_000_000_000_000_000_000, 'UTC'); $datetime->equals(JsUndefined::strip(['year' => 2005, 'month' => 6, 'day' => 2, 'timeZone' => 'UTC', 'calendar' => $temporalObject])); });
