<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/equals/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$instance = new \Calendrics\Spec\ZonedDateTime(1_000_000_000_000_000_000, 'UTC');
$base = (object) ['year' => 2000, 'month' => 5, 'day' => 2, 'hour' => 15, 'minute' => 30, 'second' => 45, 'millisecond' => 987, 'microsecond' => 654, 'nanosecond' => 321, 'timeZone' => 'UTC'];
foreach ([INF, -INF] as $inf) {
foreach (['year', 'month', 'day', 'hour', 'minute', 'second', 'millisecond', 'microsecond', 'nanosecond'] as $prop) {
Assert::throws(\RangeException::class, function () use (&$instance, &$base, &$prop, &$inf) { return $instance->equals((object) JsUndefined::strip(array_merge((array) $base, [$prop => $inf]))); }, "{$prop} property cannot be {$inf}");
$calls = new \Calendrics\Tests\Test262\ObserverTrace();
$obj = TemporalHelpers::toPrimitiveObserver($calls, $inf, $prop);
Assert::throws(\RangeException::class, function () use (&$instance, &$base, &$prop, &$obj) { return $instance->equals((object) JsUndefined::strip(array_merge((array) $base, [$prop => $obj]))); }, '');
Assert::compareObserverTrace($calls, ["get {$prop}.valueOf", "call {$prop}.valueOf"], 'it fails after fetching the primitive value');
}
}
