<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/subtract/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$blank1 = new \Calendrics\Spec\Duration();
$blank2 = new \Calendrics\Spec\Duration();
$result = $blank1->subtract($blank2);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'result is also blank');
