<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/until/options-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$instance = new \Calendrics\Spec\PlainDate(2000, 5, 2);
$result1 = $instance->until(new \Calendrics\Spec\PlainDate(1976, 11, 18), (object) []);
TemporalHelpers::assertDuration($result1, 0, 0, 0, -8566, 0, 0, 0, 0, 0, 0, 'options may be an empty plain object');
$result2 = $instance->until(new \Calendrics\Spec\PlainDate(1976, 11, 18), function () {  });
TemporalHelpers::assertDuration($result2, 0, 0, 0, -8566, 0, 0, 0, 0, 0, 0, 'options may be a function object');
