<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/until/roundingincrement-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$earlier = new \Calendrics\Spec\PlainDate(2000, 5, 2);
$later = new \Calendrics\Spec\PlainDate(2000, 5, 7);
$explicit = $earlier->until($later, (object) []);
TemporalHelpers::assertDuration($explicit, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 'default roundingIncrement is 1');
