<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/with/subclassing-ignored.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkSubclassingIgnored(\Calendrics\Spec\PlainDate::class, [2000, 5, 2], 'with', [(object) ['day' => 20]], fn($result) => TemporalHelpers::assertPlainDate($result, 2000, 5, 'M05', 20));
