<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toZonedDateTime/options-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\PlainDateTime(2000, 5, 2);
$result1 = $instance->toZonedDateTime('UTC', (object) []);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($result1), 957_225_600_000_000_000, 'options may be an empty plain object');
$result2 = $instance->toZonedDateTime('UTC', function () {  });
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($result2), 957_225_600_000_000_000, 'options may be a function object');
