<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toZonedDateTime/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.disambiguation', 'get options.disambiguation.toString', 'call options.disambiguation.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['disambiguation' => 'reject'], 'options');
$instance = new \Calendrics\Spec\PlainDateTime(-271_821, 4, 20, 0);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->toZonedDateTime('+23:59', $options); }, 'exception thrown when wall time out of range for exact time');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
