<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toZonedDateTime/plain-date-time-near-limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$dt = new \Calendrics\Spec\PlainDateTime(-271_821, 4, 19, 0, 0, 0, 0, 0, 1);
Assert::throws(\RangeException::class, function () use (&$dt) { return $dt->toZonedDateTime('UTC'); }, '');
$dt = new \Calendrics\Spec\PlainDateTime(-271_821, 4, 19, 1, 0, 0, 0, 0, 0);
Assert::throws(\RangeException::class, function () use (&$dt) { return $dt->toZonedDateTime('UTC'); }, '');
$dt = new \Calendrics\Spec\PlainDateTime(275_760, 9, 13, 0, 0, 0, 0, 0, 1);
Assert::throws(\RangeException::class, function () use (&$dt) { return $dt->toZonedDateTime('UTC'); }, '');
$dt = new \Calendrics\Spec\PlainDateTime(275_760, 9, 13, 1, 0, 0, 0, 0, 0);
Assert::throws(\RangeException::class, function () use (&$dt) { return $dt->toZonedDateTime('UTC'); }, '');
