<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toZonedDateTime/timezone-case-insensitive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\PlainDateTime(2000, 5, 2);
$timeZone = 'uTc';
$result = $instance->toZonedDateTime($timeZone);
Assert::sameValue($result->timeZoneId, 'UTC', "Time zone created from string \"{$timeZone}\"");
