<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/toPlainDate/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$ym = \Calendrics\Spec\PlainYearMonth::from('2002-01');
TemporalHelpers::assertPlainDate($ym->toPlainDate(['day' => 22]), 2002, 1, 'M01', 22);
Assert::throws(\TypeError::class, function () use (&$ym) { return $ym->toPlainDate(['something' => 'nothing']); }, '');
