<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/toPlainDate/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get fields.day', 'get fields.day.valueOf', 'call fields.day.valueOf'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$fields = TemporalHelpers::propertyBagObserver($actual, ['year' => 1.7, 'month' => 1.7, 'monthCode' => 'M01', 'day' => 1, 'calendar' => 'iso8601'], 'fields', ['calendar']);
$pym = new \Calendrics\Spec\PlainYearMonth(2005, 2);
$pym->toPlainDate($fields);
Assert::compareObserverTrace($actual, $expected, 'order of operations');
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
