<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/calendarId/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\PlainDateTime(2000, 3, 6, 12, 45, 22, 768, 234, 899);
Assert::sameValue($instance->calendarId, 'iso8601', '');
