<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/compare/argument-propertybag-invalid-offset-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$timeZone = 'UTC';
$datetime = new \Calendrics\Spec\ZonedDateTime(1_000_000_000_987_654_321, $timeZone);
$badOffsets = ['00:00', '+0', '-000:00', 0, null, true, 1000];
foreach ($badOffsets as $offset) {
if ($offset === null) { continue; }
$arg = (object) JsUndefined::strip(['year' => 2021, 'month' => 10, 'day' => 28, 'offset' => $offset, 'timeZone' => $timeZone]);
Assert::throws((is_string($offset) ? \RangeException::class : \TypeError::class), function () use (&$arg, &$datetime) { return \Calendrics\Spec\ZonedDateTime::compare($arg, $datetime); }, "\"{$offset} is not a valid offset string (second argument)");
Assert::throws((is_string($offset) ? \RangeException::class : \TypeError::class), function () use (&$datetime, &$arg) { return \Calendrics\Spec\ZonedDateTime::compare($datetime, $arg); }, "\"{$offset} is not a valid offset string (second argument)");
}
