<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/compare/calendar-temporal-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkToTemporalCalendarFastPath(function ($temporalObject) { \Calendrics\Spec\ZonedDateTime::compare(JsUndefined::strip(['year' => 2000, 'month' => 5, 'day' => 2, 'timeZone' => 'UTC', 'calendar' => $temporalObject]), JsUndefined::strip(['year' => 2001, 'month' => 6, 'day' => 3, 'timeZone' => 'UTC', 'calendar' => $temporalObject])); });
