<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/compare/compares-exact-time-not-clock-time.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$clockBefore = new \Calendrics\Spec\ZonedDateTime(946_711_800_000_000_000, '-08:00');
$clockAfter = new \Calendrics\Spec\ZonedDateTime(946_704_600_000_000_000, '-04:00');
Assert::sameValue(\Calendrics\Spec\ZonedDateTime::compare($clockBefore, $clockAfter), 1, '');
Assert::sameValue(\Calendrics\Spec\PlainDateTime::compare($clockBefore->toPlainDateTime(), $clockAfter->toPlainDateTime()), -1, '');
