<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toString/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.calendarName', 'get options.calendarName.toString', 'call options.calendarName.toString', 'get options.fractionalSecondDigits', 'get options.fractionalSecondDigits.toString', 'call options.fractionalSecondDigits.toString', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['calendarName' => 'always', 'smallestUnit' => 'month', 'fractionalSecondDigits' => 'auto', 'roundingMode' => 'expand'], 'options');
$instance = new \Calendrics\Spec\PlainDateTime(2025, 8, 14, 12);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->toString($options); }, 'exception thrown when smallestUnit is a date unit');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
