<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/round/negative-time.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\ZonedDateTime(-1_000_000_000_000_000_000, 'UTC');
$roundedDown = -1_000_000_800_000_000_000;
$roundedUp = -999_997_200_000_000_000;
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($instance->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfCeil'])), $roundedDown, 'Rounding with halfCeil rounds to the closest hour');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($instance->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfFloor'])), $roundedDown, 'Rounding with halfFloor rounds to the closest hour');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($instance->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfExpand'])), $roundedDown, 'Rounding with halfExpand rounds to the closest hour');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($instance->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfTrunc'])), $roundedDown, 'Rounding with halfTrunc rounds to the closest hour');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($instance->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfEven'])), $roundedDown, 'Rounding with halfEven rounds to the closest hour');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($instance->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'ceil'])), $roundedUp, 'Rounding with ceil rounds to the next hour');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($instance->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'floor'])), $roundedDown, 'Rounding with floor rounds to the closest hour');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($instance->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'expand'])), $roundedUp, 'Rounding with expand rounds to the next hour');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($instance->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'trunc'])), $roundedDown, 'Rounding with trunc rounds to the closest hour');
