<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/round/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['smallestUnit' => 'hour', 'roundingIncrement' => 25, 'roundingMode' => 'expand'], 'options');
$instance = new \Calendrics\Spec\ZonedDateTime(1, 'UTC');
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->round($options); }, 'exception thrown when roundingIncrement invalid for smallestUnit');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
