<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/round/rounded-date-time-outside-valid-limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
// Folded (BigInt 8640000000000000000000 exceeds int64): nsMaxInstant
// Folded (BigInt 8640000000000000000000 exceeds int64): epochNs
$zdt = \Temporal\Spec\ZonedDateTime::fromEpochParts(8640000000000, 0, '+23:59');
$roundTo = ['smallestUnit' => 'minutes', 'roundingIncrement' => 10, 'roundingMode' => 'ceil'];
Assert::throws(\RangeException::class, function () use (&$zdt, &$roundTo) { return $zdt->round($roundTo); }, '');
