<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/round/smallestunit.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$bal = new \Calendrics\Spec\ZonedDateTime(217_205_999_999_999_999, '+01:00');
$expected = new \Calendrics\Spec\ZonedDateTime(217_206_000_000_000_000, '+01:00');
foreach (['day', 'hour', 'minute', 'second', 'millisecond', 'microsecond'] as $smallestUnit) {
TemporalHelpers::assertZonedDateTimesEqual($bal->round((object) JsUndefined::strip(['smallestUnit' => $smallestUnit])), $expected);
}
