<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/getTimeZoneTransition/specific-tzdb-values.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$a1 = new \Calendrics\Spec\ZonedDateTime(1_555_448_460_000_000_000, 'America/New_York');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($a1->getTimeZoneTransition('next')), 1_572_760_800_000_000_000, '');
$a2 = new \Calendrics\Spec\ZonedDateTime(-5_364_662_400_000_000_000, 'America/New_York');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($a2->getTimeZoneTransition('next')), -2_717_650_800_000_000_000, '');
$a3 = new \Calendrics\Spec\ZonedDateTime(1_591_909_260_000_000_000, 'Europe/London');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($a3->getTimeZoneTransition('previous')), 1_585_443_600_000_000_000, '');
$a4 = new \Calendrics\Spec\ZonedDateTime(-3_849_984_000_000_000_000, 'Europe/London');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($a4->getTimeZoneTransition('previous')), -3_852_662_325_000_000_000, '');
