<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/calendar-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$arg = 'iso8601';
$result = new \Calendrics\Spec\PlainYearMonth(2000, 5, $arg, 1);
Assert::sameValue($result->calendarId, 'iso8601', "Calendar created from string \"{$arg}\"");
