<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/calendar-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get year.valueOf', 'call year.valueOf', 'get month.valueOf', 'call month.valueOf'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$args = [TemporalHelpers::toPrimitiveObserver($actual, 1970, 'year'), TemporalHelpers::toPrimitiveObserver($actual, 1, 'month'), 'local', TemporalHelpers::toPrimitiveObserver($actual, 1, 'day')];
// JS-only (spread of statically too-short array; PHP throws ArgumentCountError): assert.throws(RangeError, () => new Temporal.PlainYearMonth(...args));
// JS-only (trace covers a call skipped above, so the tracker is empty here): assert.compareArray(actual, expected, "order of operations");
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
