<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Instant/prototype/toLocaleString/datestyle-not-adjusted-when-no-conflicting-options.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$date = new \Calendrics\Tests\Test262\JsDate(0);
$instant = new \Calendrics\Spec\Instant(0, 'UTC');
$options = (object) ['dateStyle' => 'full'];
Assert::sameValue($date->toLocaleString('ja', $options), $instant->toLocaleString('ja', $options), '');
