<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Instant/prototype/toLocaleString/dateStyle-timeStyle-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instant = new \Calendrics\Spec\Instant(957_270_896_987_650_000);
$defaultFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en');
$expected = $defaultFormatter->format($instant);
$actualDate = $instant->toLocaleString('en', (object) []);
Assert::sameValue($actualDate, $expected, 'dateStyle undefined is the same as being absent');
$actualTime = $instant->toLocaleString('en', (object) []);
Assert::sameValue($actualTime, $expected, 'timeStyle undefined is the same as being absent');
