<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Instant/prototype/toLocaleString/era.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instant = new \Calendrics\Spec\Instant(0);
$instantResult = $instant->toLocaleString('en', ['era' => 'narrow']);
$dateResult = new \Calendrics\Tests\Test262\JsDate(0)->toLocaleString(['en'], ['era' => 'narrow']);
Assert::sameValue($instantResult, $dateResult, 'toLocaleString on an Instant with era option should return the same results as toLocaleString on the same Date with the same options');
