<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Instant/prototype/toLocaleString/lone-options-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$epochMs = 1_735_213_600_321;
$epochNs = 1_735_213_600_321_000_000;
$legacyDate = new \Calendrics\Tests\Test262\JsDate($epochMs);
$instant = new \Calendrics\Spec\Instant($epochNs);
foreach ([(object) ['year' => 'numeric'], (object) ['month' => 'long'], (object) ['day' => 'numeric'], (object) ['weekday' => 'long'], (object) ['hour' => 'numeric'], (object) ['minute' => 'numeric'], (object) ['second' => 'numeric'], (object) ['fractionalSecondDigits' => 3], (object) ['dayPeriod' => 'short'], (object) ['timeZoneName' => 'short']] as $options) {
$instantResult = $instant->toLocaleString('en', $options);
$legacyDateResult = $legacyDate->toLocaleString('en', $options);
Assert::sameValue($instantResult, $legacyDateResult, "Instant.toLocaleString should format lone option " . (json_encode($options)) . "");
}
