<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Instant/prototype/toLocaleString/lone-options-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$epochMs = 1_735_213_600_321;
$epochNs = 1_735_213_600_321_000_000;
$legacyDate = new \Temporal\Tests\Test262\JsDate($epochMs);
$instant = new \Temporal\Spec\Instant($epochNs);
foreach ([['year' => 'numeric'], ['month' => 'long'], ['day' => 'numeric'], ['weekday' => 'long'], ['hour' => 'numeric'], ['minute' => 'numeric'], ['second' => 'numeric'], ['fractionalSecondDigits' => 3], ['dayPeriod' => 'short'], ['timeZoneName' => 'short']] as $options) {
$instantResult = $instant->toLocaleString('en', $options);
$legacyDateResult = $legacyDate->toLocaleString('en', $options);
Assert::sameValue($instantResult, $legacyDateResult, "Instant.toLocaleString should format lone option " . (json_encode($options)) . "");
}
