<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Instant/prototype/toLocaleString/respect-timezone-after-formatting-plaindatetime.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$datestring = '2026-03-29T02:30:15+01:00';
$instant = \Calendrics\Spec\Instant::from($datestring);
$pdt = \Calendrics\Spec\PlainDateTime::from($datestring);
$legacyDate = new \Calendrics\Tests\Test262\JsDate($instant->epochMilliseconds);
$expected1 = $legacyDate->toLocaleString('en', ['timeStyle' => 'long', 'timeZone' => 'America/Los_Angeles']);
$expected2 = $legacyDate->toLocaleString('en', ['timeStyle' => 'long', 'timeZone' => 'Europe/Berlin']);
$pdt->toLocaleString('en', ['timeStyle' => 'long']);
Assert::sameValue($instant->toLocaleString('en', ['timeStyle' => 'long', 'timeZone' => 'America/Los_Angeles']), $expected1, '');
Assert::sameValue($instant->toLocaleString('en', ['timeStyle' => 'long', 'timeZone' => 'Europe/Berlin']), $expected2, '');
new \Calendrics\Spec\PlainDate(2011, 12, 30)->toLocaleString('en');
Assert::sameValue(new \Calendrics\Spec\Instant(0)->toLocaleString('en', ['era' => 'narrow']), new \Calendrics\Tests\Test262\JsDate(0)->toLocaleString(['en'], ['era' => 'narrow']), '');
