<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/prototype/equals/calendars.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$mdA = new \Calendrics\Spec\PlainMonthDay(2, 7, 'iso8601');
$mdB = new \Calendrics\Spec\PlainMonthDay(2, 7, 'gregory');
$mdC = new \Calendrics\Spec\PlainMonthDay(2, 7, 'iso8601', 1974);
Assert::sameValue($mdA->equals($mdC), false, 'different year');
Assert::sameValue($mdA->equals($mdB), false, 'different calendar');
