<?php

declare(strict_types=1);

// Source: tests/Test262/data/Now/zonedDateTimeISO/return-value.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$zdt = \Calendrics\Spec\Now::zonedDateTimeISO();
Assert::assertTrue($zdt instanceof \Calendrics\Spec\ZonedDateTime, '');
Assert::sameValue($zdt->calendarId, 'iso8601', 'calendar string should be iso8601');
Assert::sameValue($zdt->timeZoneId, \Calendrics\Spec\Now::timeZoneId(), 'time zone string should be the same as from Now');
