<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/subtract/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$d = new \Calendrics\Spec\PlainDate(2025, 8, 22);
$blank = new \Calendrics\Spec\Duration();
$result = $d->subtract($blank);
TemporalHelpers::assertPlainDate($result, 2025, 8, 'M08', 22, 'result is unchanged');
