<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/balances-up-to-weeks.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$oneMonthOneDay = new \Calendrics\Spec\Duration(0, 1, 0, 1, 0, 0, 0, 0, 0, 0);
$oneYearOneMonthOneDay = new \Calendrics\Spec\Duration(1, 1, 0, 1, 0, 0, 0, 0, 0, 0);
$severalWeeksInDays = new \Calendrics\Spec\Duration(0, 0, 0, 29, 0, 0, 0, 0, 0, 0);
$relativeTo = new \Calendrics\Spec\PlainDate(2024, 1, 1);
Assert::throws(\RangeException::class, function () use (&$oneMonthOneDay, &$relativeTo) { return $oneMonthOneDay->round((object) JsUndefined::strip(['relativeTo' => $relativeTo, 'smallestUnit' => 'weeks', 'roundingIncrement' => 99, 'roundingMode' => 'ceil'])); }, '');
TemporalHelpers::assertDuration($oneMonthOneDay->round((object) JsUndefined::strip(['relativeTo' => $relativeTo, 'largestUnit' => 'weeks', 'smallestUnit' => 'weeks', 'roundingIncrement' => 99, 'roundingMode' => 'ceil'])), 0, 0, 99, 0, 0, 0, 0, 0, 0, 0);
TemporalHelpers::assertDuration($oneMonthOneDay->round((object) JsUndefined::strip(['relativeTo' => $relativeTo, 'largestUnit' => 'weeks', 'smallestUnit' => 'weeks', 'roundingIncrement' => 6, 'roundingMode' => 'ceil'])), 0, 0, 6, 0, 0, 0, 0, 0, 0, 0);
TemporalHelpers::assertDuration($oneYearOneMonthOneDay->round((object) JsUndefined::strip(['relativeTo' => $relativeTo, 'largestUnit' => 'weeks', 'smallestUnit' => 'weeks', 'roundingIncrement' => 99, 'roundingMode' => 'ceil'])), 0, 0, 99, 0, 0, 0, 0, 0, 0, 0);
TemporalHelpers::assertDuration($oneYearOneMonthOneDay->round((object) JsUndefined::strip(['relativeTo' => $relativeTo, 'largestUnit' => 'weeks', 'smallestUnit' => 'weeks', 'roundingIncrement' => 57, 'roundingMode' => 'ceil'])), 0, 0, 57, 0, 0, 0, 0, 0, 0, 0);
TemporalHelpers::assertDuration($severalWeeksInDays->round((object) JsUndefined::strip(['relativeTo' => $relativeTo, 'largestUnit' => 'weeks', 'smallestUnit' => 'weeks', 'roundingIncrement' => 5, 'roundingMode' => 'ceil'])), 0, 0, 5, 0, 0, 0, 0, 0, 0, 0);
TemporalHelpers::assertDuration($severalWeeksInDays->round((object) JsUndefined::strip(['relativeTo' => $relativeTo, 'largestUnit' => 'weeks', 'smallestUnit' => 'weeks', 'roundingIncrement' => 8, 'roundingMode' => 'ceil'])), 0, 0, 8, 0, 0, 0, 0, 0, 0, 0);
