<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$blank = new \Calendrics\Spec\Duration();
$plainRelativeTo = new \Calendrics\Spec\PlainDate(2025, 8, 22);
$zonedRelativeTo = new \Calendrics\Spec\ZonedDateTime(1, 'UTC');
foreach (['days', 'hours', 'minutes', 'seconds', 'milliseconds', 'microseconds', 'nanoseconds'] as $smallestUnit) {
$result = $blank->round($smallestUnit);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "round to {$smallestUnit} without relativeTo");
$result = $blank->round(JsUndefined::strip(['smallestUnit' => $smallestUnit, 'relativeTo' => $plainRelativeTo]));
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "round to {$smallestUnit} with PlainDate relativeTo");
$result = $blank->round(JsUndefined::strip(['smallestUnit' => $smallestUnit, 'relativeTo' => $zonedRelativeTo]));
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "round to {$smallestUnit} with ZonedDateTime relativeTo");
}
foreach (['years', 'months', 'weeks'] as $smallestUnit) {
$result = $blank->round(JsUndefined::strip(['smallestUnit' => $smallestUnit, 'relativeTo' => $plainRelativeTo]));
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "round to {$smallestUnit} with PlainDate relativeTo");
$result = $blank->round(JsUndefined::strip(['smallestUnit' => $smallestUnit, 'relativeTo' => $zonedRelativeTo]));
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "round to {$smallestUnit} with ZonedDateTime relativeTo");
}
