<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/largestunit-smallestunit-default.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$relativeTo = \Calendrics\Spec\PlainDate::from('2020-01-01');
$almostYear = \Calendrics\Spec\Duration::from(['days' => 364]);
TemporalHelpers::assertDuration($almostYear->round(JsUndefined::strip(['smallestUnit' => 'years', 'relativeTo' => $relativeTo])), 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'years');
$almostMonth = \Calendrics\Spec\Duration::from(['days' => 27]);
TemporalHelpers::assertDuration($almostMonth->round(JsUndefined::strip(['smallestUnit' => 'months', 'relativeTo' => $relativeTo])), 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'months');
$almostWeek = \Calendrics\Spec\Duration::from(['days' => 6]);
TemporalHelpers::assertDuration($almostWeek->round(JsUndefined::strip(['smallestUnit' => 'weeks', 'relativeTo' => $relativeTo])), 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'weeks');
$almostDay = \Calendrics\Spec\Duration::from(['seconds' => 86_399]);
TemporalHelpers::assertDuration($almostDay->round(['smallestUnit' => 'days']), 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'days');
$almostHour = \Calendrics\Spec\Duration::from(['seconds' => 3599]);
TemporalHelpers::assertDuration($almostHour->round(['smallestUnit' => 'hours']), 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 'hours');
$almostMinute = \Calendrics\Spec\Duration::from(['seconds' => 59]);
TemporalHelpers::assertDuration($almostMinute->round(['smallestUnit' => 'minutes']), 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 'minutes');
$almostSecond = \Calendrics\Spec\Duration::from(['nanoseconds' => 999_999_999]);
TemporalHelpers::assertDuration($almostSecond->round(['smallestUnit' => 'seconds']), 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 'seconds');
$almostMillisecond = \Calendrics\Spec\Duration::from(['nanoseconds' => 999_999]);
TemporalHelpers::assertDuration($almostMillisecond->round(['smallestUnit' => 'milliseconds']), 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 'milliseconds');
$almostMicrosecond = \Calendrics\Spec\Duration::from(['nanoseconds' => 999]);
TemporalHelpers::assertDuration($almostMicrosecond->round(['smallestUnit' => 'microseconds']), 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 'microseconds');
