<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.largestUnit', 'get options.largestUnit.toString', 'call options.largestUnit.toString', 'get options.relativeTo', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['smallestUnit' => 'years', 'largestUnit' => 'nanoseconds', 'roundingIncrement' => 1, 'roundingMode' => 'halfCeil'], 'options');
$instance = new \Calendrics\Spec\Duration(1);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->round($options); }, 'exception thrown when smallestUnit > largestUnit');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
$actual->clear();
$expectedWithoutUnits = ['get options.largestUnit', 'get options.relativeTo', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit'];
$optionsWithoutUnits = TemporalHelpers::propertyBagObserver($actual, (object) ['roundingIncrement' => 1, 'roundingMode' => 'halfFloor'], 'options');
Assert::throws(\RangeException::class, function () use (&$instance, &$optionsWithoutUnits) { $instance->round($optionsWithoutUnits); }, 'exception thrown when neither smallestUnit nor largestUnit present');
Assert::compareObserverTrace($actual, $expectedWithoutUnits, 'all options should be read first');
$actual->clear();
