<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$createOptionsObserver = function ($__dp0 = []) use (&$actual) {
$smallestUnit = \Temporal\Tests\Test262\Js::destructure($__dp0, 'smallestUnit') ?? 'nanoseconds';
$largestUnit = \Temporal\Tests\Test262\Js::destructure($__dp0, 'largestUnit') ?? 'auto';
$roundingMode = \Temporal\Tests\Test262\Js::destructure($__dp0, 'roundingMode') ?? 'halfExpand';
$roundingIncrement = \Temporal\Tests\Test262\Js::destructure($__dp0, 'roundingIncrement') ?? 1;
$relativeTo = \Temporal\Tests\Test262\Js::destructure($__dp0, 'relativeTo') ?? null;
return TemporalHelpers::propertyBagObserver($actual, (object) JsUndefined::strip(['smallestUnit' => $smallestUnit, 'largestUnit' => $largestUnit, 'roundingMode' => $roundingMode, 'roundingIncrement' => $roundingIncrement, 'relativeTo' => $relativeTo]), 'options');
};
// JS-only (checkTemporalObject() arms negative probes that are a no-op in PHP): function checkTemporalObject(object) { ["year", "month", "monthCode", "day", "hour", "minute", "second", "millisecond", "microsecond", "nanosecond"].forEach((p…
$expected = ['get options.largestUnit', 'get options.largestUnit.toString', 'call options.largestUnit.toString', 'get options.relativeTo', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString'];
$actual = new \Temporal\Tests\Test262\ObserverTrace();
$instance = new \Temporal\Spec\Duration(0, 0, 0, 0, 2400);
$instance->round($createOptionsObserver((object) ['smallestUnit' => 'microseconds']));
Assert::compareObserverTrace($actual, $expected, 'order of operations');
$actual->clear();
$pd = new \Temporal\Spec\PlainDate(2026, 3, 6);
// JS-only (arms negative probes on a Temporal instance; PHP cannot arm one and never reads through one): checkTemporalObject(pd);
$instance->round($createOptionsObserver((object) JsUndefined::strip(['relativeTo' => $pd])));
Assert::compareObserverTrace($actual, $expected, 'relativeTo PlainDate should not read property bag fields');
$actual->clear();
$zdt = new \Temporal\Spec\ZonedDateTime(1_772_751_600_000_000_000, 'UTC');
// JS-only (arms negative probes on a Temporal instance; PHP cannot arm one and never reads through one): checkTemporalObject(zdt);
$instance->round($createOptionsObserver((object) JsUndefined::strip(['relativeTo' => $zdt])));
Assert::compareObserverTrace($actual, $expected, 'relativeTo ZonedDateTime should not read property bag fields');
$actual->clear();
$expectedOpsForPlainRelativeTo = ['get options.largestUnit', 'get options.largestUnit.toString', 'call options.largestUnit.toString', 'get options.relativeTo', 'get options.relativeTo.calendar', 'get options.relativeTo.day', 'get options.relativeTo.day.valueOf', 'call options.relativeTo.day.valueOf', 'get options.relativeTo.hour', 'get options.relativeTo.microsecond', 'get options.relativeTo.millisecond', 'get options.relativeTo.minute', 'get options.relativeTo.month', 'get options.relativeTo.month.valueOf', 'call options.relativeTo.month.valueOf', 'get options.relativeTo.monthCode', 'get options.relativeTo.monthCode.toString', 'call options.relativeTo.monthCode.toString', 'get options.relativeTo.nanosecond', 'get options.relativeTo.offset', 'get options.relativeTo.second', 'get options.relativeTo.timeZone', 'get options.relativeTo.year', 'get options.relativeTo.year.valueOf', 'call options.relativeTo.year.valueOf', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString'];
$plainRelativeTo = TemporalHelpers::propertyBagObserver($actual, (object) ['year' => 2001, 'month' => 5, 'monthCode' => 'M05', 'day' => 2, 'calendar' => 'iso8601'], 'options.relativeTo', ['calendar']);
$instance->round($createOptionsObserver((object) JsUndefined::strip(['relativeTo' => $plainRelativeTo])));
Assert::compareObserverTrace($actual, $expectedOpsForPlainRelativeTo, 'order of operations for PlainDate relativeTo');
$actual->clear();
$expectedOpsForZonedRelativeTo = ['get options.largestUnit', 'get options.largestUnit.toString', 'call options.largestUnit.toString', 'get options.relativeTo', 'get options.relativeTo.calendar', 'get options.relativeTo.day', 'get options.relativeTo.day.valueOf', 'call options.relativeTo.day.valueOf', 'get options.relativeTo.hour', 'get options.relativeTo.hour.valueOf', 'call options.relativeTo.hour.valueOf', 'get options.relativeTo.microsecond', 'get options.relativeTo.microsecond.valueOf', 'call options.relativeTo.microsecond.valueOf', 'get options.relativeTo.millisecond', 'get options.relativeTo.millisecond.valueOf', 'call options.relativeTo.millisecond.valueOf', 'get options.relativeTo.minute', 'get options.relativeTo.minute.valueOf', 'call options.relativeTo.minute.valueOf', 'get options.relativeTo.month', 'get options.relativeTo.month.valueOf', 'call options.relativeTo.month.valueOf', 'get options.relativeTo.monthCode', 'get options.relativeTo.monthCode.toString', 'call options.relativeTo.monthCode.toString', 'get options.relativeTo.nanosecond', 'get options.relativeTo.nanosecond.valueOf', 'call options.relativeTo.nanosecond.valueOf', 'get options.relativeTo.offset', 'get options.relativeTo.offset.toString', 'call options.relativeTo.offset.toString', 'get options.relativeTo.second', 'get options.relativeTo.second.valueOf', 'call options.relativeTo.second.valueOf', 'get options.relativeTo.timeZone', 'get options.relativeTo.year', 'get options.relativeTo.year.valueOf', 'call options.relativeTo.year.valueOf', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString'];
$zonedRelativeTo = TemporalHelpers::propertyBagObserver($actual, (object) ['year' => 2001, 'month' => 5, 'monthCode' => 'M05', 'day' => 2, 'hour' => 6, 'minute' => 54, 'second' => 32, 'millisecond' => 987, 'microsecond' => 654, 'nanosecond' => 321, 'offset' => '+00:00', 'calendar' => 'iso8601', 'timeZone' => 'UTC'], 'options.relativeTo', ['calendar', 'timeZone']);
$instance->round($createOptionsObserver((object) JsUndefined::strip(['relativeTo' => $zonedRelativeTo])));
Assert::compareObserverTrace($actual, $expectedOpsForZonedRelativeTo, 'order of operations for ZonedDateTime relativeTo');
$actual->clear();
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
