<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$createOptionsObserver = function ($__dp0 = []) use (&$actual) {
$smallestUnit = \Temporal\Tests\Test262\Js::destructure($__dp0, 'smallestUnit') ?? 'nanoseconds';
$largestUnit = \Temporal\Tests\Test262\Js::destructure($__dp0, 'largestUnit') ?? 'auto';
$roundingMode = \Temporal\Tests\Test262\Js::destructure($__dp0, 'roundingMode') ?? 'halfExpand';
$roundingIncrement = \Temporal\Tests\Test262\Js::destructure($__dp0, 'roundingIncrement') ?? 1;
$relativeTo = \Temporal\Tests\Test262\Js::destructure($__dp0, 'relativeTo') ?? null;
return TemporalHelpers::propertyBagObserver($actual, JsUndefined::strip(['smallestUnit' => $smallestUnit, 'largestUnit' => $largestUnit, 'roundingMode' => $roundingMode, 'roundingIncrement' => $roundingIncrement, 'relativeTo' => $relativeTo]), 'options');
};
Assert::incomplete('untranslatable: Object.defineProperty');
