<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/precision-exact-in-balance-time-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$seconds = 8_692_288_669_465_520;
$milliseconds = 513;
$d = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, $seconds, $milliseconds);
$result = $d->round(['largestUnit' => 'milliseconds']);
$expectedMilliseconds = 8.69228866946552E+18;
Assert::sameValue($expectedMilliseconds, 8_692_288_669_465_520_128, 'check expected value (ms)');
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, $expectedMilliseconds, 0, 0, 'BalanceTimeDuration should implement floating-point calculation correctly for largestUnit milliseconds');
$microseconds = 373_761;
$d = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, $seconds, 0, $microseconds);
$result = $d->round(['largestUnit' => 'microseconds']);
$expectedMicroseconds = 8.692288669465521E+21;
Assert::sameValue($expectedMicroseconds, 8.692_288_669_465_521e+21, 'check expected value (µs)');
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, $expectedMicroseconds, 0, 'BalanceTimeDuration should implement floating-point calculation correctly for largestUnit milliseconds');
$nanoseconds = 321_414_345;
$d = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, $seconds, 0, 0, $nanoseconds);
$result = $d->round(['largestUnit' => 'nanoseconds']);
$expectedNanoseconds = 8.692288669465521E+24;
Assert::sameValue($expectedNanoseconds, 8.692_288_669_465_521e+24, 'check expected value (ns)');
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, $expectedNanoseconds, 'BalanceTimeDuration should implement floating-point calculation correctly for largestUnit nanoseconds');
