<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/relativeto-rounding-near-minimum-date.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$relativeTo = new \Calendrics\Spec\PlainDate(-271_821, 5, 19);
$duration = new \Calendrics\Spec\Duration(0, 0, 0, 0, -23);
$result = $duration->round(JsUndefined::strip(['largestUnit' => 'year', 'smallestUnit' => 'day', 'roundingMode' => 'expand', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDuration($result, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, '-23 hours rounds to -1 day near minimum date');
