<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/roundingincrement-out-of-range.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\Duration(1);
$options = JsUndefined::strip(['smallestUnit' => 'years', 'relativeTo' => new \Calendrics\Spec\PlainDate(2000, 1, 1)]);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { return $instance->round(JsUndefined::strip(array_merge($options, ['roundingIncrement' => -INF]))); }, '');
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { return $instance->round(JsUndefined::strip(array_merge($options, ['roundingIncrement' => -1]))); }, '');
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { return $instance->round(JsUndefined::strip(array_merge($options, ['roundingIncrement' => 0]))); }, '');
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { return $instance->round(JsUndefined::strip(array_merge($options, ['roundingIncrement' => 1_000_000_000 + 1]))); }, '');
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { return $instance->round(JsUndefined::strip(array_merge($options, ['roundingIncrement' => INF]))); }, '');
