<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/rounding-increment-relativeto.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$plainRelativeTo = new \Calendrics\Spec\PlainDate(2020, 1, 1);
$zonedRelativeTo = new \Calendrics\Spec\ZonedDateTime(0, 'UTC');
foreach ([$plainRelativeTo, $zonedRelativeTo] as $relativeTo) {
TemporalHelpers::assertDuration(new \Calendrics\Spec\Duration(0, 0, 1, 0, 168)->round(JsUndefined::strip(['smallestUnit' => 'weeks', 'roundingIncrement' => 2, 'relativeTo' => $relativeTo])), 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "1w168h to 2w with relativeTo {$relativeTo}");
}
foreach ([JsUndefined::singleton(), $plainRelativeTo, $zonedRelativeTo] as $relativeTo) {
TemporalHelpers::assertDuration(new \Calendrics\Spec\Duration(0, 0, 0, 0, 48)->round(JsUndefined::strip(['smallestUnit' => 'days', 'roundingIncrement' => 2, 'relativeTo' => $relativeTo])), 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, "48h to 2d with relativeTo {$relativeTo}");
}
TemporalHelpers::assertDuration(new \Calendrics\Spec\Duration(0, 1, 0, 30)->round(JsUndefined::strip(['smallestUnit' => 'months', 'roundingIncrement' => 2, 'relativeTo' => new \Calendrics\Spec\PlainDate(1970, 3, 1)])), 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "1m30d to 2m with relativeTo 1970-03-01");
TemporalHelpers::assertDuration(new \Calendrics\Spec\Duration(0, 1, 0, 30)->round(JsUndefined::strip(['smallestUnit' => 'months', 'roundingIncrement' => 2, 'relativeTo' => new \Calendrics\Spec\PlainDate(1970, 7, 31)])), 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "1m30d to 2m with relativeTo 1970-07-31");
