<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/zero-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$zero = new \Calendrics\Spec\Duration();
$relativeToDates = [new \Calendrics\Spec\ZonedDateTime(0, 'UTC'), new \Calendrics\Spec\PlainDateTime(1970, 1, 1)];
$units = [(object) ['smallestUnit' => 'hours', 'largestUnit' => 'days'], (object) ['smallestUnit' => 'minutes', 'largestUnit' => 'days'], (object) ['smallestUnit' => 'seconds', 'largestUnit' => 'days'], (object) ['smallestUnit' => 'hours', 'largestUnit' => 'weeks'], (object) ['smallestUnit' => 'minutes', 'largestUnit' => 'weeks'], (object) ['smallestUnit' => 'seconds', 'largestUnit' => 'weeks'], (object) ['smallestUnit' => 'hours', 'largestUnit' => 'months'], (object) ['smallestUnit' => 'minutes', 'largestUnit' => 'months'], (object) ['smallestUnit' => 'seconds', 'largestUnit' => 'months'], (object) ['smallestUnit' => 'hours', 'largestUnit' => 'years'], (object) ['smallestUnit' => 'minutes', 'largestUnit' => 'years'], (object) ['smallestUnit' => 'seconds', 'largestUnit' => 'years']];
foreach ($relativeToDates as $relativeTo) {
foreach ($units as $unit) {
TemporalHelpers::assertDuration($zero->round((object) JsUndefined::strip(['smallestUnit' => $unit->smallestUnit, 'largestUnit' => $unit->largestUnit, 'relativeTo' => $relativeTo])), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
}
}
