<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/zero-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$zero = new \Calendrics\Spec\Duration();
$relativeToDates = [new \Calendrics\Spec\ZonedDateTime(0, 'UTC'), new \Calendrics\Spec\PlainDateTime(1970, 1, 1)];
$units = [['smallestUnit' => 'hours', 'largestUnit' => 'days'], ['smallestUnit' => 'minutes', 'largestUnit' => 'days'], ['smallestUnit' => 'seconds', 'largestUnit' => 'days'], ['smallestUnit' => 'hours', 'largestUnit' => 'weeks'], ['smallestUnit' => 'minutes', 'largestUnit' => 'weeks'], ['smallestUnit' => 'seconds', 'largestUnit' => 'weeks'], ['smallestUnit' => 'hours', 'largestUnit' => 'months'], ['smallestUnit' => 'minutes', 'largestUnit' => 'months'], ['smallestUnit' => 'seconds', 'largestUnit' => 'months'], ['smallestUnit' => 'hours', 'largestUnit' => 'years'], ['smallestUnit' => 'minutes', 'largestUnit' => 'years'], ['smallestUnit' => 'seconds', 'largestUnit' => 'years']];
foreach ($relativeToDates as $relativeTo) {
foreach ($units as $unit) {
TemporalHelpers::assertDuration($zero->round(JsUndefined::strip(['smallestUnit' => $unit['smallestUnit'], 'largestUnit' => $unit['largestUnit'], 'relativeTo' => $relativeTo])), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
}
}
