<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/round/options-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$badOptions = [JsUndefined::singleton(), null, true, \Calendrics\Tests\Test262\JsSymbol::singleton(), 1, 2];
$instance = new \Calendrics\Spec\Instant(0);
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->round(); }, 'TypeError on missing options argument');
foreach ($badOptions as $value) {
Assert::throws(\TypeError::class, function () use (&$instance, &$value) { return $instance->round($value); }, "TypeError on wrong options type " . (gettype($value)) . "");
}
