<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/round/roundingincrement-non-integer.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instant = new \Calendrics\Spec\Instant(1_000_000_000_000_000_005);
$result = $instant->round((object) ['smallestUnit' => 'nanosecond', 'roundingIncrement' => 2.5, 'roundingMode' => 'expand']);
Assert::sameValue($result->epochNanoseconds, 1_000_000_000_000_000_006, 'roundingIncrement 2.5 truncates to 2');
