<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/round/roundingincrement-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$instant = new \Calendrics\Spec\Instant(1_000_000_000_987_654_321);
TemporalHelpers::checkRoundingIncrementOptionWrongType(function ($roundingIncrement) use (&$instant) { return $instant->round(JsUndefined::strip(['smallestUnit' => 'second', 'roundingIncrement' => $roundingIncrement])); }, fn($result, $descr) => Assert::sameValue($result->epochNanoseconds, 1_000_000_001_000_000_000, $descr), fn($result, $descr) => Assert::sameValue($result->epochNanoseconds, 1_000_000_000_000_000_000, $descr));
