<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/round/roundingmode-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instant = new \Calendrics\Spec\Instant(1_000_000_000_123_987_500);
$explicit1 = $instant->round((object) ['smallestUnit' => 'microsecond']);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($explicit1), 1_000_000_000_123_988_000, 'default roundingMode is halfExpand');
$implicit1 = $instant->round((object) ['smallestUnit' => 'microsecond']);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($implicit1), 1_000_000_000_123_988_000, 'default roundingMode is halfExpand');
$explicit2 = $instant->round((object) ['smallestUnit' => 'millisecond']);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($explicit2), 1_000_000_000_124_000_000, 'default roundingMode is halfExpand');
$implicit2 = $instant->round((object) ['smallestUnit' => 'millisecond']);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($implicit2), 1_000_000_000_124_000_000, 'default roundingMode is halfExpand');
$explicit3 = $instant->round((object) ['smallestUnit' => 'second']);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($explicit3), 1_000_000_000_000_000_000, 'default roundingMode is halfExpand');
$implicit3 = $instant->round((object) ['smallestUnit' => 'second']);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($implicit3), 1_000_000_000_000_000_000, 'default roundingMode is halfExpand');
