<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/round/rounding-increments.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$inst = \Calendrics\Spec\Instant::from('1976-11-18T14:23:30.123456789Z');
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 4]), \Calendrics\Spec\Instant::from('1976-11-18T16:00:00Z'));
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'minute', 'roundingIncrement' => 15]), \Calendrics\Spec\Instant::from('1976-11-18T14:30:00Z'));
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'second', 'roundingIncrement' => 30]), \Calendrics\Spec\Instant::from('1976-11-18T14:23:30Z'));
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'millisecond', 'roundingIncrement' => 10]), \Calendrics\Spec\Instant::from('1976-11-18T14:23:30.12Z'));
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'microsecond', 'roundingIncrement' => 10]), \Calendrics\Spec\Instant::from('1976-11-18T14:23:30.12346Z'));
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'nanosecond', 'roundingIncrement' => 10]), \Calendrics\Spec\Instant::from('1976-11-18T14:23:30.12345679Z'));
$unitsAndIncrements = (object) JsUndefined::strip(['hour' => [1, 2, 4, 6, 8, 12, 24], 'minute' => [1, 5, 10, 20, 30, 40, 80, 120, 720, 1440], 'second' => [1, 5, 10, 20, 25, 30, 50, 100, 400, 86_400], 'millisecond' => [1, 5, 10, 20, 25, 30, 50, 100, 86_400_000], 'microsecond' => [1, 5, 10, 20, 25, 30, 50, 100], 'nanosecond' => [1, 5, 10, 20, 25, 30, 50, 100]]);
foreach ($unitsAndIncrements as $unit => $increments) {
foreach ($increments as $increment) {
$result = $inst->round((object) JsUndefined::strip(['smallestUnit' => $unit, 'roundingMode' => 'ceil', 'roundingIncrement' => $increment]));
Assert::sameValue($result instanceof \Calendrics\Spec\Instant, true, "{$unit} {$increment}");
}
}
