<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/round/round-to-days.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$inst = \Calendrics\Spec\Instant::from('1976-11-18T14:23:30.123456789Z');
$expected = \Calendrics\Spec\Instant::from('1976-11-19T00:00:00Z');
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 24]), $expected);
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'minute', 'roundingIncrement' => 1440]), $expected);
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'second', 'roundingIncrement' => 86_400]), $expected);
TemporalHelpers::assertInstantsEqual($inst->round((object) ['smallestUnit' => 'millisecond', 'roundingIncrement' => 86_400_000]), $expected);
