<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/round/throws-on-increments-that-do-not-divide-evenly.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$inst = new \Calendrics\Spec\Instant(0);
Assert::throws(\RangeException::class, function () use (&$inst) { return $inst->round((object) ['smallestUnit' => 'hour', 'roundingIncrement' => 7]); }, '');
Assert::throws(\RangeException::class, function () use (&$inst) { return $inst->round((object) ['smallestUnit' => 'minute', 'roundingIncrement' => 29]); }, '');
Assert::throws(\RangeException::class, function () use (&$inst) { return $inst->round((object) ['smallestUnit' => 'second', 'roundingIncrement' => 29]); }, '');
Assert::throws(\RangeException::class, function () use (&$inst) { return $inst->round((object) ['smallestUnit' => 'millisecond', 'roundingIncrement' => 29]); }, '');
Assert::throws(\RangeException::class, function () use (&$inst) { return $inst->round((object) ['smallestUnit' => 'microsecond', 'roundingIncrement' => 29]); }, '');
Assert::throws(\RangeException::class, function () use (&$inst) { return $inst->round((object) ['smallestUnit' => 'nanosecond', 'roundingIncrement' => 29]); }, '');
