<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/from/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$base = (object) ['era' => 'ad', 'month' => 5, 'day' => 2, 'calendar' => 'gregory'];
foreach ([INF, -INF] as $inf) {
foreach (['constrain', 'reject'] as $overflow) {
Assert::throws(\RangeException::class, function () use (&$base, &$inf, &$overflow) { return \Calendrics\Spec\PlainDate::from((object) JsUndefined::strip(array_merge((array) $base, ['eraYear' => $inf])), (object) JsUndefined::strip(['overflow' => $overflow])); }, "eraYear property cannot be {$inf} (overflow {$overflow}");
$calls = new \Calendrics\Tests\Test262\ObserverTrace();
$obj = TemporalHelpers::toPrimitiveObserver($calls, $inf, 'eraYear');
Assert::throws(\RangeException::class, function () use (&$base, &$obj, &$overflow) { return \Calendrics\Spec\PlainDate::from((object) JsUndefined::strip(array_merge((array) $base, ['eraYear' => $obj])), (object) JsUndefined::strip(['overflow' => $overflow])); }, '');
Assert::compareObserverTrace($calls, ['get eraYear.valueOf', 'call eraYear.valueOf'], 'it fails after fetching the primitive value');
}
}
