<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/prototype/with/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$instance = new \Calendrics\Spec\PlainMonthDay(5, 2);
foreach ([INF, -INF] as $inf) {
foreach (['constrain', 'reject'] as $overflow) {
Assert::throws(\RangeException::class, function () use (&$instance, &$inf, &$overflow) { return $instance->with(JsUndefined::strip(['day' => $inf]), JsUndefined::strip(['overflow' => $overflow])); }, "day property cannot be {$inf} (overflow {$overflow}");
$calls = new \Calendrics\Tests\Test262\ObserverTrace();
$obj = TemporalHelpers::toPrimitiveObserver($calls, $inf, 'day');
Assert::throws(\RangeException::class, function () use (&$instance, &$obj, &$overflow) { return $instance->with(JsUndefined::strip(['day' => $obj]), JsUndefined::strip(['overflow' => $overflow])); }, '');
Assert::compareObserverTrace($calls, ['get day.valueOf', 'call day.valueOf'], 'it fails after fetching the primitive value');
}
}
