<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/prototype/with/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expectedOpsForPrimitiveOptions = ['get fields.calendar', 'get fields.timeZone', 'get fields.day', 'get fields.day.valueOf', 'call fields.day.valueOf', 'get fields.month', 'get fields.month.valueOf', 'call fields.month.valueOf', 'get fields.monthCode', 'get fields.monthCode.toString', 'call fields.monthCode.toString', 'get fields.year', 'get fields.year.valueOf', 'call fields.year.valueOf'];
$expected = array_merge($expectedOpsForPrimitiveOptions, ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString']);
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$instance = new \Calendrics\Spec\PlainMonthDay(5, 2, 'iso8601');
$fields = TemporalHelpers::propertyBagObserver($actual, ['year' => 1.7, 'month' => 1.7, 'monthCode' => 'M01', 'day' => 1.7], 'fields');
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'constrain', 'extra' => 'property'], 'options');
$instance->with($fields, $options);
Assert::compareObserverTrace($actual, $expected, 'order of operations');
$actual->clear();
// JS-only (JS rejects non-object options via ToObject; PHP accepts null as "absent"): assert.throws(TypeError, () => instance.with(fields, null));
// JS-only (trace covers a call skipped above, so the tracker is empty here): assert.compareArray(actual, expectedOpsForPrimitiveOptions, "argument fields are read before TypeError is thrown for primitive options");
$actual->clear();
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
