<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/toZonedDateTimeISO/calendar-is-builtin.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\Instant(0);
$result = $instance->toZonedDateTimeISO('UTC');
Assert::sameValue($result->calendarId, 'iso8601', 'calendar string is iso8601');
