<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/withPlainTime/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$zdt = \Calendrics\Spec\ZonedDateTime::from('2015-12-07T03:24:30.000003500[-08:00]');
TemporalHelpers::assertZonedDateTimesEqual($zdt->withPlainTime((object) ['hour' => 10]), \Calendrics\Spec\ZonedDateTime::from('2015-12-07T10:00:00-08:00[-08:00]'));
$time = new \Calendrics\Spec\PlainTime(11, 22);
TemporalHelpers::assertZonedDateTimesEqual($zdt->withPlainTime($time), \Calendrics\Spec\ZonedDateTime::from('2015-12-07T11:22:00-08:00[-08:00]'));
TemporalHelpers::assertZonedDateTimesEqual($zdt->withPlainTime('12:34'), \Calendrics\Spec\ZonedDateTime::from('2015-12-07T12:34:00-08:00[-08:00]'));
