<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/constructor-full.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$datetime = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789, 'iso8601');
TemporalHelpers::assertPlainDateTime($datetime, 1976, 11, 'M11', 18, 15, 23, 30, 123, 456, 789, 'check instance (all arguments supplied)');
Assert::sameValue($datetime->calendarId, 'iso8601', 'calendar supplied in constructor can be extracted and is unchanged');
