<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::throws(\RangeException::class, fn() => new \Calendrics\Spec\PlainDateTime(-271_821, 4, 19, 0, 0, 0, 0, 0, 0), 'negative year out of bounds');
Assert::throws(\RangeException::class, fn() => new \Calendrics\Spec\PlainDateTime(275_760, 9, 14, 0, 0, 0, 0, 0, 0), 'positive year out of bounds');
