<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/timeZoneId/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\ZonedDateTime(0, 'Europe/Madrid', 'gregory');
Assert::sameValue($instance->timeZoneId, 'Europe/Madrid', '');
