<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/add/casts-argument.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$zdt = new \Calendrics\Spec\ZonedDateTime(-560_174_321_098_766, 'UTC');
$expected = new \Calendrics\Spec\ZonedDateTime(303_825_678_902_034, 'UTC');
TemporalHelpers::assertZonedDateTimesEqual($zdt->add('PT240H0.000000800S'), $expected);
