<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/add/overflow-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$datetime = new \Calendrics\Spec\ZonedDateTime(-1, 'UTC');
$duration = new \Calendrics\Spec\Duration(0, 2);
$explicit = $datetime->add($duration, []);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($explicit), 5_097_599_999_999_999, 'default overflow is constrain');
$implicit = $datetime->add($duration, []);
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($implicit), 5_097_599_999_999_999, 'default overflow is constrain');
$lambda = $datetime->add($duration, function () {  });
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read($lambda), 5_097_599_999_999_999, 'default overflow is constrain');
