<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/add/throw-when-intermediate-datetime-outside-valid-limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
// Folded (BigInt 8640000000000000000000 exceeds int64): nsMaxInstant
// Folded (BigInt -8640000000000000000000 exceeds int64): nsMinInstant
// Folded (BigInt -8640000000000000000000 exceeds int64): epochNs
$zdt = \Calendrics\Spec\ZonedDateTime::fromEpochParts(-8640000000000, 0, 'UTC');
Assert::throws(\RangeException::class, function () use (&$zdt) { return $zdt->add(JsUndefined::strip(['days' => -1])); }, '');
