<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/until/roundingmode-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$earlier = new \Calendrics\Spec\PlainYearMonth(2000, 1);
$later1 = new \Calendrics\Spec\PlainYearMonth(2005, 2);
$explicit1 = $earlier->until($later1, (object) ['smallestUnit' => 'year']);
TemporalHelpers::assertDuration($explicit1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'default roundingMode is trunc');
$implicit1 = $earlier->until($later1, (object) ['smallestUnit' => 'year']);
TemporalHelpers::assertDuration($implicit1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'default roundingMode is trunc');
$later2 = new \Calendrics\Spec\PlainYearMonth(2005, 12);
$explicit2 = $earlier->until($later2, (object) ['smallestUnit' => 'year']);
TemporalHelpers::assertDuration($explicit2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'default roundingMode is trunc');
$implicit2 = $earlier->until($later2, (object) ['smallestUnit' => 'year']);
TemporalHelpers::assertDuration($implicit2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'default roundingMode is trunc');
