<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/from/argument-string-fractional-precision.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$tests = JsUndefined::strip(['PT0.999999999H' => \Calendrics\Spec\Duration::from(['minutes' => 59, 'seconds' => 59, 'milliseconds' => 999, 'microseconds' => 996, 'nanoseconds' => 400]), 'PT0.000000011H' => \Calendrics\Spec\Duration::from(['minutes' => 0, 'seconds' => 0, 'milliseconds' => 0, 'microseconds' => 39, 'nanoseconds' => 600]), 'PT0.999999999M' => \Calendrics\Spec\Duration::from(['seconds' => 59, 'milliseconds' => 999, 'microseconds' => 999, 'nanoseconds' => 940]), 'PT0.000000011M' => \Calendrics\Spec\Duration::from(['seconds' => 0, 'milliseconds' => 0, 'microseconds' => 0, 'nanoseconds' => 660]), 'PT0.999999999S' => \Calendrics\Spec\Duration::from(['milliseconds' => 999, 'microseconds' => 999, 'nanoseconds' => 999]), 'PT0.000000011S' => \Calendrics\Spec\Duration::from(['milliseconds' => 0, 'microseconds' => 0, 'nanoseconds' => 11])]);
foreach ($tests as $str => $expected) {
$actual = \Calendrics\Spec\Duration::from($str);
TemporalHelpers::assertDurationsEqual($actual, $expected, $str);
}
