<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/prototype/toPlainDate/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$instance = new \Calendrics\Spec\PlainMonthDay(5, 2, 'gregory');
foreach ([INF, -INF] as $inf) {
Assert::throws(\RangeException::class, function () use (&$instance, &$inf) { return $instance->toPlainDate(JsUndefined::strip(['era' => 'ad', 'eraYear' => $inf])); }, "eraYear property cannot be {$inf}");
$calls = new \Calendrics\Tests\Test262\ObserverTrace();
$obj = TemporalHelpers::toPrimitiveObserver($calls, $inf, 'eraYear');
Assert::throws(\RangeException::class, function () use (&$instance, &$obj) { return $instance->toPlainDate(JsUndefined::strip(['era' => 'ad', 'eraYear' => $obj])); }, '');
Assert::compareObserverTrace($calls, ['get eraYear.valueOf', 'call eraYear.valueOf'], 'it fails after fetching the primitive value');
}
