<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/equals/argument-plaindatetime.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkPlainDateTimeConversionFastPath(function ($datetime) use (&$date) { $date = new \Calendrics\Spec\PlainDate(2000, 5, 2); Assert::assertTrue($date->equals($datetime), ''); });
