<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/prototype/toLocaleString/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$findPart = function ($parts, $expectedType) use (&$__dp0) {
return \Calendrics\Tests\Test262\Js::arrayFind($parts, function ($__dp0) use (&$expectedType) { $type = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'type'); return $type === $expectedType; })->value;
};
$calendar = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US')->resolvedOptions()->calendarId;
$monthday = \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['monthCode' => 'M11', 'day' => 18, 'calendar' => $calendar]));
$dtfNY = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US', (object) ['timeZone' => 'America/New_York']);
Assert::sameValue($monthday->toLocaleString('en-US', (object) ['timeZone' => 'America/New_York']), $dtfNY->format($monthday), '');
$partsNY = $dtfNY->formatToParts($monthday);
$monthPartNY = $findPart($partsNY, 'month');
$dayPartNY = $findPart($partsNY, 'day');
$resultNY = $monthday->toLocaleString('en-US', (object) ['timeZone' => 'America/New_York']);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($resultNY, $monthPartNY), 'en-US locale string has a month part');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($resultNY, $dayPartNY), 'en-US locale string has a day part');
$dtfVienna = new \Calendrics\Tests\Test262\IntlDateTimeFormat('de-AT', (object) JsUndefined::strip(['timeZone' => 'Europe/Vienna', 'calendar' => $calendar]));
Assert::sameValue($monthday->toLocaleString('de-AT', (object) JsUndefined::strip(['timeZone' => 'Europe/Vienna', 'calendar' => $calendar])), $dtfVienna->format($monthday), '');
$partsVienna = $dtfVienna->formatToParts($monthday);
$monthPartVienna = $findPart($partsVienna, 'month');
$dayPartVienna = $findPart($partsVienna, 'day');
$resultVienna = $monthday->toLocaleString('de-AT', (object) JsUndefined::strip(['timeZone' => 'Europe/Vienna', 'calendar' => $calendar]));
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($resultVienna, $monthPartVienna), 'de-AT locale string has a month part');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($resultVienna, $dayPartVienna), 'de-AT locale string has a day part');
