<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/prototype/toLocaleString/dateStyle-timeStyle-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$defaultFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en');
$__destruct__ = $defaultFormatter->resolvedOptions();
$calendar = $__destruct__->calendar;
$monthday = new \Calendrics\Spec\PlainMonthDay(5, 2, $calendar);
$expected = $defaultFormatter->format($monthday);
$actual = $monthday->toLocaleString('en', (object) []);
Assert::sameValue($actual, $expected, 'dateStyle undefined is the same as being absent');
