<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/prototype/toLocaleString/locales-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$defaultFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat([], []);
$__destruct__ = $defaultFormatter->resolvedOptions();
$calendar = $__destruct__->calendar;
$monthday = new \Calendrics\Spec\PlainMonthDay(5, 2, $calendar);
$expected = $defaultFormatter->format($monthday);
$actualExplicit = $monthday->toLocaleString();
Assert::sameValue($actualExplicit, $expected, 'default locale is determined by Intl.DateTimeFormat');
$actualImplicit = $monthday->toLocaleString();
Assert::sameValue($actualImplicit, $expected, 'default locale is determined by Intl.DateTimeFormat');
