<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/prototype/toLocaleString/lone-options-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$epochMs = 1_735_213_600_321;
$legacyDate = new \Temporal\Tests\Test262\JsDate($epochMs);
$plainMonthDay = new \Temporal\Spec\PlainMonthDay(12, 26);
foreach ([(object) ['month' => 'long'], (object) ['day' => 'numeric']] as $options) {
$plainMonthDayResult = $plainMonthDay->toLocaleString('en-u-ca-iso8601', $options);
$legacyDateResult = $legacyDate->toLocaleString('en-u-ca-iso8601', $options);
Assert::sameValue($plainMonthDayResult, $legacyDateResult, "PlainMonthDay.toLocaleString should format lone option " . (json_encode($options)) . "");
}
