<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/prototype/toLocaleString/options-conflict.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$conflictingOptions = ['month', 'day'];
$calendar = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en')->resolvedOptions()->calendarId;
$md = new \Calendrics\Spec\PlainMonthDay(4, 17, $calendar);
$md->toLocaleString('en', (object) ['dateStyle' => 'short']);
Assert::throws(\TypeError::class, function () use (&$md) { $md->toLocaleString('en', (object) ['timeStyle' => 'short']); }, 'timeStyle conflicts with PlainMonthDay');
foreach ($conflictingOptions as $option) {
Assert::throws(\TypeError::class, function () use (&$md, &$option) { $md->toLocaleString('en', (object) [$option => 'numeric', 'dateStyle' => 'short']); }, "{$option} conflicts with dateStyle");
$md->toLocaleString('en', (object) [$option => 'numeric']);
$md->toLocaleString('en', (object) [$option => 'numeric']);
}
