<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/from/argument-zoneddatetime.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkToTemporalInstantFastPath(function ($datetime) use (&$result) { $result = \Calendrics\Spec\Instant::from($datetime); Assert::sameValue($result->epochNanoseconds, $result->epochNanoseconds, 'epochNanoseconds result'); });
