<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/argument-propertybag-calendar-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$calendar = 'iso8601';
$arg = JsUndefined::strip(['year' => 1976, 'monthCode' => 'M11', 'day' => 18, 'calendar' => $calendar]);
$result = \Calendrics\Spec\PlainDateTime::from($arg);
TemporalHelpers::assertPlainDateTime($result, 1976, 11, 'M11', 18, 0, 0, 0, 0, 0, 0, "Calendar created from string \"{$calendar}\"");
Assert::sameValue($result->calendarId, 'iso8601', 'calendar string is iso8601');
