<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/argument-string-optional-data.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::assertPlainDateTime(\Calendrics\Spec\PlainDateTime::from('1976-11-18T15:23:30+00'), 1976, 11, 'M11', 18, 15, 23, 30, 0, 0, 0, 'optional parts (no minute after offset)');
TemporalHelpers::assertPlainDateTime(\Calendrics\Spec\PlainDateTime::from('1976-11-18T15'), 1976, 11, 'M11', 18, 15, 0, 0, 0, 0, 0, 'optional parts (no minute in time part)');
TemporalHelpers::assertPlainDateTime(\Calendrics\Spec\PlainDateTime::from('1976-11-18'), 1976, 11, 'M11', 18, 0, 0, 0, 0, 0, 0, 'optional parts (no time part)');
