<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/argument-plaindatetime.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$orig = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 15, 23, 20, 123, 456, 789);
$result = \Calendrics\Spec\PlainDateTime::from($orig);
TemporalHelpers::assertPlainDateTime($result, 1976, 11, 'M11', 18, 15, 23, 20, 123, 456, 789, 'PlainDateTime is copied');
Assert::sameValue($result->calendarId, $orig->calendarId, 'Calendar is copied');
Assert::notSameValue($result, $orig, 'When a PlainDateTime is given, the returned value is not the original PlainDateTime');
