<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/argument-string-comma-decimal-separator.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::assertPlainDateTime(\Calendrics\Spec\PlainDateTime::from('1976-11-18T15:23:30,12'), 1976, 11, 'M11', 18, 15, 23, 30, 120, 0, 0, 'comma decimal separator');
