<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/overflow-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$validValues = [new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 12), '2000-05-02T12:00'];
foreach ($validValues as $value) {
$explicit = \Calendrics\Spec\PlainDateTime::from($value, []);
TemporalHelpers::assertPlainDateTime($explicit, 2000, 5, 'M05', 2, 12, 0, 0, 0, 0, 0, 'overflow is ignored');
$implicit = \Calendrics\Spec\PlainDateTime::from($value, []);
TemporalHelpers::assertPlainDateTime($implicit, 2000, 5, 'M05', 2, 12, 0, 0, 0, 0, 0, 'overflow is ignored');
$lambda = \Calendrics\Spec\PlainDateTime::from($value, function () {  });
TemporalHelpers::assertPlainDateTime($lambda, 2000, 5, 'M05', 2, 12, 0, 0, 0, 0, 0, 'overflow is ignored');
}
$propertyBag = ['year' => 2000, 'month' => 13, 'day' => 34, 'hour' => 12];
$explicit = \Calendrics\Spec\PlainDateTime::from($propertyBag, []);
TemporalHelpers::assertPlainDateTime($explicit, 2000, 12, 'M12', 31, 12, 0, 0, 0, 0, 0, 'default overflow is constrain');
$implicit = \Calendrics\Spec\PlainDateTime::from($propertyBag, []);
TemporalHelpers::assertPlainDateTime($implicit, 2000, 12, 'M12', 31, 12, 0, 0, 0, 0, 0, 'default overflow is constrain');
$lambda = \Calendrics\Spec\PlainDateTime::from($propertyBag, function () {  });
TemporalHelpers::assertPlainDateTime($lambda, 2000, 12, 'M12', 31, 12, 0, 0, 0, 0, 0, 'default overflow is constrain');
