<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/overflow-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$validValues = [new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 12), '2000-05-02T12:00'];
foreach ($validValues as $value) {
TemporalHelpers::checkStringOptionWrongType('overflow', 'constrain', function ($overflow) use (&$value) { return \Calendrics\Spec\PlainDateTime::from($value, (object) JsUndefined::strip(['overflow' => $overflow])); }, fn($result, $descr) => TemporalHelpers::assertPlainDateTime($result, 2000, 5, 'M05', 2, 12, 0, 0, 0, 0, 0, $descr));
}
$propertyBag = (object) ['year' => 2000, 'month' => 5, 'day' => 2, 'hour' => 12];
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Calendrics\Spec\PlainDateTime::from($propertyBag, (object) ['overflow' => null]); }, 'null');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Calendrics\Spec\PlainDateTime::from($propertyBag, (object) ['overflow' => true]); }, 'true');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Calendrics\Spec\PlainDateTime::from($propertyBag, (object) ['overflow' => false]); }, 'false');
Assert::throws(\TypeError::class, function () use (&$propertyBag) { return \Calendrics\Spec\PlainDateTime::from($propertyBag, (object) JsUndefined::strip(['overflow' => \Calendrics\Tests\Test262\JsSymbol::singleton()])); }, 'symbol');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Calendrics\Spec\PlainDateTime::from($propertyBag, (object) ['overflow' => 2]); }, 'number');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Calendrics\Spec\PlainDateTime::from($propertyBag, (object) ['overflow' => 2]); }, 'bigint');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Calendrics\Spec\PlainDateTime::from($propertyBag, (object) JsUndefined::strip(['overflow' => (object) []])); }, 'plain object');
$expected = ['get overflow.toString', 'call overflow.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$observer = TemporalHelpers::toPrimitiveObserver($actual, 'constrain', 'overflow');
$result = \Calendrics\Spec\PlainDateTime::from($propertyBag, (object) JsUndefined::strip(['overflow' => $observer]));
TemporalHelpers::assertPlainDateTime($result, 2000, 5, 'M05', 2, 12, 0, 0, 0, 0, 0, 'object with toString');
Assert::compareObserverTrace($actual, $expected, 'order of operations');
