<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/toLocaleString/return-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instant = new \Calendrics\Spec\Instant(957_270_896_987_650_000);
Assert::sameValue(is_string($instant->toLocaleString('en', (object) ['dateStyle' => 'short'])), true, '');
Assert::sameValue(is_string($instant->toLocaleString('en', (object) ['timeStyle' => 'short'])), true, '');
