<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/fromEpochNanoseconds/argument.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::throws(\TypeError::class, fn() => \Calendrics\Spec\Instant::fromEpochNanoseconds(), 'undefined');
Assert::throws(\TypeError::class, fn() => \Calendrics\Spec\Instant::fromEpochNanoseconds(), 'undefined');
Assert::throws(\TypeError::class, fn() => \Calendrics\Spec\Instant::fromEpochNanoseconds(null), 'null');
Assert::throws(\TypeError::class, fn() => \Calendrics\Spec\Instant::fromEpochNanoseconds(42.0), 'number');
Assert::throws(\TypeError::class, fn() => \Calendrics\Spec\Instant::fromEpochNanoseconds(\Calendrics\Tests\Test262\JsSymbol::singleton()), 'symbol');
