<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/fromEpochNanoseconds/limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
// Folded (BigInt 8640000000000000000000 exceeds int64): limit
Assert::throws(\RangeException::class, fn() => \Temporal\Spec\Instant::fromEpochParts(-8640000000001, 999999999), '');
Assert::throws(\RangeException::class, fn() => \Temporal\Spec\Instant::fromEpochParts(8640000000000, 1), '');
TemporalHelpers::assertInstantsEqual(\Temporal\Spec\Instant::fromEpochParts(-8640000000000, 0), \Temporal\Spec\Instant::from('-271821-04-20T00:00:00Z'));
TemporalHelpers::assertInstantsEqual(\Temporal\Spec\Instant::fromEpochParts(8640000000000, 0), \Temporal\Spec\Instant::from('+275760-09-13T00:00:00Z'));
