<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/with/calendar-temporal-object-throws.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$datetime = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789);
$values = [\Calendrics\Spec\PlainDate::from('2022-04-12'), \Calendrics\Spec\PlainDateTime::from('2022-04-12T15:19:45'), \Calendrics\Spec\PlainMonthDay::from('04-12'), \Calendrics\Spec\PlainTime::from('15:19:45'), \Calendrics\Spec\PlainYearMonth::from('2022-04'), \Calendrics\Spec\ZonedDateTime::from('2022-04-12T15:19:45[UTC]'), \Calendrics\Spec\Now::plainDateTimeISO(), \Calendrics\Spec\Now::plainDateISO(), \Calendrics\Spec\Now::plainTimeISO()];
foreach ($values as $value) {
// JS-only (JS-only observability getter on Temporal arg (PHP reads internal slot directly, getter never fires)): Object.defineProperty(value, "calendar", { get() { throw new Test262Error("should not get calendar property") } });
// JS-only (JS-only observability getter on Temporal arg (PHP reads internal slot directly, getter never fires)): Object.defineProperty(value, "timeZone", { get() { throw new Test262Error("should not get timeZone property") } });
Assert::throws(\TypeError::class, function () use (&$datetime, &$value) { return $datetime->with($value); }, 'throws with temporal object');
}
