<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/with/overflow-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$datetime = new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 12);
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['minute' => 45], (object) ['overflow' => null]); }, 'null');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['minute' => 45], (object) ['overflow' => true]); }, 'true');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['minute' => 45], (object) ['overflow' => false]); }, 'false');
Assert::throws(\TypeError::class, function () use (&$datetime) { return $datetime->with((object) ['minute' => 45], (object) JsUndefined::strip(['overflow' => \Calendrics\Tests\Test262\JsSymbol::singleton()])); }, 'symbol');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['minute' => 45], (object) ['overflow' => 2]); }, 'number');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['minute' => 45], (object) ['overflow' => 2]); }, 'bigint');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['minute' => 45], (object) JsUndefined::strip(['overflow' => (object) []])); }, 'plain object');
$expected = ['get overflow.toString', 'call overflow.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$observer = TemporalHelpers::toPrimitiveObserver($actual, 'constrain', 'overflow');
$result = $datetime->with((object) ['minute' => 45], (object) JsUndefined::strip(['overflow' => $observer]));
TemporalHelpers::assertPlainDateTime($result, 2000, 5, 'M05', 2, 12, 45, 0, 0, 0, 0, 'object with toString');
Assert::compareObserverTrace($actual, $expected, 'order of operations');
