<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/toString/smallestunit-plurals-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$datetime = new \Calendrics\Spec\ZonedDateTime(1_000_000_000_123_456_789, 'UTC');
$validUnits = ['minute', 'second', 'millisecond', 'microsecond', 'nanosecond'];
TemporalHelpers::checkPluralUnitsAccepted(function ($smallestUnit) use (&$datetime) { return $datetime->toString((object) JsUndefined::strip(['smallestUnit' => $smallestUnit])); }, $validUnits);
