<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/toString/balance-subseconds.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$pos = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, 0, 999, 999_999, 999_999_999);
Assert::sameValue((string) ($pos), 'PT2.998998999S', '');
$neg = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, 0, -999, -999_999, -999_999_999);
Assert::sameValue((string) ($neg), '-PT2.998998999S', '');
