<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/toString/fractionalseconddigits-nan.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$duration = new \Calendrics\Spec\Duration(1, 2, 3, 4, 5, 6, 7, 987, 650, 0);
Assert::throws(\RangeException::class, function () use (&$duration) { return $duration->toString(JsUndefined::strip(['fractionalSecondDigits' => NAN])); }, '');
