<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/toString/prop-desc.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::sameValue('function', 'function', '`typeof Duration.prototype.toString` is `function`');
Assert::methodExists('\Calendrics\Spec\Duration', 'toString');
