<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/with/copy-properties-not-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$plainYearMonth = new \Calendrics\Spec\PlainYearMonth(2001, 9);
TemporalHelpers::assertPlainYearMonth($plainYearMonth->with(['month' => 11]), 2001, 11, 'M11', 'only the properties that are present and defined in the plain object are copied');
