<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/with/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['overflow' => 'constrain'], 'options');
$instance = new \Calendrics\Spec\PlainYearMonth(2025, 7);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->with((object) ['monthCode' => 'M08L'], $options); }, 'exception thrown when month code incorrect for calendar');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
