<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/with/yearmonthlike-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$plainYearMonth = new \Calendrics\Spec\PlainYearMonth(1, 1);
$tests = [[JsUndefined::singleton()], [null], [true], ['2019-05-17'], ['2019-05-17T12:34'], ['2019-05-17T12:34Z'], ['18:05:42.577'], ['42'], [\Calendrics\Tests\Test262\JsSymbol::singleton(), 'symbol'], [42, 'number'], [42, 'bigint'], [\Calendrics\Spec\PlainDate::from('2019-05-17'), 'PlainDate'], [\Calendrics\Spec\PlainDateTime::from('2019-05-17T12:34'), 'PlainDateTime'], [\Calendrics\Spec\PlainMonthDay::from('2019-05-17'), 'PlainMonthDay'], [\Calendrics\Spec\PlainTime::from('12:34'), 'PlainTime'], [\Calendrics\Spec\PlainYearMonth::from('2019-05-17'), 'PlainYearMonth'], [\Calendrics\Spec\ZonedDateTime::from('2019-05-17T12:34Z[UTC]'), 'ZonedDateTime'], [(object) ['year' => 2021, 'calendar' => 'iso8601'], 'calendar'], [(object) ['year' => 2021, 'timeZone' => 'UTC'], 'timeZone'], [(object) [], 'empty object'], [(object) ['months' => 12], 'only plural property']];
foreach ($tests as $__entry__) {
[$value, $message] = array_pad($__entry__, 2, null);
if ($value === null) { continue; }
$message = $message ?? \Calendrics\Tests\Test262\Js::toString($value);
Assert::throws(\TypeError::class, function () use (&$plainYearMonth, &$value) { return $plainYearMonth->with($value); }, $message);
}
