<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/compare/argument-string-too-many-decimals.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$invalidStrings = ['1970-01-01T00:00:00.1234567891Z', '1970-01-01T00:00:00.1234567890Z', '1970-01-01T00+00:00:00.1234567891', '1970-01-01T00+00:00:00.1234567890'];
$epoch = new \Calendrics\Spec\Instant(0);
foreach ($invalidStrings as $arg) {
Assert::throws(\RangeException::class, function () use (&$arg, &$epoch) { \Calendrics\Spec\Instant::compare($arg, $epoch); }, 'no more than 9 decimal places are allowed (first arg)');
Assert::throws(\RangeException::class, function () use (&$epoch, &$arg) { \Calendrics\Spec\Instant::compare($epoch, $arg); }, 'no more than 9 decimal places are allowed (second arg)');
}
