<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/compare/exhaustive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::sameValue(\Calendrics\Spec\Instant::compare(new \Calendrics\Spec\Instant(1_000_000_000_000_000_000), new \Calendrics\Spec\Instant(500_000_000_000_000_000)), 1, '>');
Assert::sameValue(\Calendrics\Spec\Instant::compare(new \Calendrics\Spec\Instant(-1000), new \Calendrics\Spec\Instant(1000)), -1, '<');
Assert::sameValue(\Calendrics\Spec\Instant::compare(new \Calendrics\Spec\Instant(123_456_789), new \Calendrics\Spec\Instant(123_456_789)), 0, '=');
