<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/compare/instant-string-sub-minute-offset.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$epoch = new \Calendrics\Spec\Instant(0);
$str = '1970-01-01T00:19:32.37+00:19:32.37';
$result1 = \Calendrics\Spec\Instant::compare($str, $epoch);
Assert::sameValue($result1, 0, 'if present, sub-minute offset is accepted exactly (first argument)');
$result2 = \Calendrics\Spec\Instant::compare($epoch, $str);
Assert::sameValue($result2, 0, 'if present, sub-minute offset is accepted exactly (second argument)');
