<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/toLocaleString/resolved-time-zone.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$date = new \Calendrics\Spec\PlainDate(2021, 8, 4);
$result = $date->toLocaleString('en', ['timeZone' => 'Pacific/Apia']);
Assert::sameValue($result, '8/4/2021', '');
