<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/compare/disregards-calendar-if-exact-times-equal.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$arg1 = new \Calendrics\Spec\ZonedDateTime(1_572_342_398_271_986_102, '-07:00', 'iso8601');
$arg2 = new \Calendrics\Spec\ZonedDateTime(1_572_342_398_271_986_102, '-07:00', 'japanese');
Assert::sameValue(\Calendrics\Spec\ZonedDateTime::compare($arg1, $arg2), 0, '');
