<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/compare/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$other = new \Calendrics\Spec\ZonedDateTime(1_000_000_000_000_000_000, 'UTC', 'gregory');
$base = ['era' => 'ad', 'month' => 5, 'day' => 2, 'hour' => 15, 'timeZone' => 'UTC', 'calendar' => 'gregory'];
foreach ([INF, -INF] as $inf) {
Assert::throws(\RangeException::class, function () use (&$base, &$inf, &$other) { return \Calendrics\Spec\ZonedDateTime::compare(JsUndefined::strip(array_merge($base, ['eraYear' => $inf])), $other); }, "eraYear property cannot be {$inf}");
Assert::throws(\RangeException::class, function () use (&$other, &$base, &$inf) { return \Calendrics\Spec\ZonedDateTime::compare($other, JsUndefined::strip(array_merge($base, ['eraYear' => $inf]))); }, "eraYear property cannot be {$inf}");
$calls1 = new \Calendrics\Tests\Test262\ObserverTrace();
$obj1 = TemporalHelpers::toPrimitiveObserver($calls1, $inf, 'eraYear');
Assert::throws(\RangeException::class, function () use (&$base, &$obj1, &$other) { return \Calendrics\Spec\ZonedDateTime::compare(JsUndefined::strip(array_merge($base, ['eraYear' => $obj1])), $other); }, '');
Assert::compareObserverTrace($calls1, ['get eraYear.valueOf', 'call eraYear.valueOf'], 'it fails after fetching the primitive value');
$calls2 = new \Calendrics\Tests\Test262\ObserverTrace();
$obj2 = TemporalHelpers::toPrimitiveObserver($calls2, $inf, 'eraYear');
Assert::throws(\RangeException::class, function () use (&$other, &$base, &$obj2) { return \Calendrics\Spec\ZonedDateTime::compare($other, JsUndefined::strip(array_merge($base, ['eraYear' => $obj2]))); }, '');
Assert::compareObserverTrace($calls2, ['get eraYear.valueOf', 'call eraYear.valueOf'], 'it fails after fetching the primitive value');
}
