<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/add/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$dt = new \Calendrics\Spec\PlainDateTime(2025, 8, 22, 14, 1);
$blank = new \Calendrics\Spec\Duration();
$result = $dt->add($blank);
TemporalHelpers::assertPlainDateTime($result, 2025, 8, 'M08', 22, 14, 1, 0, 0, 0, 0, 'result is unchanged');
