<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/add/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'constrain'], 'options');
$instance = new \Calendrics\Spec\PlainDateTime(2025, 8, 31, 23, 59, 59);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->add(new \Calendrics\Spec\Duration(0, 0, 0, 104_249_991_374, 1), $options); }, 'RangeError thrown when time addition overflows days component');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
