<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/add/overflow-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$datetime = new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 12);
$duration = new \Calendrics\Spec\Duration(3, 3, 0, 3, 3);
TemporalHelpers::checkStringOptionWrongType('overflow', 'constrain', function ($overflow) use (&$datetime, &$duration) { return $datetime->add($duration, JsUndefined::strip(['overflow' => $overflow])); }, fn($result, $descr) => TemporalHelpers::assertPlainDateTime($result, 2003, 8, 'M08', 5, 15, 0, 0, 0, 0, 0, $descr));
