<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/add/overflow-adding-months-to-max-year.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$maxYear = new \Calendrics\Spec\PlainDateTime(275_760, 1, 1);
$duration = new \Calendrics\Spec\Duration(0, 5432, 5432, 0, 0, 0, 0, 0, 0, 0);
Assert::throws(\RangeException::class, function () use (&$maxYear, &$duration) { return $maxYear->add($duration); }, '');
$minYear = new \Calendrics\Spec\PlainDateTime(-271_821, 4, 19, 0, 0, 0, 0, 0, 1);
Assert::throws(\RangeException::class, function () use (&$minYear, &$duration) { return $minYear->add($duration->negated()); }, '');
