<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/add/throws-if-duration-days-too-large.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$secondsPerDay = 24 * 60 * 60;
$maxSeconds = 2 ** 53 - 1;
$maxDays = (int) ($maxSeconds / $secondsPerDay);
$maxHours = (int) (fmod(num1: $maxSeconds / $secondsPerDay, num2: 1) * 24);
$d = new \Calendrics\Spec\Duration(0, 0, 0, $maxDays, $maxHours);
$pdt = new \Calendrics\Spec\PlainDateTime(1970, 1, 1, 24 - $maxHours);
Assert::throws(\RangeException::class, function () use (&$pdt, &$d) { return $pdt->add($d); }, '');
