<?php

declare(strict_types=1);

// Source: tests/Test262/data/Now/instant/return-value-value.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$nowBefore = \Calendrics\Tests\Test262\Js::dateNow();
$seconds = (float) (intdiv(\Calendrics\Spec\Now::instant()->epochNanoseconds, 1_000_000));
$nowAfter = \Calendrics\Tests\Test262\Js::dateNow();
Assert::assertTrue($seconds >= $nowBefore, 'The result of evaluating (seconds >= nowBefore) is expected to be true');
Assert::assertTrue($seconds <= $nowAfter, 'The result of evaluating (seconds <= nowAfter) is expected to be true');
