<?php

declare(strict_types=1);

// Source: tests/Test262/data/Now/instant/return-value-prototype.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::assertTrue(\Calendrics\Spec\Now::instant() instanceof \Calendrics\Spec\Instant, 'Object.getPrototypeOf(Temporal.Now.instant()) returns Temporal.Instant.prototype');
