<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/toString/timezone-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\Instant(0);
$result1 = $instance->toString(['timeZone' => 'UTC']);
Assert::sameValue(\Calendrics\Tests\Test262\Js::slice($result1, -6), '+00:00', 'Time zone created from string \'UTC\'');
$result2 = $instance->toString(['timeZone' => '-01:30']);
Assert::sameValue(\Calendrics\Tests\Test262\Js::slice($result2, -6), '-01:30', 'Time zone created from string \'-01:30\'');
