<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRange/fails-on-distinct-temporal-types.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$us = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US');
$instances = (object) JsUndefined::strip(['date' => new \Calendrics\Tests\Test262\JsDate(1_580_527_800_000), 'instant' => new \Calendrics\Spec\Instant(0), 'plaindate' => new \Calendrics\Spec\PlainDate(2000, 5, 2), 'plaindatetime' => new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 12, 34, 56, 987, 654, 321), 'plainmonthday' => new \Calendrics\Spec\PlainMonthDay(5, 2), 'plaintime' => new \Calendrics\Spec\PlainTime(13, 37), 'plainyearmonth' => new \Calendrics\Spec\PlainYearMonth(2019, 6), 'zoneddatetime' => new \Calendrics\Spec\ZonedDateTime(0, 'America/Kentucky/Louisville')]);
foreach ($instances as $typeName => $instance) {
foreach ($instances as $anotherTypeName => $anotherInstance) {
if ($typeName !== $anotherTypeName) {
Assert::throws(\TypeError::class, function () use (&$us, &$instance, &$anotherInstance) { $us->formatRange($instance, $anotherInstance); }, 'formatRange: bad arguments (' . $typeName . ' and ' . $anotherTypeName . ')');
}
}
}
