<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-no-time-clip-weekday.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', ['weekday' => 'long', 'year' => 'numeric', 'month' => 'long', 'day' => 'numeric', 'calendar' => 'iso8601']);
$weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
$minDate = new \Calendrics\Spec\PlainDate(-271_821, 4, 19);
$maxDate = new \Calendrics\Spec\PlainDate(275_760, 9, 13);
$result = $dtf->formatRange($minDate, $maxDate);
$hasWeekday = \Calendrics\Tests\Test262\Js::arraySome($weekdays, function ($d) use (&$result) { return \Calendrics\Tests\Test262\Js::includes($result, $d); });
Assert::assertTrue($hasWeekday, 'formatRange with extreme dates should include weekday names, got: ' . $result);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '19'), 'formatRange result includes min day 19, got: ' . $result);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($result, '13'), 'formatRange result includes max day 13, got: ' . $result);
