<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-not-overlapping-options.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$sampleEpochMs = 1_726_773_817_847;
$sampleEpochNs = 1_726_773_817_847_000_000;
$legacyDate = new \Calendrics\Tests\Test262\JsDate($sampleEpochMs);
$instant = new \Calendrics\Spec\Instant($sampleEpochNs);
$plainDateTime = new \Calendrics\Spec\PlainDateTime(2024, 9, 19, 12, 23, 37, 847);
$plainDate = new \Calendrics\Spec\PlainDate(2024, 9, 19);
$plainYearMonth = new \Calendrics\Spec\PlainYearMonth(2024, 9);
$plainMonthDay = new \Calendrics\Spec\PlainMonthDay(9, 19);
$plainTime = new \Calendrics\Spec\PlainTime(12, 23, 37, 847);
$dateStyleFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['dateStyle' => 'short', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$dateStyleResult = $dateStyleFormatter->formatRange($legacyDate, $legacyDate);
Assert::sameValue($dateStyleFormatter->formatRange($instant, $instant), $dateStyleResult, 'Instant with dateStyle');
Assert::sameValue($dateStyleFormatter->formatRange($plainDateTime, $plainDateTime), $dateStyleResult, 'PlainDateTime with dateStyle');
Assert::sameValue($dateStyleFormatter->formatRange($plainDate, $plainDate), $dateStyleResult, 'PlainDate with dateStyle');
Assert::notSameValue($dateStyleFormatter->formatRange($plainYearMonth, $plainYearMonth), $dateStyleResult, 'PlainYearMonth with dateStyle should not throw but day is omitted');
Assert::notSameValue($dateStyleFormatter->formatRange($plainMonthDay, $plainMonthDay), $dateStyleResult, 'PlainMonthDay with dateStyle should not throw but year is omitted');
Assert::throws(\TypeError::class, function () use (&$dateStyleFormatter, &$plainTime) { return $dateStyleFormatter->formatRange($plainTime, $plainTime); }, 'no overlap between dateStyle and PlainTime');
$yearFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['year' => 'numeric', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$yearResult = $yearFormatter->formatRange($legacyDate, $legacyDate);
Assert::sameValue($yearFormatter->formatRange($instant, $instant), $yearResult, 'Instant with year');
Assert::sameValue($yearFormatter->formatRange($plainDateTime, $plainDateTime), $yearResult, 'PlainDateTime with year');
Assert::sameValue($yearFormatter->formatRange($plainDate, $plainDate), $yearResult, 'PlainDate with year');
Assert::sameValue($yearFormatter->formatRange($plainYearMonth, $plainYearMonth), $yearResult, 'PlainYearMonth with year');
Assert::throws(\TypeError::class, function () use (&$yearFormatter, &$plainMonthDay) { return $yearFormatter->formatRange($plainMonthDay, $plainMonthDay); }, 'no overlap between year and PlainMonthDay');
Assert::throws(\TypeError::class, function () use (&$yearFormatter, &$plainTime) { return $yearFormatter->formatRange($plainTime, $plainTime); }, 'no overlap between year and PlainTime');
$dayFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['day' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$dayResult = $dayFormatter->formatRange($legacyDate, $legacyDate);
Assert::sameValue($dayFormatter->formatRange($instant, $instant), $dayResult, 'Instant with day');
Assert::sameValue($dayFormatter->formatRange($plainDateTime, $plainDateTime), $dayResult, 'PlainDateTime with day');
Assert::sameValue($dayFormatter->formatRange($plainDate, $plainDate), $dayResult, 'PlainDate with day');
Assert::throws(\TypeError::class, function () use (&$dayFormatter, &$plainYearMonth) { return $dayFormatter->formatRange($plainYearMonth, $plainYearMonth); }, 'no overlap between day and PlainYearMonth');
Assert::sameValue($dayFormatter->formatRange($plainMonthDay, $plainMonthDay), $dayResult, 'PlainMonthDay with day');
Assert::throws(\TypeError::class, function () use (&$dayFormatter, &$plainTime) { return $dayFormatter->formatRange($plainTime, $plainTime); }, 'no overlap between day and PlainTime');
$timeStyleFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['timeStyle' => 'long', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$timeStyleResult = $timeStyleFormatter->formatRange($legacyDate, $legacyDate);
Assert::sameValue($timeStyleFormatter->formatRange($instant, $instant), $timeStyleResult, 'Instant with timeStyle');
$timeStylePlainDateTimeResult = $timeStyleFormatter->formatRange($plainDateTime, $plainDateTime);
Assert::notSameValue($timeStylePlainDateTimeResult, $timeStyleResult, 'PlainDateTime with timeStyle should not throw but time zone is omitted');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainDate) { return $timeStyleFormatter->formatRange($plainDate, $plainDate); }, 'no overlap between PlainDate and timeStyle');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainYearMonth) { return $timeStyleFormatter->formatRange($plainYearMonth, $plainYearMonth); }, 'no overlap between PlainYearMonth and timeStyle');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainMonthDay) { return $timeStyleFormatter->formatRange($plainMonthDay, $plainMonthDay); }, 'no overlap between PlainMonthDay and timeStyle');
Assert::sameValue($timeStyleFormatter->formatRange($plainTime, $plainTime), $timeStylePlainDateTimeResult, 'PlainTime with timeStyle should be the same as PlainDateTime');
$hourFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['hour' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$hourResult = $hourFormatter->formatRange($legacyDate, $legacyDate);
Assert::sameValue($hourFormatter->formatRange($instant, $instant), $hourResult, 'Instant with hour');
Assert::sameValue($hourFormatter->formatRange($plainDateTime, $plainDateTime), $hourResult, 'PlainDateTime with hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainDate) { return $hourFormatter->formatRange($plainDate, $plainDate); }, 'no overlap between PlainDate and hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainYearMonth) { return $hourFormatter->formatRange($plainYearMonth, $plainYearMonth); }, 'no overlap between PlainYearMonth and hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainMonthDay) { return $hourFormatter->formatRange($plainMonthDay, $plainMonthDay); }, 'no overlap between PlainMonthDay and hour');
Assert::sameValue($hourFormatter->formatRange($plainTime, $plainTime), $hourResult, 'PlainTime with hour');
$monthFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['month' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$monthResult = $monthFormatter->formatRange($legacyDate, $legacyDate);
$monthHourFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['month' => '2-digit', 'hour' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$monthHourResult = $monthHourFormatter->formatRange($legacyDate, $legacyDate);
Assert::sameValue($monthHourFormatter->formatRange($instant, $instant), $monthHourResult, 'Instant with month+hour');
Assert::sameValue($monthHourFormatter->formatRange($plainDateTime, $plainDateTime), $monthHourResult, 'PlainDateTime with month+hour');
Assert::sameValue($monthHourFormatter->formatRange($plainDate, $plainDate), $monthResult, 'PlainDate with month+hour behaves the same as month');
Assert::sameValue($monthHourFormatter->formatRange($plainYearMonth, $plainYearMonth), $monthResult, 'PlainYearMonth with month+hour behaves the same as month');
Assert::sameValue($monthHourFormatter->formatRange($plainMonthDay, $plainMonthDay), $monthResult, 'PlainMonthDay with month+hour behaves the same as month');
Assert::sameValue($monthHourFormatter->formatRange($plainTime, $plainTime), $hourResult, 'PlainTime with month+hour behaves the same as hour');
