<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-ignore-timezone.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$datetime_apia = '2011-12-30T12:00:00';
$datetime_los_angeles = '2026-03-08T02:00:00';
$pdt_apia = \Calendrics\Spec\PlainDateTime::from($datetime_apia);
$pdt_los_angeles = \Calendrics\Spec\PlainDateTime::from($datetime_los_angeles);
$pd_apia = \Calendrics\Spec\PlainDate::from($datetime_apia);
$pd_los_angeles = \Calendrics\Spec\PlainDate::from($datetime_los_angeles);
$pt_apia = \Calendrics\Spec\PlainTime::from($datetime_apia);
$pt_los_angeles = \Calendrics\Spec\PlainTime::from($datetime_los_angeles);
$dtf_apia = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US', (object) ['dateStyle' => 'short', 'timeStyle' => 'short', 'timeZone' => 'Pacific/Apia']);
$dtf_los_angeles = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US', (object) ['dateStyle' => 'short', 'timeStyle' => 'short', 'timeZone' => 'America/Los_Angeles']);
$pdt_apia_result = $dtf_apia->formatRange($pdt_apia, $pdt_los_angeles);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($pdt_apia_result, '30') && !\Calendrics\Tests\Test262\Js::includes($pdt_apia_result, '31'), 'day is calculated correctly, ignoring the Pacific/Apia timezone');
$pdt_los_angeles_result = $dtf_los_angeles->formatRange($pdt_apia, $pdt_los_angeles);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($pdt_los_angeles_result, '2:00') && !\Calendrics\Tests\Test262\Js::includes($pdt_los_angeles_result, '3:00'), 'hour is calculated correctly with the America/Los_Angeles timezone');
$pd_apia_result = $dtf_apia->formatRange($pd_apia, $pd_los_angeles);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($pd_apia_result, '30') && !\Calendrics\Tests\Test262\Js::includes($pd_apia_result, '31'), 'day is calculated correctly, ignoring the Pacific/Apia timezone');
$pt_los_angeles_result = $dtf_los_angeles->formatRange($pt_apia, $pt_los_angeles);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($pt_los_angeles_result, '2:00') && !\Calendrics\Tests\Test262\Js::includes($pt_los_angeles_result, '3:00'), 'hour is calculated correctly with the America/Los_Angeles timezone');
