<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-format-with-era.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$formatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(['en'], (object) ['era' => 'narrow', 'timeZone' => 'UTC']);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::startsWith($formatter->formatRange(new \Calendrics\Spec\PlainDate(2025, 11, 4), new \Calendrics\Spec\PlainDate(2025, 11, 5)), '11'), 'formatting a PlainDate should work');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::startsWith($formatter->formatRange(new \Calendrics\Spec\PlainYearMonth(2025, 11, 'gregory'), new \Calendrics\Spec\PlainYearMonth(2025, 12, 'gregory')), '11'), 'formatting a PlainYearMonth should work');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::startsWith($formatter->formatRange(new \Calendrics\Spec\PlainMonthDay(11, 4, 'gregory'), new \Calendrics\Spec\PlainMonthDay(11, 14, 'gregory')), '11'), 'formatting a PlainMonthDay should work');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::startsWith($formatter->formatRange(new \Calendrics\Spec\PlainTime(14, 46), new \Calendrics\Spec\PlainTime(17, 46)), '2'), 'formatting a PlainTime should work');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::startsWith($formatter->formatRange(new \Calendrics\Spec\PlainDateTime(2025, 11, 4, 14, 16, 0, 0, 0, 0, 'gregory'), new \Calendrics\Spec\PlainDateTime(2025, 11, 15, 14, 47, 0, 0, 0, 0, 'gregory')), '11'), 'formatting a PlainDateTime should work');
$dateResult = $formatter->formatRange(new \Calendrics\Tests\Test262\JsDate(0), new \Calendrics\Tests\Test262\JsDate(1));
Assert::assertTrue(\Calendrics\Tests\Test262\Js::startsWith($formatter->formatRange(new \Calendrics\Spec\Instant(0), new \Calendrics\Spec\Instant(1_000_000_000)), $dateResult), 'formatting an Instant should work');
