<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRange/temporal-plaindatetime-formatting-timezonename.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$locale = 'en-US';
$timeZoneNameStyles = ['long', 'short', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric'];
$pdt1 = new \Calendrics\Spec\PlainDateTime(2026, 1, 5, 11, 22);
$pdt2 = new \Calendrics\Spec\PlainDateTime(2026, 1, 5, 11, 23);
foreach ($timeZoneNameStyles as $timeZoneNameStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, (object) JsUndefined::strip(['timeZoneName' => $timeZoneNameStyle]));
$timeZoneDisplayName = \Calendrics\Tests\Test262\Js::arrayFind($dtf->formatToParts(\Calendrics\Tests\Test262\Js::dateUTC(2026, 0, 5, 11, 22)), function ($__dp0) { $type = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'type'); return $type === 'timeZoneName'; })->value;
$result = $dtf->formatRange($pdt1, $pdt2);
Assert::sameValue(is_string($result), true, "can format a PlainDateTime with timeZoneName = {$timeZoneNameStyle}");
Assert::incomplete('untranslatable: Array.prototype.indexOf()');
}
