<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-no-time-clip.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$calendars = ['iso8601', 'gregory'];
foreach ($calendars as $calendar) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', (object) JsUndefined::strip(['calendar' => $calendar]));
$minDate = new \Calendrics\Spec\PlainDate(-271_821, 4, 19, $calendar);
$maxDate = new \Calendrics\Spec\PlainDate(275_760, 9, 13, $calendar);
$dateResult = $dtf->formatRange($minDate, $maxDate);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateResult, '-271821') || \Calendrics\Tests\Test262\Js::includes($dateResult, '271822'), 'dateResult includes min year');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateResult, '4'), 'dateResult includes min month');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateResult, '19'), 'dateResult includes min day');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateResult, '275760'), 'dateResult includes max year');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateResult, '13'), 'result includes max day');
$minDateTime = new \Calendrics\Spec\PlainDateTime(-271_821, 4, 19, 0, 0, 0, 0, 0, 1, $calendar);
$maxDateTime = new \Calendrics\Spec\PlainDateTime(275_760, 9, 13, 23, 59, 59, 999, 999, 999, $calendar);
$dateTimeResult = $dtf->formatRange($minDateTime, $maxDateTime);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateTimeResult, '-271821') || \Calendrics\Tests\Test262\Js::includes($dateTimeResult, '271822'), 'dateTimeResult includes min year');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateTimeResult, '4'), 'dateTimeResult includes min month');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateTimeResult, '19'), 'dateTimeResult includes min day');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateTimeResult, '275760'), 'dateTimeResult includes max year');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($dateTimeResult, '13'), 'dateTimeResult includes max day');
$minYearMonth = new \Calendrics\Spec\PlainYearMonth(-271_821, 4, $calendar);
$maxYearMonth = new \Calendrics\Spec\PlainYearMonth(275_760, 9, $calendar);
$yearMonthResult = $dtf->formatRange($minYearMonth, $maxYearMonth);
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($yearMonthResult, '-271821') || \Calendrics\Tests\Test262\Js::includes($yearMonthResult, '271822'), 'yearMonthResult includes min year');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($yearMonthResult, '4'), 'yearMonthResult includes min month');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($yearMonthResult, '275760'), 'yearMonthResult includes max year');
Assert::assertTrue(\Calendrics\Tests\Test262\Js::includes($yearMonthResult, '9'), 'yearMonthResult includes max month');
}
