<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-resolved-time-zone.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$usDayPeriodSpace = (\Calendrics\Tests\Test262\Js::truthy($__logical0 = \Calendrics\Tests\Test262\Js::arrayFind(new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US', (object) ['timeStyle' => 'short'])->formatRangeToParts(0, 86_400), fn($part, $i, $parts) => $part->type === 'literal' && \Calendrics\Tests\Test262\Js::computedProperty($parts, $i + 1)->type === 'dayPeriod')?->value) ? $__logical0 : '');
$usDateRangeSeparator = \Calendrics\Tests\Test262\Js::arrayFind(new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US', (object) ['dateStyle' => 'short'])->formatRangeToParts(1 * 86_400 * 1000, 366 * 86_400 * 1000), fn($part) => $part->type === 'literal' && $part->source === 'shared')->value;
$formatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en-US', (object) ['timeZone' => 'Pacific/Apia']);
$date1 = new \Calendrics\Spec\PlainDate(2021, 8, 4);
$date2 = new \Calendrics\Spec\PlainDate(2021, 8, 5);
$dateResult = $formatter->formatRange($date1, $date2);
Assert::sameValue($dateResult, "8/4/2021{$usDateRangeSeparator}8/5/2021", 'plain dates');
$datetime1 = new \Calendrics\Spec\PlainDateTime(2021, 8, 4, 0, 30, 45, 123, 456, 789);
$datetime2 = new \Calendrics\Spec\PlainDateTime(2021, 8, 4, 23, 30, 45, 123, 456, 789);
Assert::incomplete('Intl range harness does not support compact shared-date intervals');
