<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/from/era-japanese.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$calendar = 'japanese';
$reiwa = \Calendrics\Spec\PlainYearMonth::from((object) JsUndefined::strip(['era' => 'reiwa', 'eraYear' => 2, 'month' => 1, 'calendar' => $calendar]));
$heisei = \Calendrics\Spec\PlainYearMonth::from((object) JsUndefined::strip(['era' => 'heisei', 'eraYear' => 2, 'month' => 1, 'calendar' => $calendar]));
$showa = \Calendrics\Spec\PlainYearMonth::from((object) JsUndefined::strip(['era' => 'showa', 'eraYear' => 2, 'month' => 1, 'calendar' => $calendar]));
$taisho = \Calendrics\Spec\PlainYearMonth::from((object) JsUndefined::strip(['era' => 'taisho', 'eraYear' => 2, 'month' => 1, 'calendar' => $calendar]));
$meiji = \Calendrics\Spec\PlainYearMonth::from((object) JsUndefined::strip(['era' => 'meiji', 'eraYear' => 6, 'month' => 1, 'calendar' => $calendar]));
$ce = \Calendrics\Spec\PlainYearMonth::from((object) JsUndefined::strip(['era' => 'ce', 'eraYear' => 1000, 'month' => 1, 'calendar' => $calendar]));
$bce = \Calendrics\Spec\PlainYearMonth::from((object) JsUndefined::strip(['era' => 'bce', 'eraYear' => 1, 'month' => 1, 'calendar' => $calendar]));
TemporalHelpers::assertPlainYearMonth($reiwa, 2020, 1, 'M01', "{$reiwa}", 'reiwa', 2);
TemporalHelpers::assertPlainYearMonth($heisei, 1990, 1, 'M01', "{$heisei}", 'heisei', 2);
TemporalHelpers::assertPlainYearMonth($showa, 1927, 1, 'M01', "{$showa}", 'showa', 2);
TemporalHelpers::assertPlainYearMonth($taisho, 1913, 1, 'M01', "{$taisho}", 'taisho', 2);
TemporalHelpers::assertPlainYearMonth($meiji, 1873, 1, 'M01', "{$meiji}", 'meiji', 6);
TemporalHelpers::assertPlainYearMonth($ce, 1000, 1, 'M01', "{$ce} (CE)", 'ce', 1000);
TemporalHelpers::assertPlainYearMonth($bce, 0, 1, 'M01', "{$bce} (BCE)", 'bce', 1);
