<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/since/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$instance = new \Calendrics\Spec\PlainYearMonth(2000, 5, 'gregory');
$base = (object) ['era' => 'ad', 'month' => 5, 'calendar' => 'gregory'];
foreach ([INF, -INF] as $inf) {
Assert::throws(\RangeException::class, function () use (&$instance, &$base, &$inf) { return $instance->since((object) JsUndefined::strip(array_merge((array) $base, ['eraYear' => $inf]))); }, "eraYear property cannot be {$inf}");
$calls = new \Calendrics\Tests\Test262\ObserverTrace();
$obj = TemporalHelpers::toPrimitiveObserver($calls, $inf, 'eraYear');
Assert::throws(\RangeException::class, function () use (&$instance, &$base, &$obj) { return $instance->since((object) JsUndefined::strip(array_merge((array) $base, ['eraYear' => $obj]))); }, '');
Assert::compareObserverTrace($calls, ['get eraYear.valueOf', 'call eraYear.valueOf'], 'it fails after fetching the primitive value');
}
