<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/monthCode/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::sameValue(new \Calendrics\Spec\PlainDateTime(1997, 8, 23, 5, 30, 13)->monthCode, 'M08', '');
