<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/until/inverse.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$dt = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789);
$later = new \Calendrics\Spec\PlainDateTime(2016, 3, 3, 18);
TemporalHelpers::assertDurationsEqual($dt->until($later), $later->since($dt), 'until and since act as inverses');
