<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/until/options-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$feb20 = new \Calendrics\Spec\PlainDateTime(2020, 2, 1, 0, 0);
$feb21 = new \Calendrics\Spec\PlainDateTime(2021, 2, 1, 0, 0);
$badOptions = [null, 1, 'obviously invalid', true, \Calendrics\Tests\Test262\JsSymbol::singleton(), 1];
foreach ($badOptions as $bad) {
Assert::throws(\TypeError::class, function () use (&$feb20, &$feb21, &$bad) { return $feb20->until($feb21, $bad); }, "unacceptable options (" . (gettype($bad)) . ")");
}
