<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/until/rounding-near-minimum-date.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$dt1 = new \Calendrics\Spec\PlainDateTime(-271_821, 5, 19, 0, 0, 0);
$dt2 = new \Calendrics\Spec\PlainDateTime(-271_821, 5, 18, 0, 0, 0);
$result = $dt1->until($dt2, (object) ['largestUnit' => 'year', 'smallestUnit' => 'day', 'roundingIncrement' => 2, 'roundingMode' => 'expand']);
TemporalHelpers::assertDuration($result, 0, 0, 0, -2, 0, 0, 0, 0, 0, 0, 'expand rounding of -1 day to increment 2 near minimum date gives -2 days');
