<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatToParts/dangi-calendar-dates.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$compareFormatToPartsSnapshot = function ($isoString, $expectedComponents) use (&$calendar, &$__dp0) {
$date = new \Calendrics\Tests\Test262\JsDate($isoString);
$formatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat("en-US-u-ca-{$calendar}", (object) ['timeZone' => 'UTC']);
$actualComponents = $formatter->formatToParts($date);
foreach ($expectedComponents as $expectedType => $expectedValue) {
$part = \Calendrics\Tests\Test262\Js::arrayFind($actualComponents, function ($__dp0) use (&$expectedType) { $type = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'type'); return $type === $expectedType; });
$contextMessage = "{$expectedType} component of {$isoString} formatted in {$calendar}";
Assert::notSameValue($part, null, "{$contextMessage} is missing");
Assert::sameValue(is_string($part->value), true, "{$contextMessage} is not a string");
Assert::assertTrue($part->value === \Calendrics\Tests\Test262\Js::toString($expectedValue) || $part->value === str_pad(\Calendrics\Tests\Test262\Js::toString($expectedValue), 2, '0', STR_PAD_LEFT), "{$contextMessage} has unexpected value");
}
};
$calendar = 'dangi';
$dangiYearOffset = new \Calendrics\Spec\PlainDate(1, 1, 1, $calendar)->year;
$compareFormatToPartsSnapshot('2000-01-01T00:00Z', (object) ['relatedYear' => 1999, 'month' => 11, 'day' => 25]);
$compareFormatToPartsSnapshot('1900-01-01T00:00Z', (object) ['relatedYear' => 1899, 'month' => 12, 'day' => 1]);
$compareFormatToPartsSnapshot('2050-01-01T00:00Z', (object) ['relatedYear' => 2049, 'month' => 12, 'day' => 8]);
