<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatToParts/temporal-plainyearmonth-formatting-timezonename.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$locale = 'en-US';
$timeZoneNameStyles = ['long', 'short', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric'];
$ym = new \Calendrics\Spec\PlainYearMonth(2026, 1, 'gregory', 1);
foreach ($timeZoneNameStyles as $timeZoneNameStyle) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat($locale, JsUndefined::strip(['timeZoneName' => $timeZoneNameStyle]));
$result = $dtf->formatToParts($ym);
Assert::assertTrue(is_array($result), "can format a PlainYearMonth with timeZoneName = {$timeZoneNameStyle}");
foreach ($result as $__obj__) {
$type = $__obj__['type'] ?? null;
Assert::notSameValue($type, 'timeZoneName', "formatting a PlainYearMonth with timeZoneName = {$timeZoneNameStyle} should not print a time zone");
}
}
