<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatToParts/temporal-objects-no-time-clip.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$findPart = function ($parts, $expectedType) use (&$__dp0) {
return \Calendrics\Tests\Test262\Js::arrayFind($parts, function ($__dp0) use (&$expectedType) { $type = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'type'); return $type === $expectedType; })->value;
};
$calendars = ['iso8601', 'gregory'];
foreach ($calendars as $calendar) {
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', (object) JsUndefined::strip(['calendar' => $calendar]));
$minDate = $dtf->formatToParts(new \Calendrics\Spec\PlainDate(-271_821, 4, 19, $calendar));
$yearPart = +$findPart($minDate, 'year');
Assert::assertTrue($yearPart === -271_821 || $yearPart === 271_822, 'minDate includes year');
Assert::sameValue(+$findPart($minDate, 'month'), 4, 'minDate includes month');
Assert::sameValue(+$findPart($minDate, 'day'), 19, 'minDate includes day');
$maxDate = $dtf->formatToParts(new \Calendrics\Spec\PlainDate(275_760, 9, 13, $calendar));
Assert::sameValue(+$findPart($maxDate, 'year'), 275_760, 'maxDate includes year');
Assert::sameValue(+$findPart($maxDate, 'month'), 9, 'maxDate includes month');
Assert::sameValue(+$findPart($maxDate, 'day'), 13, 'maxDate includes day');
$minDateTime = $dtf->formatToParts(new \Calendrics\Spec\PlainDateTime(-271_821, 4, 19, 0, 0, 0, 0, 0, 1, $calendar));
$yearPart = +$findPart($minDateTime, 'year');
Assert::assertTrue($yearPart === -271_821 || $yearPart === 271_822, 'minDateTime includes year');
Assert::sameValue(+$findPart($minDateTime, 'month'), 4, 'minDateTime includes month');
Assert::sameValue(+$findPart($minDateTime, 'day'), 19, 'minDateTime includes day');
$maxDateTime = $dtf->formatToParts(new \Calendrics\Spec\PlainDateTime(275_760, 9, 13, 23, 59, 59, 999, 999, 999, $calendar));
Assert::sameValue(+$findPart($maxDateTime, 'year'), 275_760, 'maxDateTime includes year');
Assert::sameValue(+$findPart($maxDateTime, 'month'), 9, 'maxDateTime includes month');
Assert::sameValue(+$findPart($maxDateTime, 'day'), 13, 'maxDateTime includes day');
$minYearMonth = $dtf->formatToParts(new \Calendrics\Spec\PlainYearMonth(-271_821, 4, $calendar));
$yearPart = +$findPart($minYearMonth, 'year');
Assert::assertTrue($yearPart === -271_821 || $yearPart === 271_822, 'minYearMonth includes year');
Assert::sameValue(+$findPart($minYearMonth, 'month'), 4, 'minYearMonth includes month');
$maxYearMonth = $dtf->formatToParts(new \Calendrics\Spec\PlainYearMonth(275_760, 9, $calendar));
Assert::sameValue(+$findPart($maxYearMonth, 'year'), 275_760, 'maxYearMonth includes year');
Assert::sameValue(+$findPart($maxYearMonth, 'month'), 9, 'maxYearMonth includes month');
}
