<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatToParts/temporal-zoneddatetime-not-supported.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$formatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat();
$__destruct__ = $formatter->resolvedOptions();
$timeZone = $__destruct__->timeZone;
$options = \Calendrics\Tests\Test262\Js::destructureRest($__destruct__, ['timeZone']);
$datetime = new \Calendrics\Spec\ZonedDateTime(0, $timeZone);
Assert::sameValue(is_string($datetime->toLocaleString(null, $options)), true, 'toLocaleString() with same options succeeds');
Assert::throws(\TypeError::class, function () use (&$formatter, &$datetime) { return $formatter->formatToParts($datetime); }, 'formatToParts() does not support Temporal.ZonedDateTime');
