<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatToParts/temporal-objects-no-time-clip-weekday.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$dtf = new \Calendrics\Tests\Test262\IntlDateTimeFormat('en', ['weekday' => 'long', 'year' => 'numeric', 'month' => 'long', 'day' => 'numeric', 'calendar' => 'iso8601']);
$minDate = new \Calendrics\Spec\PlainDate(-271_821, 4, 19);
$parts = $dtf->formatToParts($minDate);
$weekdayPart = \Calendrics\Tests\Test262\Js::arrayFind($parts, function ($p) { return $p->type === 'weekday'; });
Assert::notSameValue($weekdayPart, null, 'formatToParts should include a weekday part');
$weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
$isValidWeekday = \Calendrics\Tests\Test262\Js::indexOf($weekdays, $weekdayPart->value) >= 0;
Assert::assertTrue($isValidWeekday, 'weekday part should be a valid weekday name, got: ' . $weekdayPart->value);
$dayPart = \Calendrics\Tests\Test262\Js::arrayFind($parts, function ($p) { return $p->type === 'day'; });
Assert::notSameValue($dayPart, null, 'formatToParts should include a day part');
Assert::sameValue($dayPart->value, '19', 'day part should be 19');
$maxDate = new \Calendrics\Spec\PlainDate(275_760, 9, 13);
$maxParts = $dtf->formatToParts($maxDate);
$maxWeekdayPart = \Calendrics\Tests\Test262\Js::arrayFind($maxParts, function ($p) { return $p->type === 'weekday'; });
Assert::notSameValue($maxWeekdayPart, null, 'max date formatToParts should include a weekday part');
$isValidWeekday = \Calendrics\Tests\Test262\Js::indexOf($weekdays, $maxWeekdayPart->value) >= 0;
Assert::assertTrue($isValidWeekday, 'max date weekday part should be a valid weekday name, got: ' . $maxWeekdayPart->value);
$maxDayPart = \Calendrics\Tests\Test262\Js::arrayFind($maxParts, function ($p) { return $p->type === 'day'; });
Assert::notSameValue($maxDayPart, null, 'max date formatToParts should include a day part');
Assert::sameValue($maxDayPart->value, '13', 'max date day part should be 13');
