<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/DateTimeFormat/prototype/formatToParts/temporal-objects-not-overlapping-options.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$sampleEpochMs = 1_726_773_817_847;
$sampleEpochNs = 1_726_773_817_847_000_000;
$legacyDate = new \Calendrics\Tests\Test262\JsDate($sampleEpochMs);
$instant = new \Calendrics\Spec\Instant($sampleEpochNs);
$plainDateTime = new \Calendrics\Spec\PlainDateTime(2024, 9, 19, 12, 23, 37, 847);
$plainDate = new \Calendrics\Spec\PlainDate(2024, 9, 19);
$plainYearMonth = new \Calendrics\Spec\PlainYearMonth(2024, 9);
$plainMonthDay = new \Calendrics\Spec\PlainMonthDay(9, 19);
$plainTime = new \Calendrics\Spec\PlainTime(12, 23, 37, 847);
$dateStyleFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['dateStyle' => 'short', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$dateStyleResult = json_encode($dateStyleFormatter->formatToParts($legacyDate));
Assert::sameValue(json_encode($dateStyleFormatter->formatToParts($instant)), $dateStyleResult, 'Instant with dateStyle');
Assert::sameValue(json_encode($dateStyleFormatter->formatToParts($plainDateTime)), $dateStyleResult, 'PlainDateTime with dateStyle');
Assert::sameValue(json_encode($dateStyleFormatter->formatToParts($plainDate)), $dateStyleResult, 'PlainDate with dateStyle');
Assert::notSameValue(json_encode($dateStyleFormatter->formatToParts($plainYearMonth)), $dateStyleResult, 'PlainYearMonth with dateStyle should not throw but day is omitted');
Assert::notSameValue(json_encode($dateStyleFormatter->formatToParts($plainMonthDay)), $dateStyleResult, 'PlainMonthDay with dateStyle should not throw but year is omitted');
Assert::throws(\TypeError::class, function () use (&$dateStyleFormatter, &$plainTime) { return $dateStyleFormatter->formatToParts($plainTime); }, 'no overlap between dateStyle and PlainTime');
$yearFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['year' => 'numeric', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$yearResult = json_encode($yearFormatter->formatToParts($legacyDate));
Assert::sameValue(json_encode($yearFormatter->formatToParts($instant)), $yearResult, 'Instant with year');
Assert::sameValue(json_encode($yearFormatter->formatToParts($plainDateTime)), $yearResult, 'PlainDateTime with year');
Assert::sameValue(json_encode($yearFormatter->formatToParts($plainDate)), $yearResult, 'PlainDate with year');
Assert::sameValue(json_encode($yearFormatter->formatToParts($plainYearMonth)), $yearResult, 'PlainYearMonth with year');
Assert::throws(\TypeError::class, function () use (&$yearFormatter, &$plainMonthDay) { return $yearFormatter->formatToParts($plainMonthDay); }, 'no overlap between year and PlainMonthDay');
Assert::throws(\TypeError::class, function () use (&$yearFormatter, &$plainTime) { return $yearFormatter->formatToParts($plainTime); }, 'no overlap between year and PlainTime');
$dayFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['day' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$dayResult = json_encode($dayFormatter->formatToParts($legacyDate));
Assert::sameValue(json_encode($dayFormatter->formatToParts($instant)), $dayResult, 'Instant with day');
Assert::sameValue(json_encode($dayFormatter->formatToParts($plainDateTime)), $dayResult, 'PlainDateTime with day');
Assert::sameValue(json_encode($dayFormatter->formatToParts($plainDate)), $dayResult, 'PlainDate with day');
Assert::throws(\TypeError::class, function () use (&$dayFormatter, &$plainYearMonth) { return $dayFormatter->formatToParts($plainYearMonth); }, 'no overlap between day and PlainYearMonth');
Assert::sameValue(json_encode($dayFormatter->formatToParts($plainMonthDay)), $dayResult, 'PlainMonthDay with day');
Assert::throws(\TypeError::class, function () use (&$dayFormatter, &$plainTime) { return $dayFormatter->formatToParts($plainTime); }, 'no overlap between day and PlainTime');
$timeStyleFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['timeStyle' => 'long', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$timeStyleResult = json_encode($timeStyleFormatter->formatToParts($legacyDate));
Assert::sameValue(json_encode($timeStyleFormatter->formatToParts($instant)), $timeStyleResult, 'Instant with timeStyle');
$timeStylePlainDateTimeResult = json_encode($timeStyleFormatter->formatToParts($plainDateTime));
Assert::notSameValue($timeStylePlainDateTimeResult, $timeStyleResult, 'PlainDateTime with timeStyle should not throw but time zone is omitted');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainDate) { return $timeStyleFormatter->formatToParts($plainDate); }, 'no overlap between PlainDate and timeStyle');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainYearMonth) { return $timeStyleFormatter->formatToParts($plainYearMonth); }, 'no overlap between PlainYearMonth and timeStyle');
Assert::throws(\TypeError::class, function () use (&$timeStyleFormatter, &$plainMonthDay) { return $timeStyleFormatter->formatToParts($plainMonthDay); }, 'no overlap between PlainMonthDay and timeStyle');
Assert::sameValue(json_encode($timeStyleFormatter->formatToParts($plainTime)), $timeStylePlainDateTimeResult, 'PlainTime with timeStyle should be the same as PlainDateTime');
$hourFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['hour' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$hourResult = json_encode($hourFormatter->formatToParts($legacyDate));
Assert::sameValue(json_encode($hourFormatter->formatToParts($instant)), $hourResult, 'Instant with hour');
Assert::sameValue(json_encode($hourFormatter->formatToParts($plainDateTime)), $hourResult, 'PlainDateTime with hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainDate) { return $hourFormatter->formatToParts($plainDate); }, 'no overlap between PlainDate and hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainYearMonth) { return $hourFormatter->formatToParts($plainYearMonth); }, 'no overlap between PlainYearMonth and hour');
Assert::throws(\TypeError::class, function () use (&$hourFormatter, &$plainMonthDay) { return $hourFormatter->formatToParts($plainMonthDay); }, 'no overlap between PlainMonthDay and hour');
Assert::sameValue(json_encode($hourFormatter->formatToParts($plainTime)), $hourResult, 'PlainTime with hour');
$monthFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['month' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$monthResult = json_encode($monthFormatter->formatToParts($legacyDate));
$monthHourFormatter = new \Calendrics\Tests\Test262\IntlDateTimeFormat(null, ['month' => '2-digit', 'hour' => '2-digit', 'calendar' => 'iso8601', 'timeZone' => 'America/Vancouver']);
$monthHourResult = json_encode($monthHourFormatter->formatToParts($legacyDate));
Assert::sameValue(json_encode($monthHourFormatter->formatToParts($instant)), $monthHourResult, 'Instant with month+hour');
Assert::sameValue(json_encode($monthHourFormatter->formatToParts($plainDateTime)), $monthHourResult, 'PlainDateTime with month+hour');
Assert::sameValue(json_encode($monthHourFormatter->formatToParts($plainDate)), $monthResult, 'PlainDate with month+hour behaves the same as month');
Assert::sameValue(json_encode($monthHourFormatter->formatToParts($plainYearMonth)), $monthResult, 'PlainYearMonth with month+hour behaves the same as month');
Assert::sameValue(json_encode($monthHourFormatter->formatToParts($plainMonthDay)), $monthResult, 'PlainMonthDay with month+hour behaves the same as month');
Assert::sameValue(json_encode($monthHourFormatter->formatToParts($plainTime)), $hourResult, 'PlainTime with month+hour behaves the same as hour');
