<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/add/argument-mixed-sign.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\Duration(0, 0, 0, 1, 2, 3, 4, 987, 654, 321);
Assert::throws(\RangeException::class, function () use (&$instance) { return $instance->add((object) JsUndefined::strip(['hours' => 1, 'minutes' => -30])); }, "mixed positive and negative values always throw");
