<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/argument-string-optional-parts.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::assertZonedDateTimesEqual(\Calendrics\Spec\ZonedDateTime::from('1976-11-18T15:23:30-08[-08:00]'), new \Calendrics\Spec\ZonedDateTime(217_207_410_000_000_000, '-08:00'));
TemporalHelpers::assertZonedDateTimesEqual(\Calendrics\Spec\ZonedDateTime::from('1976-11-18T15-08:00[-08:00]'), new \Calendrics\Spec\ZonedDateTime(217_206_000_000_000_000, '-08:00'));
TemporalHelpers::assertZonedDateTimesEqual(\Calendrics\Spec\ZonedDateTime::from('2020-01-01[+09:00]'), new \Calendrics\Spec\ZonedDateTime(1_577_804_400_000_000_000, '+09:00'));
