<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/observable-get-overflow-argument-string-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['disambiguation' => 'compatible', 'offset' => 'ignore', 'overflow' => 'reject'], 'options');
Assert::throws(\RangeException::class, function () use (&$options) { return \Calendrics\Spec\ZonedDateTime::from('2020-13-34T25:60:60+99:99[UTC]', $options); }, '');
Assert::compareObserverTrace($actual, [], 'options read after string parsing');
