<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.disambiguation', 'get options.disambiguation.toString', 'call options.disambiguation.toString', 'get options.offset', 'get options.offset.toString', 'call options.offset.toString', 'get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'constrain', 'offset' => 'prefer', 'disambiguation' => 'compatible'], 'options');
Assert::throws(\RangeException::class, function () use (&$options) { \Calendrics\Spec\ZonedDateTime::from(['year' => 2025, 'monthCode' => 'M08L', 'day' => 14, 'timeZone' => 'UTC'], $options); }, 'exception thrown when month code is invalid for calendar');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
