<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$createOptionsObserver = function ($__dp0 = []) use (&$actual) {
$overflow = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'overflow') ?? 'constrain';
$disambiguation = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'disambiguation') ?? 'compatible';
$offset = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'offset') ?? 'reject';
return TemporalHelpers::propertyBagObserver($actual, (object) JsUndefined::strip(['overflow' => $overflow, 'disambiguation' => $disambiguation, 'offset' => $offset, 'extra' => 'property']), 'options');
};
$expectedOptionsReading = ['get options.disambiguation', 'get options.disambiguation.toString', 'call options.disambiguation.toString', 'get options.offset', 'get options.offset.toString', 'call options.offset.toString', 'get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$expectedOpsForPrimitiveOptions = ['get item.calendar', 'get item.day', 'get item.day.valueOf', 'call item.day.valueOf', 'get item.hour', 'get item.hour.valueOf', 'call item.hour.valueOf', 'get item.microsecond', 'get item.microsecond.valueOf', 'call item.microsecond.valueOf', 'get item.millisecond', 'get item.millisecond.valueOf', 'call item.millisecond.valueOf', 'get item.minute', 'get item.minute.valueOf', 'call item.minute.valueOf', 'get item.month', 'get item.month.valueOf', 'call item.month.valueOf', 'get item.monthCode', 'get item.monthCode.toString', 'call item.monthCode.toString', 'get item.nanosecond', 'get item.nanosecond.valueOf', 'call item.nanosecond.valueOf', 'get item.offset', 'get item.offset.toString', 'call item.offset.toString', 'get item.second', 'get item.second.valueOf', 'call item.second.valueOf', 'get item.timeZone', 'get item.year', 'get item.year.valueOf', 'call item.year.valueOf'];
$expected = array_merge($expectedOpsForPrimitiveOptions, $expectedOptionsReading);
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$from = TemporalHelpers::propertyBagObserver($actual, (object) ['year' => 2001, 'month' => 5, 'monthCode' => 'M05', 'day' => 2, 'hour' => 6, 'minute' => 54, 'second' => 32, 'millisecond' => 987, 'microsecond' => 654, 'nanosecond' => 321, 'offset' => '+00:00', 'calendar' => 'iso8601', 'timeZone' => 'UTC'], 'item', ['calendar', 'timeZone']);
$options = $createOptionsObserver();
\Calendrics\Spec\ZonedDateTime::from($from, $options);
Assert::compareObserverTrace($actual, $expected, 'order of operations');
$actual->clear();
\Calendrics\Spec\ZonedDateTime::from(new \Calendrics\Spec\ZonedDateTime(0, 'UTC'), $options);
Assert::compareObserverTrace($actual, $expectedOptionsReading, 'order of operations when cloning a ZonedDateTime instance');
$actual->clear();
\Calendrics\Spec\ZonedDateTime::from('2001-05-02T06:54:32.987654321+00:00[UTC]', $options);
Assert::compareObserverTrace($actual, $expectedOptionsReading, 'order of operations when parsing a string');
$actual->clear();
// JS-only (JS rejects non-object options via ToObject; PHP accepts null as "absent"): assert.throws(TypeError, () => Temporal.ZonedDateTime.from(from, null));
// JS-only (trace covers a call skipped above, so the tracker is empty here): assert.compareArray(actual, expectedOpsForPrimitiveOptions, "item fields are read before TypeError is thrown for primitive options");
$actual->clear();
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
