<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/overflow-options.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$bad = (object) ['year' => 2019, 'month' => 1, 'day' => 32, 'timeZone' => '+01:00'];
$expected = new \Calendrics\Spec\ZonedDateTime(1_548_889_200_000_000_000, '+01:00');
Assert::throws(\RangeException::class, function () use (&$bad) { return \Calendrics\Spec\ZonedDateTime::from($bad, (object) ['overflow' => 'reject']); }, '');
TemporalHelpers::assertZonedDateTimesEqual(\Calendrics\Spec\ZonedDateTime::from($bad), $expected);
TemporalHelpers::assertZonedDateTimesEqual(\Calendrics\Spec\ZonedDateTime::from($bad, (object) ['overflow' => 'constrain']), $expected);
