<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/since/argument-zoneddatetime.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkToTemporalInstantFastPath(function ($datetime) use (&$instant, &$result) { $instant = new \Calendrics\Spec\Instant(1_000_000_000_000_000_000); $result = $instant->since($datetime); Assert::sameValue($result->total((object) ['unit' => 'nanoseconds']), -987_654_321, 'nanoseconds result'); });
