<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/from/argument-plainyearmonth.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$orig = new \Calendrics\Spec\PlainYearMonth(2000, 5, null, 7);
$result = \Calendrics\Spec\PlainYearMonth::from($orig);
TemporalHelpers::assertPlainYearMonth($result, 2000, 5, 'M05', 'PlainYearMonth is copied', null, null, 7);
Assert::sameValue($result->calendarId, $orig->calendarId, 'Calendar is copied');
Assert::notSameValue($result, $orig, 'When a PlainYearMonth is given, the returned value is not the original PlainYearMonth');
