<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/from/observable-get-overflow-argument-primitive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = new \Temporal\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'reject'], 'options');
$result = \Temporal\Spec\PlainYearMonth::from('2021-05', $options);
Assert::compareObserverTrace($actual, $expected, 'Successful call');
TemporalHelpers::assertPlainYearMonth($result, 2021, 5, 'M05');
$actual->clear();
Assert::throws(\TypeError::class, function () use (&$options) { return \Temporal\Spec\PlainYearMonth::from(7, $options); }, '');
Assert::compareObserverTrace($actual, [], 'Failing call before options is processed');
$actual->clear();
Assert::throws(\RangeException::class, function () use (&$options) { return \Temporal\Spec\PlainYearMonth::from(['year' => 2021, 'month' => 13], $options); }, '');
Assert::compareObserverTrace($actual, $expected, 'Failing call after options is processed');
