<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/from/overflow-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$validValues = [new \Calendrics\Spec\PlainYearMonth(2000, 5), '2000-05'];
foreach ($validValues as $value) {
$explicit = \Calendrics\Spec\PlainYearMonth::from($value, []);
TemporalHelpers::assertPlainYearMonth($explicit, 2000, 5, 'M05', 'overflow is ignored');
$implicit = \Calendrics\Spec\PlainYearMonth::from($value, []);
TemporalHelpers::assertPlainYearMonth($implicit, 2000, 5, 'M05', 'overflow is ignored');
$lambda = \Calendrics\Spec\PlainYearMonth::from($value, function () {  });
TemporalHelpers::assertPlainYearMonth($lambda, 2000, 5, 'M05', 'overflow is ignored');
}
$propertyBag = ['year' => 2000, 'month' => 13];
$explicit = \Calendrics\Spec\PlainYearMonth::from($propertyBag, []);
TemporalHelpers::assertPlainYearMonth($explicit, 2000, 12, 'M12', 'default overflow is constrain');
$implicit = \Calendrics\Spec\PlainYearMonth::from($propertyBag, []);
TemporalHelpers::assertPlainYearMonth($implicit, 2000, 12, 'M12', 'default overflow is constrain');
$lambda = \Calendrics\Spec\PlainYearMonth::from($propertyBag, function () {  });
TemporalHelpers::assertPlainYearMonth($lambda, 2000, 12, 'M12', 'default overflow is constrain');
