<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/month/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::sameValue(new \Calendrics\Spec\PlainDate(2021, 7, 15)->month, 7, '');
Assert::sameValue(\Calendrics\Spec\PlainDate::from('2019-03-15')->month, 3, '');
