<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/round/smallestunit-plurals-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$datetime = new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 12, 34, 56, 789, 999, 999);
$validUnits = ['day', 'hour', 'minute', 'second', 'millisecond', 'microsecond', 'nanosecond'];
TemporalHelpers::checkPluralUnitsAccepted(function ($smallestUnit) use (&$datetime) { return $datetime->round(JsUndefined::strip(['smallestUnit' => $smallestUnit])); }, $validUnits);
TemporalHelpers::checkPluralUnitsAccepted(function ($smallestUnit) use (&$datetime) { return $datetime->round($smallestUnit); }, $validUnits);
