<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/compare/argument-plaindate.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$datetime = new \Calendrics\Spec\PlainDateTime(2000, 5, 2, 12, 34, 56, 987, 654, 321);
TemporalHelpers::checkToTemporalPlainDateTimeFastPath(function ($date) use (&$result, &$datetime) { $result = \Calendrics\Spec\PlainDateTime::compare($date, $datetime); Assert::sameValue($result, -1, 'PlainDate is converted to midnight'); });
TemporalHelpers::checkToTemporalPlainDateTimeFastPath(function ($date) use (&$result, &$datetime) { $result = \Calendrics\Spec\PlainDateTime::compare($datetime, $date); Assert::sameValue($result, 1, 'PlainDate is converted to midnight'); });
