<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/compare/argument-number.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$numbers = [1, 19_761_118, -19_761_118, 1_234_567_890];
foreach ($numbers as $arg) {
Assert::throws(\TypeError::class, function () use (&$arg) { return \Calendrics\Spec\PlainDateTime::compare($arg, new \Calendrics\Spec\PlainDateTime(1976, 11, 18)); }, "A number ({$arg}) is not a valid ISO string for PlainDateTime (first argument)");
Assert::throws(\TypeError::class, function () use (&$arg) { return \Calendrics\Spec\PlainDateTime::compare(new \Calendrics\Spec\PlainDateTime(1976, 11, 18), $arg); }, "A number ({$arg}) is not a valid ISO string for PlainDateTime (second argument)");
}
