<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/monthsInYear/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$ym = new \Calendrics\Spec\PlainYearMonth(1976, 11);
Assert::sameValue($ym->monthsInYear, 12, '');
