<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/compare/argument-plaindatetime.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$sameDate = new \Calendrics\Spec\PlainDate(2000, 5, 2);
$earlierDate = new \Calendrics\Spec\PlainDate(1920, 7, 3);
$laterDate = new \Calendrics\Spec\PlainDate(2005, 1, 12);
TemporalHelpers::checkPlainDateTimeConversionFastPath(function ($datetime) use (&$result, &$sameDate) { $result = \Calendrics\Spec\PlainDate::compare($datetime, $sameDate); Assert::sameValue($result, 0, 'First argument, same date: comparison result'); }, 'First argument, same date');
TemporalHelpers::checkPlainDateTimeConversionFastPath(function ($datetime) use (&$result, &$earlierDate) { $result = \Calendrics\Spec\PlainDate::compare($datetime, $earlierDate); Assert::sameValue($result, 1, 'First argument, earlier date: comparison result'); }, 'First argument, earlier date');
TemporalHelpers::checkPlainDateTimeConversionFastPath(function ($datetime) use (&$result, &$laterDate) { $result = \Calendrics\Spec\PlainDate::compare($datetime, $laterDate); Assert::sameValue($result, -1, 'First argument, later date: comparison result'); }, 'First argument, later date');
TemporalHelpers::checkPlainDateTimeConversionFastPath(function ($datetime) use (&$result, &$sameDate) { $result = \Calendrics\Spec\PlainDate::compare($sameDate, $datetime); Assert::sameValue($result, 0, 'Second argument, same date: comparison result'); }, 'Second argument, same date');
TemporalHelpers::checkPlainDateTimeConversionFastPath(function ($datetime) use (&$result, &$earlierDate) { $result = \Calendrics\Spec\PlainDate::compare($earlierDate, $datetime); Assert::sameValue($result, -1, 'Second argument, earlier date: comparison result'); }, 'Second argument, earlier date');
TemporalHelpers::checkPlainDateTimeConversionFastPath(function ($datetime) use (&$result, &$laterDate) { $result = \Calendrics\Spec\PlainDate::compare($laterDate, $datetime); Assert::sameValue($result, 1, 'Second argument, later date: comparison result'); }, 'Second argument, later date');
