<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/compare/argument-propertybag-calendar-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$wrongTypeTests = [[null, 'null'], [true, 'boolean'], [1, 'number'], [1, 'bigint'], [19_970_327, 'large number'], [-19_970_327, 'negative number'], [1_234_567_890, 'very large integer'], [\Calendrics\Tests\Test262\JsSymbol::singleton(), 'symbol'], [(object) [], 'object'], [new \Calendrics\Spec\Duration(), 'duration instance']];
foreach ($wrongTypeTests as $__entry__) {
[$calendar, $description] = array_pad($__entry__, 2, null);
if ($calendar === null) { continue; }
$arg = (object) JsUndefined::strip(['year' => 2019, 'monthCode' => 'M11', 'day' => 1, 'calendar' => $calendar]);
Assert::throws(\TypeError::class, function () use (&$arg) { return \Calendrics\Spec\PlainDate::compare($arg, new \Calendrics\Spec\PlainDate(1976, 11, 18)); }, "{$description} is not a valid property bag and does not convert to a string (first argument)");
Assert::throws(\TypeError::class, function () use (&$arg) { return \Calendrics\Spec\PlainDate::compare(new \Calendrics\Spec\PlainDate(1976, 11, 18), $arg); }, "{$description} is not a valid property bag and does not convert to a string (second argument)");
}
