<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/compare/argument-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$d1 = \Calendrics\Spec\PlainDate::from('1976-11-18');
$d2 = \Calendrics\Spec\PlainDate::from('2019-06-30');
Assert::sameValue(\Calendrics\Spec\PlainDate::compare('1976-11-18', $d2), -1, 'first argument');
Assert::sameValue(\Calendrics\Spec\PlainDate::compare('2019-06-30', $d2), 0, 'first argument');
Assert::sameValue(\Calendrics\Spec\PlainDate::compare('2024-01-12', $d2), 1, 'first argument');
Assert::sameValue(\Calendrics\Spec\PlainDate::compare($d1, '2019-06-30'), -1, 'second argument');
Assert::sameValue(\Calendrics\Spec\PlainDate::compare($d1, '1976-11-18'), 0, 'second argument');
Assert::sameValue(\Calendrics\Spec\PlainDate::compare($d1, '1926-07-07'), 1, 'second argument');
