<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/compare/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$other = new \Calendrics\Spec\PlainDate(2000, 5, 2);
$base = ['year' => 2000, 'month' => 5, 'day' => 2];
foreach ([INF, -INF] as $inf) {
foreach (['year', 'month', 'day'] as $prop) {
Assert::throws(\RangeException::class, function () use (&$base, &$prop, &$inf, &$other) { return \Calendrics\Spec\PlainDate::compare(JsUndefined::strip(array_merge($base, [$prop => $inf])), $other); }, "{$prop} property cannot be {$inf}");
Assert::throws(\RangeException::class, function () use (&$other, &$base, &$prop, &$inf) { return \Calendrics\Spec\PlainDate::compare($other, JsUndefined::strip(array_merge($base, [$prop => $inf]))); }, "{$prop} property cannot be {$inf}");
$calls1 = new \Calendrics\Tests\Test262\ObserverTrace();
$obj1 = TemporalHelpers::toPrimitiveObserver($calls1, $inf, $prop);
Assert::throws(\RangeException::class, function () use (&$base, &$prop, &$obj1, &$other) { return \Calendrics\Spec\PlainDate::compare(JsUndefined::strip(array_merge($base, [$prop => $obj1])), $other); }, '');
Assert::compareObserverTrace($calls1, ["get {$prop}.valueOf", "call {$prop}.valueOf"], 'it fails after fetching the primitive value');
$calls2 = new \Calendrics\Tests\Test262\ObserverTrace();
$obj2 = TemporalHelpers::toPrimitiveObserver($calls2, $inf, $prop);
Assert::throws(\RangeException::class, function () use (&$other, &$base, &$prop, &$obj2) { return \Calendrics\Spec\PlainDate::compare($other, JsUndefined::strip(array_merge($base, [$prop => $obj2]))); }, '');
Assert::compareObserverTrace($calls2, ["get {$prop}.valueOf", "call {$prop}.valueOf"], 'it fails after fetching the primitive value');
}
}
