<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/compare/leap-second.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$arg = '2016-12-31T23:59:60';
$result = \Calendrics\Spec\PlainDate::compare($arg, new \Calendrics\Spec\PlainDate(2016, 12, 31));
Assert::sameValue($result, 0, 'leap second is a valid ISO string for PlainDate (first argument)');
$result = \Calendrics\Spec\PlainDate::compare(new \Calendrics\Spec\PlainDate(2016, 12, 31), $arg);
Assert::sameValue($result, 0, 'leap second is a valid ISO string for PlainDate (second argument)');
$arg = ['year' => 2016, 'month' => 12, 'day' => 31, 'hour' => 23, 'minute' => 59, 'second' => 60];
$result = \Calendrics\Spec\PlainDate::compare($arg, new \Calendrics\Spec\PlainDate(2016, 12, 31));
Assert::sameValue($result, 0, 'second: 60 is ignored in property bag for PlainDate (first argument)');
$result = \Calendrics\Spec\PlainDate::compare(new \Calendrics\Spec\PlainDate(2016, 12, 31), $arg);
Assert::sameValue($result, 0, 'second: 60 is ignored in property bag for PlainDate (second argument)');
