<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/compare/use-internal-slots.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$CustomError = function () {
};
// JS-only (getter-only Temporal subclass; getters never fire in PHP, aliased to PlainDate): class AvoidGettersDate extends Temporal.PlainDate { get year() { throw new CustomError(); } get month() { throw new CustomError(); } get day() { throw new Cust…
$one = new \Calendrics\Spec\PlainDate(2000, 5, 2);
$two = new \Calendrics\Spec\PlainDate(2006, 3, 25);
Assert::sameValue(\Calendrics\Spec\PlainDate::compare($one, $two), -1, '');
