<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/from/month-code-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$monthCodeValues = [5, 5, false, \Calendrics\Tests\Test262\JsSymbol::singleton(), null, new \Calendrics\Tests\Test262\JsNonStringPrimitive(5)];
$year = 2026;
foreach ($monthCodeValues as $monthCode) {
if ($monthCode instanceof \Calendrics\Tests\Test262\JsNonStringPrimitive) { continue; }
Assert::throws(\TypeError::class, function () use (&$year, &$monthCode) { return \Calendrics\Spec\PlainDate::from((object) JsUndefined::strip(['year' => $year, 'monthCode' => $monthCode, 'day' => 1])); }, ($monthCode instanceof \Calendrics\Tests\Test262\JsSymbol ? 'Symbol should be rejected as month code' : "month code {$monthCode} should be rejected"));
}
