<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/from/observable-get-overflow-argument-string-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'constrain'], 'options');
Assert::throws(\RangeException::class, function () use (&$options) { return \Calendrics\Spec\PlainDate::from('2020-13-34', $options); }, '');
Assert::compareObserverTrace($actual, [], 'options read after ISO string parsing');
