<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/from/options-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$fields = ['year' => 2000, 'month' => 13, 'day' => 2];
$explicit = \Calendrics\Spec\PlainDate::from($fields);
Assert::sameValue($explicit->month, 12, 'default overflow is constrain');
$implicit = \Calendrics\Spec\PlainDate::from($fields);
Assert::sameValue($implicit->month, 12, 'default overflow is constrain');
$implicitEmpty = \Calendrics\Spec\PlainDate::from($fields, []);
Assert::sameValue($implicitEmpty->month, 12, 'default overflow is constrain');
$lambda = \Calendrics\Spec\PlainDate::from($fields, function () {  });
Assert::sameValue($lambda->month, 12, 'default overflow is constrain');
