<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/calendar-temporal-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkToTemporalCalendarFastPath(function ($temporalObject) use (&$duration) { $duration = new \Calendrics\Spec\Duration(1, 1, 1, 1, 1, 1, 1); $duration->total(JsUndefined::strip(['unit' => 'seconds', 'relativeTo' => JsUndefined::strip(['year' => 2000, 'month' => 1, 'day' => 1, 'calendar' => $temporalObject])])); });
