<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.relativeTo', 'get options.unit', 'get options.unit.toString', 'call options.unit.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['unit' => 'weeks'], 'options');
$instance = new \Calendrics\Spec\Duration(1);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->total($options); }, 'exception thrown when total of calendar unit requested without relativeTo');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
