<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$createOptionsObserver = function ($__dp0 = []) use (&$actual) {
$unit = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'unit') ?? 'nanoseconds';
$roundingMode = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'roundingMode') ?? 'halfExpand';
$roundingIncrement = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'roundingIncrement') ?? 1;
$relativeTo = \Calendrics\Tests\Test262\Js::destructure($__dp0, 'relativeTo') ?? null;
return TemporalHelpers::propertyBagObserver($actual, (object) JsUndefined::strip(['unit' => $unit, 'roundingMode' => $roundingMode, 'roundingIncrement' => $roundingIncrement, 'relativeTo' => $relativeTo]), 'options');
};
Assert::incomplete('untranslatable: Object.defineProperty');
