<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/precision-exact-mathematical-values-5.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$seconds = 8_692_288_669_465_520;
$milliseconds = 513;
$d = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, $seconds, $milliseconds);
$result = $d->total(['unit' => 'milliseconds']);
$expectedMilliseconds = 8.69228866946552E+18;
Assert::sameValue($expectedMilliseconds, 8_692_288_669_465_520_128, 'check expected value (ms)');
Assert::sameValue($result, $expectedMilliseconds, 'BalanceTimeDuration should implement floating-point calculation correctly for largestUnit milliseconds');
$microseconds = 373_761;
$d = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, $seconds, 0, $microseconds);
$result = $d->total(['unit' => 'microseconds']);
$expectedMicroseconds = 8.692288669465521E+21;
Assert::sameValue($expectedMicroseconds, 8.692_288_669_465_521e+21, 'check expected value (µs)');
Assert::sameValue($result, $expectedMicroseconds, 'BalanceTimeDuration should implement floating-point calculation correctly for largestUnit microseconds');
$nanoseconds = 321_414_345;
$d = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, $seconds, 0, 0, $nanoseconds);
$result = $d->total(['unit' => 'nanoseconds']);
$expectedNanoseconds = 8.692288669465521E+24;
Assert::sameValue($expectedNanoseconds, 8.692_288_669_465_521e+24, 'check expected value (ns)');
Assert::sameValue($result, $expectedNanoseconds, 'BalanceTimeDuration should implement floating-point calculation correctly for largestUnit nanoseconds');
$d = new \Calendrics\Spec\Duration(0, 0, 5, 5);
$result = $d->total(['unit' => 'months', 'relativeTo' => '1972-01-31']);
$expectedMonths = 1.3_548_387_096_774_193;
Assert::sameValue($result, $expectedMonths, 'NudgeToCalendarUnit should implement floating-point calculation correctly for largestUnit months');
