<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/relativeto-plaindate-add24hourdaystonormalizedtimeduration-out-of-range.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$duration = \Calendrics\Spec\Duration::from(JsUndefined::strip(['years' => 1, 'seconds' => 2 ** 53 - 1]));
$relativeTo = new \Calendrics\Spec\PlainDate(2000, 1, 1);
Assert::throws(\RangeException::class, function () use (&$duration, &$relativeTo) { return $duration->total(JsUndefined::strip(['relativeTo' => $relativeTo, 'unit' => 'days'])); }, '');
