<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/throws-if-date-time-invalid-with-plaindate-relative.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$duration = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, 0, 0, 0, 1);
$relativeTo = new \Calendrics\Spec\PlainDate(275_760, 9, 13);
$totalOf = (object) JsUndefined::strip(['unit' => 'years', 'relativeTo' => $relativeTo]);
Assert::throws(\RangeException::class, function () use (&$duration, &$totalOf) { return $duration->total($totalOf); }, '');
