<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/sign/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\Duration(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
Assert::sameValue($instance->sign, 1, '');
$smallInstance = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, 0, 0, 0, 1);
Assert::sameValue($smallInstance->sign, 1, '');
$negInstance = new \Calendrics\Spec\Duration(-1, -2, -3, -4, -5, -6, -7, -8, -9, -10);
Assert::sameValue($negInstance->sign, -1, '');
$smallNegInstance = new \Calendrics\Spec\Duration(0, 0, 0, 0, 0, 0, 0, 0, 0, -1);
Assert::sameValue($smallNegInstance->sign, -1, '');
