<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/from/dst-skipped-cross-midnight.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$startOfDay = \Calendrics\Spec\ZonedDateTime::from('1919-03-31[America/Toronto]');
$midnightDisambiguated = \Calendrics\Spec\ZonedDateTime::from('1919-03-31T00[America/Toronto]');
TemporalHelpers::assertDuration($startOfDay->until($midnightDisambiguated), 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 'start of day is 30 minutes earlier than following the disambiguation strategy for midnight');
Assert::sameValue($midnightDisambiguated->epochNanoseconds, \Calendrics\Spec\ZonedDateTime::from((object) ['year' => 1919, 'month' => 3, 'day' => 31, 'timeZone' => 'America/Toronto'])->epochNanoseconds, 'start of day magic doesn\'t happen with property bag, missing properties are zero');
