<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/monthsInYear/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$datetime = new \Calendrics\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789, 'iso8601');
Assert::sameValue($datetime->monthsInYear, 12, 'check months in year information');
Assert::sameValue(new \Calendrics\Spec\PlainDateTime(1234, 8, 23, 5, 30, 13)->monthsInYear, 12, '');
