<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/add/argument-duration-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$nov94 = \Calendrics\Spec\PlainYearMonth::from('1994-11');
$diff = \Calendrics\Spec\Duration::from('P18Y7M');
TemporalHelpers::assertPlainYearMonth($nov94->add($diff), 2013, 6, 'M06');
