<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/add/argument-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$instance = \Calendrics\Spec\PlainYearMonth::from(['year' => 2000, 'month' => 5]);
$result = $instance->add('P3M');
TemporalHelpers::assertPlainYearMonth($result, 2000, 8, 'M08');
