<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/add/limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$max = \Calendrics\Spec\PlainYearMonth::from('+275760-09');
foreach (['reject', 'constrain'] as $overflow) {
Assert::throws(\RangeException::class, function () use (&$max, &$overflow) { return $max->add((object) ['months' => 1], (object) JsUndefined::strip(['overflow' => $overflow])); }, $overflow);
}
