<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/add/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'constrain'], 'options');
$instance = new \Calendrics\Spec\PlainYearMonth(-271_821, 4);
Assert::throws(\RangeException::class, function () use (&$instance, &$options) { $instance->add(new \Calendrics\Spec\Duration(0, 1), $options); }, 'exception thrown when converting -271821-04 to date');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
$actual->clear();
$instance2 = new \Calendrics\Spec\PlainYearMonth(1999, 12);
Assert::throws(\RangeException::class, function () use (&$instance2, &$options) { $instance2->add(new \Calendrics\Spec\Duration(0, 0, 1), $options); }, 'exception thrown when attempting to add too-low unit');
Assert::compareObserverTrace($actual, $expected, 'all options should be read first');
