<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/add/subclassing-ignored.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkSubclassingIgnored(\Calendrics\Spec\PlainYearMonth::class, [2000, 5], 'add', [(object) ['months' => 1]], fn($result) => TemporalHelpers::assertPlainYearMonth($result, 2000, 6, 'M06'));
