<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/argument-convert.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read(new \Calendrics\Spec\ZonedDateTime(false, 'UTC')), 0, 'boolean defaults');
Assert::sameValue(\Calendrics\Tests\Test262\JsEpoch::read(new \Calendrics\Spec\ZonedDateTime(true, 'UTC')), 1, 'boolean defaults');
Assert::throws(\TypeError::class, fn() => new \Calendrics\Spec\ZonedDateTime(\Calendrics\Tests\Test262\JsSymbol::singleton(), 'UTC'), "symbol");
Assert::throws(\TypeError::class, fn() => new \Calendrics\Spec\ZonedDateTime(null, 'UTC'), "undefined");
