<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/calendar-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$wrongTypeTests = [[null, 'null'], [true, 'boolean'], [1, 'number'], [1, 'bigint'], [-19_761_118, 'negative number'], [19_761_118, 'large positive number'], [1_234_567_890, 'large integer'], [\Calendrics\Tests\Test262\JsSymbol::singleton(), 'symbol'], [(object) [], 'object'], [new \Calendrics\Spec\Duration(), 'duration instance']];
foreach ($wrongTypeTests as $__entry__) {
[$arg, $description] = array_pad($__entry__, 2, null);
Assert::throws(\TypeError::class, function () use (&$arg) { return new \Calendrics\Spec\ZonedDateTime(0, 'UTC', $arg); }, "{$description} is not a valid calendar");
}
