<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/timezone-case-insensitive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$timeZone = 'uTc';
$result = new \Calendrics\Spec\ZonedDateTime(0, $timeZone);
Assert::sameValue($result->timeZoneId, 'UTC', "Time zone created from string \"{$timeZone}\"");
