<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/fields-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
foreach (TemporalHelpers::isoPlainMonthDayStringsValid() as $argument) {
$plainMonthDay = \Calendrics\Spec\PlainMonthDay::from($argument);
Assert::notSameValue($plainMonthDay, $argument, "from {$argument} converts");
TemporalHelpers::assertPlainMonthDay($plainMonthDay, 'M10', 1, "from {$argument}");
Assert::sameValue($plainMonthDay->calendarId, 'iso8601', "from {$argument} calendar");
}
foreach (TemporalHelpers::isoPlainMonthDayStringsInvalid() as $arg) {
Assert::throws(\RangeException::class, function () use (&$arg) { return \Calendrics\Spec\PlainMonthDay::from($arg); }, "\"{$arg}\" not a valid PlainMonthDay string");
}
