<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/iso-year-used-only-for-overflow.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$outOfRangeCommonYear = -999_999;
$outOfRangeLeapYear = -1_000_000;
$result = \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['year' => $outOfRangeCommonYear, 'month' => 1, 'day' => 1]));
TemporalHelpers::assertPlainMonthDay($result, 'M01', 1, 'ISO year is not checked for range');
$commonResult = \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['year' => $outOfRangeCommonYear, 'monthCode' => 'M02', 'day' => 29]));
TemporalHelpers::assertPlainMonthDay($commonResult, 'M02', 28, 'ISO year is used to apply overflow');
Assert::throws(\RangeException::class, function () use (&$outOfRangeCommonYear) { \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['year' => $outOfRangeCommonYear, 'monthCode' => 'M02', 'day' => 29]), (object) ['overflow' => 'reject']); }, 'ISO year is used to apply overflow');
$leapResult = \Calendrics\Spec\PlainMonthDay::from((object) JsUndefined::strip(['year' => $outOfRangeLeapYear, 'monthCode' => 'M02', 'day' => 29]));
TemporalHelpers::assertPlainMonthDay($leapResult, 'M02', 29, 'ISO year is used to apply overflow');
