<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/negative-month-or-day.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
Assert::throws(\RangeException::class, fn() => \Calendrics\Spec\PlainMonthDay::from(JsUndefined::strip(['day' => 1, 'month' => -1])), '');
Assert::throws(\RangeException::class, fn() => \Calendrics\Spec\PlainMonthDay::from(JsUndefined::strip(['month' => 1, 'day' => -1])), '');
