<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/observable-get-overflow-argument-primitive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$expected = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = new \Calendrics\Tests\Test262\ObserverTrace();
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['overflow' => 'reject'], 'options');
$result = \Calendrics\Spec\PlainMonthDay::from('05-17', $options);
Assert::compareObserverTrace($actual, $expected, 'Successful call');
TemporalHelpers::assertPlainMonthDay($result, 'M05', 17);
$actual->clear();
Assert::throws(\TypeError::class, function () use (&$options) { return \Calendrics\Spec\PlainMonthDay::from(7, $options); }, '');
Assert::compareObserverTrace($actual, [], 'Failing call before options is processed');
$actual->clear();
Assert::throws(\RangeException::class, function () use (&$options) { return \Calendrics\Spec\PlainMonthDay::from((object) ['monthCode' => 'M02', 'day' => 30], $options); }, '');
Assert::compareObserverTrace($actual, $expected, 'Failing call after options is processed');
