<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/options-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
use Calendrics\Tests\Test262\TemporalHelpers;
$fields = ['month' => 2, 'day' => 31];
$explicit = \Calendrics\Spec\PlainMonthDay::from($fields);
TemporalHelpers::assertPlainMonthDay($explicit, 'M02', 29, 'default overflow is constrain');
$implicit = \Calendrics\Spec\PlainMonthDay::from($fields);
TemporalHelpers::assertPlainMonthDay($implicit, 'M02', 29, 'default overflow is constrain');
$lambda = \Calendrics\Spec\PlainMonthDay::from($fields, function () {  });
TemporalHelpers::assertPlainMonthDay($lambda, 'M02', 29, 'default overflow is constrain');
