<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/eraYear/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Calendrics\Tests\Test262\Assert;
use Calendrics\Tests\Test262\JsUndefined;
$instance = new \Calendrics\Spec\PlainDate(2000, 3, 6);
Assert::sameValue($instance->eraYear, null, '');
